<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  style="height:100%;">
                            <thead>
                                <tr>
                                    <th class="no-sort">S.No.</th>
                                    <th> Semester </th> 
                                    <th>course Category</th>
                                    <th> Course </th> 
                                    <th>Student Name</th>
                                    <th>UID</th>
                                    <th>Total class conducted</th>
                                    <th>Total class Attended</th>
                                    <th> Percent</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {

                                    foreach ($this->paginator as $results) {
                                     //echo"<pre>";print_r($results);die;
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>						

                                            <td><?php echo $results['term_name']; ?></td>
                                            <td><?php echo $results['cc_name']; ?></td>
                                            <td><?php  if(empty($results['department'])){ echo $results['course_name'];}else{ echo $results['department'];
                                            }?></td>
                                            
                                           
                                            
                                            <td><?php echo $results['studentName']; ?></td>
                                            <td><?php echo $results['f_id']; ?></td>
                                            <input type="hidden" name="batch_code[]" id="batch_code" value="<?php echo $results['batch']?$results['batch']:$results['batch']; ?>" />
                                            <input type="hidden" name="u_id[]" id="student_id" value="<?php echo $results['f_id']; ?>" /> 
                                            <td><input type="text" name=conducted_class[]" class="conducted_class"  id = "conducted_class" value="<?= $results['total_class']; ?>" /></td>
                                            <td><input type="text" name="attended_class[]" class="attended_class"  id = "attended_class" value="<?= $results['present']; ?>" /></td>
                                            
                                            
                                            
                                           <td style="text-align:center" class="total_percent">
                                                <?php  
                                              
                                                $total_percent = round($results['present']/$results['total_class'] * 100);
                                                
                                                if($total_percent >= 75){
                                                   echo "<b style='color:green;'>$total_percent</b>";
                                                }else{
                                                   echo "<b style='color:red;'>$total_percent</b>"; 
                                                }
                                                
                                                ?>
                                            </td>
                                            
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
<script>
    setDatatables();
    $(".allowedBtn").click(function() {
    let update_id = $(this).closest("td").find("#update_id").val();
    let buttonValue=$(this).closest("td").find('#allowedBtn').val();
    let remarks= $("#attend_remarks-"+update_id).val();
    //alert(remarks);
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-update-attend-status'; ?>',
        data: {update_id:update_id,buttonValue:buttonValue,remarks:remarks}
    }).done(function (data) {
        $("#attend_status-"+update_id).text('Allowed'); 
        //alert("The Application Form this "+update_id+' is approved');
    });     
});
$(".notallowedBtn").click(function() {

    let update_id = $(this).closest("td").find("#update_id").val();
    let buttonValue=$(this).closest("td").find('#notallowedBtn').val();
    let remarks= $("#attend_remarks-"+update_id).val();
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-update-attend-status'; ?>',
        data: {update_id:update_id,buttonValue:buttonValue,remarks:remarks}
    }).done(function (data) {
        $("#attend_status-"+update_id).text('Not Allowed'); 
        //alert("The Application Form this "+update_id+' is rejected');

    });   
});
    </script>