   

<?php
$result = $this->result;
                            $i = 1;
                            $pagination_tr = '';
                            if (count($result) != 0) {
                                foreach ($result as $results) {
                                    ?>
                                    <tr>
                                        <td><?php echo $i;
                            $i++;
                            ?> </td>						
                                        <td><?php echo $results['course_code']; ?></td>
                                        <td><?php echo ((int)$results['total_class']); ?></td>
                                        <td><?php echo (int)$results['p']; ?></td>
                                        <td><?php echo (int)$results['A']; ?></td>
                                        <td><?php echo (int)$results['percent']; ?> %</td>
                                    </tr> 
    <?php
    }
}
else{ ?>
    <tr>
        <td colspan="8">No Records</td>
    </tr>
<?php }
?>  
