<style>
    .link:link,
    .link:visited{
        position: relative;
        display: inline-block;
        padding:.2em 2em;
        border-radius:100px;
      /*  background-color:#faa2b1;*/
        -webkit-transition: all .2s;
        transition: all .2s;
    }
    
    
    .link::after{
        content: "";
        position:absolute;
        top:0px;
        left:0px;
      background-color:#faa2b1; 
        width:100%;
        height:100%;
        z-index:-1;
        border-radius:100px;
         -webkit-transition: all .2s;
        transition: all .2s;
    }
    
    
    
    .link:hover{
        box-shadow:0px 5px 6px #000;
    }
    
    .link:hover::after{
        transform:scale(2,3);
          
    }
    
      .link:active{
        box-shadow:0px 5px 1px #000;
    }
    
    dt{
        display:none;
    }
    </style>
    <style>
    @media print {
                    table td:nth-child(7)
                     {
                         display:none;
                     }
                     table th:nth-child(7)
                     {
                         display:none;
                     }
                      *{
                        visibility:hidden;
                     }
                     table,th,td 
                     {
                         visibility:visible;                    
                     } 
                     .title1
                     {
                        visibility:visible; 
                     }
                }
</style>
 
<div class="right_col">
<?php if ($this->type) { ?>
<div class="padding-md">
	<div class="row">
		<div class="col-md-12 " >
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">Notification Push</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >
					
					<div class="panel-body">
						  <div class="row">

							<div class="col-sm-3 employee_class">
                            <div class="form-group" >
                            <label  class="control-label" >Batch<span class="asterisk">*</span></label>
                            <?php echo $this->form->academic_year_id; ?>
                            </div>
							</div>
						
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                            <label class="control-label">Term<span class="asterisk">*</span></label>
                               
                                    <?php echo $this->form->term_id; ?>
                            
                            </div>
							</div>
                                                      		<div class="col-sm-3 employee_class">
                            <div class="form-group">
                            <label class="control-label">Course<span class="asterisk">*</span></label>
                            <?php echo $this->form->course_id; ?>
                            </div>
							</div>
							
							</div>
                                            <div class="row">
							<div class="col-sm-3">
							<div class="form-group">
							<input type="text" id="batch" class="form-control" style="background-color:#fdf59a;" readonly />
							</div>
							</div>
							</div>
                                            
                                            
                                                            <div class="panel panel-default">
	
					
					<div class="panel-body">
					
					<div class="row">
					<div class="col-sm-3"><h4><span style="color:#777;">Assignment Details</span></h4></div>
					</div>
					 <div class="row masterbox">
					 <div class="row">
					      <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Document Type<span class="asterisk">*</span></label>
                                <?php echo $this->form->document_type; ?>
                            </div>
							</div>
                                                <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Document Title<span class="asterisk">*</span></label>
                                <?php echo $this->form->document_title; ?>
                            </div>
							</div>
                                                <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Remarks<span class="asterisk">*</span></label>
                                <?php echo $this->form->remarks; ?>
                            </div>
							</div>
                                           
                                             
                                             		 <div class="col-sm-3">
							<div class="form-group">
                                                        <label class="control-label">Status<span class="asterisk"></span></label>
                                                           <?php echo $this->form->status; ?> 
							</div>
							</div>
                                         </div>
                                             <div class='row'>
                                               <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Due Date<span class="asterisk"></span></label>
                                <?php echo $this->form-> due_date; ?>
                            </div>
							</div>
                                             </div>
                                             <div class="row">
                                             	<div class="col-sm-3">
							<div class="form-group">
                                                        <label class="control-label">Date<span class="asterisk"></span></label>
							<input type="text" value='<?=date('d-m-Y')?>'  class="form-control" style="background-color:#fdf59a;" id='updated_date' name='updated_date' readonly />
							</div>
							</div>
                                            
                                             </div>
                                         </div>
                                            
                                            <div class="row">	
					<div class="col-sm-3"><h4><span style="color:#777;">File Upload</span></h4></div>
					</div>
					<div class="row masterbox">
							 <div class="row">
							 <div class="col-sm-3 employee_class">
							  <input name="file[]" id="file" type="file"   size="50"/>
                                                                <div class='form-control-static'>
                                                                    <span class='text-danger'>only .jpg, .png, .pdf, .docx, .doc, .ppt, .xls file can upload</span>
                                                                </div>
							 </div>
							 </div>
					</div>
                                            
                                            
                                            
                                        </div>
                                            
                                            
							
					<!--	 <?php /* if(count($this->item_result)>0){
							//		print_r($this->item_result);die;
							$i=0;
						   foreach($this->item_result as $val){ 
						$i++; */
					?>
					<div class="row" id="" style="">
					
							<div class="col-sm-3">
							<label>Fee Head Name<span class="asterisk">*</span></label>
							<input type="text"  label="feehead_name_<?php // echo $i;?>"  class="form-control feehead_name" name="Fee[feehead_name][]" placeholder="" value="<?php echo $val['feehead_name'];?>"/> 
							</div>				  
													
						<a href="#" class="removeclass btn btn-primary remove_class" style="padding:7px 15px;margin:24px 15px; ">-</a>
						</div>   
					<?php // } ?>
					 <div class="col-sm-3"></div>    
					<input type="button" value="+" id="AddButton" class="btn btn-primary adjust-size" style="padding:7px 15px;margin-left:9px;">
					
					<?php  // }  else {    ?>
					 
		<input type="hidden" name="count_val" id="count_val" value="1" class="count_val" />  
		<div class="row" style="">
	
		<div class="col-sm-3"><label> Fee Head Name <span class="asterisk">*</span></label> <input type="text"  label="feehead_name_0"  class="form-control" name="Fee[feehead_name][]" style="" placeholder="Name" value="" /> 
		</div>
            <input type="button" value="+" id="AddButton" class="btn btn-primary adjust-size" style="padding:7px 15px;margin:24px 15px;"> 
       	
		
	</div>
	<?php // } ?>
       <div id="fields">
         <div class="padding-top"></div>
        </div>   -->
					</div>
					<div>
						<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div style="float:left;">
										<button class="btn btn-primary submit">Update</button>
										</div>
										<div style="float:left;">
										<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>assignment/index/">Back</a>
										</div>
										<?php }		?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars">Notification Push</i>
				
		</h3>
	</div>
			
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>assignment/index/type/add">Add </a>
		</div>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                        <h2 class="title1">Notification Push</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix">
                    <div class="col-sm-0" style="float:right;">
                                   <!-- <a class="btn btn-primary" target="_blank" href="#<?php //echo $this->mainconfig['host']; ?>fee-structure/structure-pdf/id/<?php //echo $this->structure_id; ?>">Print</a>--><a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a></div>
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
				<thead>
					<tr>
						<th style="text-align:center;">S. No.</th>	
						<th style="text-align:center;">Document Title</th>
						<th style="text-align:center;">Files&nbsp;(Download Files)</th>
						<th style="text-align:center;">Remarks</th>
                                                <th style="text-align:center">Date</th>
                                                 <th style="text-align:center">Due Date</th>
                                                <th style="text-align:center">Actions</th>
					</tr>
				</thead>
				<tbody style="text-align:center;">
					<?php
                                         
						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {
						

					?>
							<tr>
								<td><?php echo $i;

									$i++; ?>
								</td>						
								
								
								<td><?php echo $results['document_title']; ?></td>
								
                                                                <td><a href='<?=$this->baseUrl($results['filename']);?>' class='link' download><?php echo $results['filename1']; ?></a></td>
                                                                <td><?php echo $results['remarks']; ?></td>
                                                                <td><?=$results['updated_date']; ?></td>
								<td><?=$results['due_date']; ?></td>
								<td><a href="<?php echo $this->mainconfig['host']; ?>assignment/index/type/edit/id/<?php echo $results['assignment_id']; ?>/aca/<?php echo $results['academic_year_id']; ?>/ter/<?php echo $results['term_id']; ?>" class="edit" title="Edit">View / Edit</a>&nbsp; 

							</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>	
 
	
        $('#due_date').attr('autocomplete','off');
        $(function () {
            $('#due_date').datetimepicker();
        });
        
        
        
	function ConfirmDelete()
	{
	var x = confirm("Are you sure you want to delete?");
	if(x)
		return true;
	else
		return false;
	}


 $("#academic_year_id").change(function () {
        var academic_id = $('#academic_year_id').val();
        if (academic_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms'; ?>',
                data: {academic_year_id: academic_id}
            }).done(function (data) {
                //alert(data);
                $('#term_id').empty('');
                $('#term_id').html(data);
            })
        } 
    });
    
    
    
    $("#term_id").change(function () {
        var term_id= $('#term_id').val();
        var academic_id = $('#academic_year_id').val();
    // alert(academic_id);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'].'attendance/ajax-get-course';?>',
                data: {academic_year_id: academic_id,term_id: term_id}
            }).done(function (data) {
                //alert(data);
                $('#course_id').empty('');
                $('#course_id').html(data);
            })
         
    });
    
     $("#course_id").change(function() {
        var term_id= $('#term_id').val();
        var academic_id = $('#academic_year_id').val();
        var course_id = $("#course_id").val();
     
      // alert(academic_id);
	        var id=$(this).attr("id");
			$.ajax({
              type: "POST",
               url:"<?php echo $this->mainconfig['host'].'attendance/ajax-get-date';?>",
              data: { batch_id:academic_id,term_id:term_id,course_id:course_id}
            }).done(function(data) {
				$('#date').empty('');
				$("#date").html(data);
			});
              
     });
    
    
     $("#date").change(function() {
        var term_id= $('#term_id').val();
        var academic_id = $('#academic_year_id').val();
        var course_id = $("#course_id").val();
        var date_val = $("#date").val();
	        var id=$(this).attr("id");
			$.ajax({
              type: "POST",
               url:"<?php echo $this->mainconfig['host'].'attendance/ajax-student-list-view';?>",
              data: { batch_id:academic_id,
                       term_id:term_id,course_id:course_id,date_val: date_val}
            }).done(function(data) {
				$('#item_details').empty('');
				$("#item_details").html(data);
			});
     });



$('body').on('change', '#academic_year_id', function() {		
var academic_id=$('#academic_year_id').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	 }
	 
 });
 
 
var academic_id=$('#academic_year_id option:selected').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	 }
	else{
$('#batch').hide();
}


 $('#dataTable').DataTable();

</script>