<table class="table table-striped table-bordered mb30 jambo_table bulk_action "
                            id="datatable-responsive">
                            <thead>
                                <tr>
                                    <th>S.  No.</th>
                                    <th>Student Name</th>
                                    <!---<th>Last Name</th>--->
                                    <th>Father Name</th>
                                    <th>Batch</th>
                                    <th>Core Course</th>
                                    <th>Generic Electives</th>
                                    <th>AECC</th>
                                    <th>UID</th>
                                    <th >REG NO.</th>
                                    <th>Exam Roll No.</th>
                                    <!--<th >Earned Credit</th> -->
                                    <th>Save & Edit</th>
                                    <th>Status</th>
                                    <th class="no_print">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                        
                                <?php
                                $earned_credit = new Application_Model_TotalEarnedCredits();
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {

                                    foreach ($this->paginator as $results) {
                                       
                                        ?>
                                        <tr>
                                            <td><?php
                                                echo $i;

                                                $i++;
                                                ?>
                                            </td>                       
                                            <td><?php echo $results['stu_fname'].' '. $results['stu_lname']; ?></td>
                                            <!--<td><?php echo $results['stu_lname']; ?></td>-->
                                            <td><?php echo $results['father_fname'].' '.$results['father_lname']; ?></td>
                                            <td><?php echo $results['academic_year']; ?></td>
                                            <td><?php echo $results['dept_name']; ?></td>
                                            <td ><?php echo $results['ge_name']; ?></td>
                                            <td><?php echo $results['aecc_name']; ?></td>
                                            

                                            <td><?php echo $results['stu_id']; ?></td>
                                            <td style="vertical-align:middle;" class="form-group-sm">
                                                <?php if ($results['reg_no'] != '0000' && !empty($results['reg_no'])) { ?>
                                                    <label class='changebox ' style='font-weight:normal;' ><?php echo $results['reg_no']; ?></label>
                                                <?php } else { ?>
                                                    <input type='text' class='changebox form-control' size="12" name='reg_no' data-reg = '<?php echo $results['student_id']; ?>' value="<?php echo $results['reg_no']; ?>"/>
                                                <?php } ?>
                                            </td>
                                            <td style="vertical-align:middle;" class="form-group-sm"><?php // echo $results['reg_no'];  ?>
                                                <?php if ($results['exam_roll'] != '0000' &&  !empty($results['exam_roll']) ) { ?>
                                                    <label class='changebox' style='font-weight:normal;' ><?php echo $results['exam_roll']; ?></label>
                                                <?php } else { ?>
                                                    <input type='text' class='changebox form-control' size="12" name='exam_roll' data-exam = '<?php echo $results['student_id']; ?>' value="<?php echo $results['exam_roll']; ?>"/>
                                                <?php } ?>
                                            </td>
                                             <!---<td style="vertical-align:middle;" class="form-group-sm"><?php // echo $results['earned_credit'];  ?>
                                                 <table>
                                                     <tbody><tr>
                                                         <td >
                                                <?php if ($results['earned_credit'] > 0) { ?>
                                                    <label class='changebox' style='font-weight:normal;' ><?php echo $results['earned_credit']; ?></label>
                                                <?php } else { ?>
                                                    <input type='text' class='changebox form-control' size="2" name='earned_credit' data-credit = '<?php echo $results['student_id']; ?>' value="<?php echo $results['earned_credit']; ?>"/>
                                                <?php } $credits_details = $earned_credit->getRecordAcademic($results['academic_id']); ?> 
                                                         </td>
                                                         <td>
                                                             /<span><?=$credits_details['credit_number']?$credits_details['credit_number']:0;?></span>
                                                         </td>
                                                         </tr></tbody></table>
                                            </td>-->
                                            <td style="text-align:center; vertical-align: middle;"><label for='<?=$results['student_id'];?>'  class="checkbox"></label><input type="checkbox" <?php
                                                if (($results['exam_roll'] == '0000' && $results['reg_no'] == '0000') || (empty($results['exam_roll']) && empty($results['reg_no']))) {
                                                    
                                                } else {
                                                    echo 'checked';
                                                }
                                                ?> data-id ="<?= $results['student_id']; ?>" id ='<?= $results['student_id']; ?>' /></td>


                                            <td class="text-center" style="vertical-align: middle;" >
                                               <?php echo($results['stu_status'] == 1 
                                                    ? "<b style='color:green;'>Active</b>" 
                                                    : ($results['stu_status'] == 2 
                                                        ? "<b>Discontinue</b>" 
                                                        : ($results['stu_status'] == 3 
                                                            ? "<b style='color:red;'>T.C</b>." 
                                                            : "<b>Alumni</b>"))); 
                                                ?>

                                            </td>

                                            <td class="text-center" style="vertical-align: middle;">
                                             <a href="<?php echo $this->mainconfig['host']; ?>student/index/type/edit/id/<?php echo $results['student_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>  </td>
                                        </tr>            
                                        <?php
                                    }
                                   
                                }
                                ?>

                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="11">Save All</td>
                                    <td ><button type='buttom' class='btn btn-primary' type = "button" >Save All</button></td> 
                                    <td></td>
                                    <td></td>
                                </tr>
                            </tfoot>
                        </table>
<script> 
 setDatatables();

$('div[class="dt-buttons btn-group"]').appendTo('#moved-buttons');
$(document).ready(function(){
    var cells = [];
    var rows = $("#datatable-responsive").dataTable().fnGetNodes();
    for(var i=0;i<rows.length;i++){
        if($(rows[i]).find("input[type='checkbox']").prop('checked')){
            if($(rows[i]).find("input[type='checkbox']").prev('label').find('i').index()== -1)
            $(rows[i]).find("input[type='checkbox']").prev('label').append('<i class="glyphicon glyphicon-ok"></i>');
        }
    }
});

    //Method is used to get Total records!
     $(document).ready(function () {

        var text = $('#datatable-responsive_info').text();

        res = text.split("of");

        if (res.length > 0) {

            if (res[1]) {
                act_text = res[1].split("entries");
            $("<div id='custom_data_records'><label>Total Records : <span>" + act_text[0] + "</span></label></div>").insertAfter('#datatable-responsive_length');
                $('input[type="search"]').keyup(function () {
                    $('#custom_data_records').remove();
                    var text = $('#datatable-responsive_info').text();
                    res = text.split("of");
                    act_text = res[1].split("entries");
                    $("<div id='custom_data_records'><label>Total Records : <span>" + act_text[0] + "</span></label></div>").insertAfter('#datatable-responsive_length');
                });
            }
        }
    });
    
    
    $('button').click(function(){

var reg_no = [];
var reg_id = []
var roll_no = [];
var roll_id = [];
var credit_no = [];
var credit_id = [];

$('input[name="reg_no"]').each(function(e){
   reg_no.push($(this).val());
   reg_id.push($(this).data('reg'));
    
});

$('input[name="exam_roll"]').each(function(e){
    roll_no.push($(this).val());
    roll_id.push($(this).data('exam'));
    
});
$('input[name="earned_credit"]').each(function(e){
    credit_no.push($(this).val());
    credit_id.push($(this).data('credit'));
    
});
if(reg_no.length >0 || roll_no > 0 ){
    $('.load-box').show();
   $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-bulk-saved-result'; ?>',
                data: {reg_no: reg_no, reg_id: reg_id, roll_no: roll_no,roll_id:roll_id}
            }).done(function (data) {
               $('head').append("<meta http-equiv='refresh' content = '0'>");
            });
            }

});


    
    </script>