<?php if(!empty($this->paginator)){ 
    
   //echo '<pre>'; print_r($this->paginator);exit;
?>
   

                                                 
                                                 
  
<style>
@media print {
  
  button,fieldset{
      position:fixed !important;
      display:none !important;
  }
   p{
        font-size: 18px;
    }
  
    #applicationFormPreview{
        padding-left: 2em;
        padding-right:2em;
        position:absolute !important;
        top:0px !important;
        width:100%;
    }
  
  
  .pagebreak {
       clear: both;
      page-break-after: always; }
}
 @page 
    {
        position:absolute !important;
        size:  auto;   /* auto is the initial value */
        margin: 1mm;
        margin-top:0; 
       /* this affects the margin in the printer settings */
    }   
    
</style>
<div class="right_col">
<div class="appForm" id="applicationFormPreview">
<div class="" id="applicationFormPreview">
       <div style="float:right;padding-bottom: 3em;" id="divbutton">
            <button type="button" id="printAppForm2"  class="btn btn-primary" onclick="window.print()"></button>
        </div>
 
        <div class="row" id="section-to-print">
        
                
            <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action " >

                <thead>
                    <tr>
                       
                    </tr>
                </thead>
                <tbody>
                   
                    <tr>
                        <td class="col-sm-2 col-sm-offset-1">
                            <div class="form-group">
                                 <img src="<?php echo $this->mainconfig['publicpath']; ?>img/logo.png" width="120" height="130">          
                            </div>
                        </td>
                       

                        <td class="col-sm-10" style="text-align: center;">
                            <div class = 'sub' style="text-align: center;">
                                <h4> PATNA WOMEN'S COLLEGE</h4>
                                <h5>AUTONOMOUS</p></h5>
                                <h4>PATNA UNIVERSITY</h4>
                                <h5>3rd Cycle NAAC Accredited at A Grade with CGPA 3.58/4</h5>
                                <h5>College with Potential for Excellence(CPE) status accorded by UGC</h5>
                                <h5> BAILEY ROAD,PATNA - 800 001, BIHAR</h5>
                                
                        </div>
                        </td>
                    </tr>
                  
                </tbody>
            </table>
            <div class="col-xs-12">
                <h2  style="text-align: center"> <u>Character Certificate </u> </h2> 
            <p>
                Certified that <b><?php echo $this->paginator['stu_fname'];?></b> daughter of  <b><?php echo $this->paginator['father_fname'];?> / <?php echo $this->paginator['mother_fname'];?></b> was a student of               Patna Women's College, Patna, from <b> <?php echo !empty($this->paginator['session_for_char']) ? $this->paginator['session_for_char']:$this->paginator['session'];?> </b> in <b><?php echo $this->paginator['batch']; if($this->paginator['degree']==1){ echo '(Honours).';}else{ echo '.';}?></b> </p>

            <p>During her stay  here her conduct has been good and there is nothing against her character, as far as I know.</p>

            <p>I wish her well wherever she goes. </p>
           
            </div>
              <div class="col-sm-6">
               Date <?php echo date('d/m/Y') ?>
               
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;	&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            <img src="<?php echo $this->mainconfig['publicpath']; ?>images/principal.jpg" alt="..."  height ="40" width="200"><br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;	&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;	&emsp;&emsp;&emsp;<b>(Dr. Sister M. Rashmi A.C.) </b> <br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;	&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<b>Principal</b> <br>
          
          

            </div>
            
        </div>
</div>
</div>
</div>
<?php }else{ ?>   

<div class="right_col">
    <label id="alert_msg" style="color:red; ">
       Result not found.....!Oop's:) 
    </label> 
    
</div>
<?php  } ?>                                         