<div class="col-md-12">
<?php //echo '<pre>'; print_r($this->paginator);exit; ?>
    <div class="table-responsive" id="studentData"> 
        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  style="height:100%;">
            <thead>
                <tr>
                    <th>Course Code</th>
                    <th> cc Name </th>
                    <th>Credit Value</th>
                    <th> Countable(YES/NO)</th>
                    <th>Course Name </th>

                </tr>
            </thead>
           
            <tbody>
                <?php foreach ($this->paginator as $key => $value) { ?>
                   
                <tr>					
                    <td><?php echo $value['course_code']; ?></td>
                    <input type="hidden" name="course_id[]" value="<?= $value['course_id'] ?>" />
                    <input type="hidden" name="course_code[]" value="<?= $value['course_code'] ?>" />
                    <input type="hidden" name="cc_id[]" value="<?= $value['cc_id'] ?>" />
                    <input type="hidden" name="credit_id[]" value="<?= $value['credit_id'] ?>" />
                    <input type="hidden" name="re_credit[]" value="<?= $value['re_credit'] ?>" />
                    <input type="hidden" name="ge_id[]" value="<?= $value['ge_id'] ?>" />
                    <input type="hidden" name="count_id[]" value="<?= $value['count_id'] ?>" />
                    <input type="hidden" name="degree_id[]" value="<?= $value['degree_id'] ?>" />
                    <input type="hidden" name="cmn_terms[]" value="<?= $value['cmn_terms'] ?>" />
                    <td><?php echo $value['cc_name']; ?></td>
                    <td><?php echo $value['credit_value']; ?></td>
                    <td><?php if($value['count_id'] == 0)echo 'YES';else echo 'NO'; ?></td>
                    <td><?php echo $value['course_name']; ?></td>
                <tr>
                <?php }?>

            </tbody>
            
        </table>
    </div>
</div>
