<div class="right_col">
<?php if ($this->type) { ?>
<div class="padding-md">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">Earned Academics Credit</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
						<div class="row">
															
							
							<div class="col-sm-3 employee_class">
                                <div class="form-group">
                                <label class="control-label"> Batch<span class="asterisk">*</span></label>
                                <?php echo $this->form->academic_id; ?>
                                </div>
							</div>
<?php echo $this->form->csrftoken; ?>                                                    
							<div class="col-sm-3 employee_class">
                                <div class="form-group">
                                <label class="control-label">Credit's<span class="asterisk">*</span></label>
                                <?php echo $this->form->credit_number; ?>
                                </div>
							</div>  									
																
							<div class="col-sm-3 employee_class">
                                <div class="form-group">
                                <label class="control-label"> status<span class="asterisk">*</span></label>
                                <?php echo $this->form->status; ?>
                                </div>
							</div>  									
														
							
							
						</div>
					</div>
						<div>
						<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert <?php echo $_SESSION['message_class']; ?> ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars"> Earned Academics Credit </i>
				
		</h3>
	</div>
			
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>master/earned-credit-migration/type/add">Bulk Add </a>
		</div>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                    <h2>Earned Academics Credit</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
				<thead>
					<tr>
						<th>S.No.</th>												
						<th>Batch</th>
                                                <th>Degree</th>
                                                <th>Department</th>
						<th>Total credit</th>
						
                        <th class="no_print">Action</th>
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {
						//print_r($results);die;

					?>
							<tr>
								<td><?php echo $i;

									$i++; ?>
								</td>						
								
								
								<td><?php echo $results['short_code']; ?></td>
                                                                <td><?php echo $results['degree']; ?></td>
                                                                <td><?php echo $results['department']; ?></td>
								<td><?php echo $results['credit_number']; ?></td>
								
								<td><a href="<?php echo $this->mainconfig['host']; ?>master/total-earned-credits/type/edit/id/<?php echo $results['id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>

							</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>	
 
	
	function ConfirmDelete()
	{
	var x = confirm("Are you sure you want to delete?");
	if(x)
		return true;
	else
		return false;
	}
    $('body').on('change', '#stream', function () {
        var stream = $('#stream').val();
        if (stream) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-academic-on-stream'; ?>',
                data: {stream: stream}
            }).done(function (data) {
                
                $('#academic_id').empty('');
                $('#academic_id').html(data);
                $('#academic_id').trigger("chosen:updated");
            });
        }
    });

</script>
