<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
			
				<thead>
					<tr>
					    <th>Student ID </th>
						<th>Student Name</th>
						<th> </th>
					</tr>
				</thead>
				<tbody>
				<tbody>
					<?php $result=$this->corecourseresult;
					      foreach($result as $results) {
					?>
					<tr>
					<td><?php echo $results['stu_id'];?></td>
					<td><?php echo $results['stu_fname'].'&nbsp;&nbsp;'.$results['stu_lname'];?></td> 
					<td><a class="btn btn-primary" href="<?php echo $this->mainconfig['host'];?>report/studentreport-Pdf/id/<?php echo $results['student_id'] ?>">Print </a>
					<a class="btn btn-primary" href="<?php echo $this->mainconfig['host'];?>report/studentgradesheetreport-Pdf/id/<?php echo $results['student_id']; ?>/acd_id/<?php echo $results['academic_id']; ?>/year/<?php echo $this->year_id; ?>">Print Grade Sheet </a></td>
					</tr>
					<?php } ?>
										
				</tbody>
			</table>
			 <?php //echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
