<style>
   
    #refresh{
        cursor:pointer;
    }
    
    
</style>
<div class="right_col bdoypayment">
    <div class="load-box" style="z-index:998">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
</div>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                        <h3 class="page-title txt-color-blueDark">
                            <i class="fa fa-bars">Semester Fee Details</i>

                        </h3>
                    </div>
                </div>
                <div class="col-md-12">
                   <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <label class="control-label" style="float:left;">Department <span class="asterisk"></span></label>
                           <?php echo $this->form->department; ?>
                        </div>
                   </div>
                   <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <label class="control-label" style="float:left;">Semester <span class="asterisk"></span></label>
                           <?php echo $this->form->cmn_terms; ?>
                        </div>
                   </div>
                       
                   
                   <div class="col-md-12">
                   
                       
                       <div class="col-sm-3 col-sm-offset-3 employee_class">
                        <div class="form-group">
                          
                        </div>
                   </div>
                       
                    <div class="col-sm-3 employee_class">
                        
                        
                   </div>
                        <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <button type="button" id="getRecords" class="btn btn-primary pull-right" style="margin-top:1.5em;z-index:999;" value="0" >Get Records</button>
                        </div>
                   </div>
                   </div>
                   
                <div style="float:left;padding-left:10%;">
                </div>
                </div>
                 <div class="col-md-12">
                   <div class="table-responsive" id="ajaxData"> 
                       <table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" style="height:100%">
                            <thead>
                                <tr>

                                    <th class="no-sort">S.No.</th>

                                    <th>Student Name</th>


                                    <th>UID</th>

                                    <th>Transaction Id</th>
                                    <th>Status</th>
                                    <th>Pay Mode</th>
                                    <th>Amount</th>
                                    <th>Batch</th>
                                    <th>Date</th>
                                </tr>
                            </thead>
                            <tbody>
                               
                                                <tr>
                                                    <td colspan="9">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                               

                            </tbody>
                        </table>

                        
                       
                    </div>
                </div>
                
            </div>    
           

        </div>
       
        </div>
 


<script>
     $('.datepicker').datepicker();
  
//Author: Kedar: 22 Oct 2020 : To get record by filter crieteria

$('body').on('click', '#getRecords', function() {
    
    let department = $('#department').val();
    let sem= $('#cmn_terms').val();
    $('.load-box').css('display','block');
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-fees-installment-record'; ?>',
        data: {department:department,sem:sem}
    }).done(function (data) {
        $('#ajajxData').empty('');
        $('#ajaxData').html(data);
        $('.load-box').css('display','none');

    });
});

    

</script>

