<div class="padding-md right_col">
     <div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
 </div>   
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">Attendance Report</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
							<div class="row">
															
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Batch<span class="asterisk">*</span></label>
                                <?php echo $this->form->academic_year_id; ?>
                            </div>
							</div> 
                                                            	<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Month(From)<span class="asterisk">*</span></label>
                               <input type ="text" data-toggle="month-picker" name='from-month' id='from-month' class='form-control' />
                            </div>
                                                            </div>
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Month(To)<span class="asterisk">*</span></label>
                                <input type ="text" data-toggle="month-picker" name='to-month' id='to-month' class='form-control' />
                            </div>
							</div> 
							
							<div class="col-sm-3 employee_class">
                                <div class="form-group">
                                  <label class="control-label">Year<span class="asterisk">*</span></label>
                                    <?php echo $this->form->year_id; ?>
                                </div>
                            </div>
							
							<div class="col-sm-3 employee_class">
                                <div class="form-group">
                                  <label class="control-label">term_id<span class="asterisk">*</span></label>
                                   <select name="term_id" id="term_id" class="form-control">
                                      <option>Select</option>
                                  </select>
                                </div>
                            </div>
                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                  <label class="control-label">Degree<span class="asterisk">*</span></label>
                                    <?php echo $this->form->degree_id; ?>
                                </div>
                            </div>
                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                  <label class="control-label">Course_category<span class="asterisk">*</span></label>
                                    <?php echo $this->form->cc_id; ?>
                                </div>
                            </div>
                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                  <label class="control-label">Course Group<span class="asterisk">*</span></label>
                                    <?php echo $this->form->ge_id; ?>
                                </div>
                            </div>
                           <div id="course_ids"></div>
                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                  <label class="control-label">Department<span class="asterisk">*</span></label>
                                    <?php echo $this->form->department; ?>
                                </div>
                            </div>
						
							</div>
							<div class="row">
						<div class="col-sm-3">
							<div class="form-group">
                              <label class="control-label">&nbsp;</label>
							<input type="text" id="batch" class="form-control" style="background-color:#fdf59a;"  readonly />
							</div>
						</div>
						</div>
						  <div class="row" id="grade-data">
                                
                            </div>
                            <div id="getstudent" class="col-sm-12">
							</div>
							
						
				</form>
                          
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	


<script>
 jQuery(document).ready(function() {
		$('#batch').hide();
        $('body').on('change', '#term_id, #stu_id', function() {
			
            getstudentDetails();
        });
	});
 
	
    $('#department,#course_ids').change(function(){
        var term= $('#term_id').val();
        var course_id = $('#course_id').val();
        //alert(course_id);
        var department = $('#department').val();
         $('.load-box').css('display','block');
        $url = '<?php echo $this->mainconfig['host']; ?>report/get-attendance-report';
        $.post($url,
                {
                    'department': $('#department').val(),
                    'course_id': $('#course_id').val(),
                    'year_id': $('#year_id').val(),
                    'monthFrom':$('#from-month').val(),
                    'monthTo':$('#to-month').val(),
                    'term_id':term,
                    
                    'academic_id':$('#academic_year_id').val()
        })
                .done(function(data) {
                    $('#getstudent').html(data);
            
                });
                
                
                
                  $.ajax({ 
			type: "POST",
			url:"<?php echo $this->mainconfig['host'].'report/attendancereport-view';?>",
			data: { acd_id : $('#academic_year_id').val(),year:$('#year_id').val(),term:term,department:department,course_id:course_id,from:$('#from-month').val(),to:$('#to-month').val()}
		}).done( function( data ) { 
	     //alert(data);	
			$("#grade-data").empty();
                             $('.load-box').hide();
			$("#grade-data").html(data);
                    
		});

    });

 $("#academic_year_id").change(function() {
	 var academic_year_id=$("#academic_year_id").val();
  if(academic_year_id !=''){
	 $.ajax({ 
			type: "POST",
			url:"<?php echo $this->mainconfig['host'].'report/ajax-get-student-names';?>",
			data: { academic_year_id : academic_year_id}
		}).done( function( data ) { 
	     //alert(data);	
			$("#stu_id").html(data);
		});
	}
});


 $('body').on('change', '#academic_year_id', function() {		
var academic_id=$('#academic_year_id').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	 }	 
 });
 
   $('body').on('change', '#year_id', function() {		
var academic_id=$('#academic_year_id').val();
var year_id = $('#year_id').val();
   if(academic_id && year_id){
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-term-year-batch';?>',
			data: {batch_id:academic_id,year_id: year_id}
		}).done(function( data ) {
			
				$('#term_id').html(data);	
	  });
	 } 
 });
 
 //For filteration Date:14 -Feb 2020
 
 $('body').on('change', '#cc_id', function () {
    var cc_id = $('#cc_id').val();
    var term_id = $('#cmn_terms').val();
    if (cc_id) {
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-group'; ?>',
            data: {cc_id: cc_id, term_id: term_id}
        }).done(function (data) {
            $('#ge_id').empty('');
            $('#ge_id').html(data);
            $('#ge_id').trigger("chosen:updated");
        });
    }
});

$(document).on('change','#ge_id',function() { 
    var department_id = '';
    var cc_dept ='';
    var Ct_id= $('#cc_id').val();
    var employee_id = '';
    var department;
    
    var course_group= $('#ge_id').val();
    //alert(course_group);
    
    var term_id = $('#term_id').val();
    alert(term_id);
    $('.load-box').css('display','block');
    if(ge_id){
       $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-base-of-course'; ?>',
            data: {Ct_id: Ct_id, employee_id: employee_id, department_id: department_id, term_id: term_id, ge_id: course_group, cc_dept: department}
        }).done(function (data) {
            $('#course_ids').empty('');
            $('#course_ids').html(data);
            $(".chosen-select").chosen(); 
            $('#grade_data').empty();
            $('.load-box').css('display','none');
        });
    }
});
    
    $('body').on('change', '#degree_id', function () {
 $('.load-box').css('display','block');
        var degree_id = $('#degree_id').val();
        if (degree_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-course-cat'; ?>',
                data: {degree_id: degree_id}
            }).done(function (data) {
                    $('#cc_id').empty();
                    $('#cc_id').html(data);
                    
                    $.ajax({
                   type: "POST",
                   url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Dept'; ?>',
                   data: {degree_id: degree_id}
               }).done(function (data) {
                   $('#department').empty('');
                   $('#department').html(data);
                    $('.load-box').css('display','none');
               });
            
                
            });
        }

    });
    
</script>