
        <table class="table table-striped table-bordered mb30 jambo_table bulk_action "
               id="dataTable" border ='1' width="100%">
                    <thead><tr  id="header">
                            <th colspan="3" class="text-center course_code"></th>     
                            <th colspan="3" class="text-center">PATNA WOMEN'S COLLEGE, AUTONOMOUS, PATNA UNIVERSITY</th>     
                            <th colspan="3" class="text-center">Examination Date___________</th>     
                </tr>
            <tr >
                <th>S.No.</th>
                <th>Form Id</th>
                <th style="width: 15em">Student Name</th>
                <th>Exam Roll No.</th>
                <th>Registration No</th>
                <th>Copy Number</th>
                <th>Student Signature</th>
                <th>Invigilator Signature</th>
<!--                <th style='display:none'>Photo</th>-->
                <th  style="width: 50px;">Photo</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $i = 1;

            if (count($this->paginator) != 0) {

                foreach ($this->paginator as $results) {
                   //echo "<pre>";print_r($results);die;
                    ?>
                    <tr>
                        <td><?php echo $i;

                    $i++;
                    ?>
                        </td>						

                        <td><?php echo $results['stu_id']; ?></td>
                        <td><?php echo $results['stu_fname']; ?></td>
                        <td><?php echo $results['exam_roll']; ?></td>
                        <td><?php echo $results['reg_no']; ?></td>
                        <td ></td>
                        <td></td>
                        <td></td>

                        <td ><img class="img img-rounded" data-base64 ="<?=$src;?>"  src="<?php echo $this->mainconfig['host'] . $results['filename']; ?>" width="100px" height="70px" alt="img"></td>

                    </tr>            

                <?php
                } 
            }
            ?>

        </tbody>
</table>

<script>

setDatatables();

</script>
