<style>
.modal-dialog {
    width: 690px;
    margin: 30px auto;
}
</style>
<?php
 //echo '<pre>'; print_r($this->paginator); exit;
?>
<div class="right_col">
   <div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>

    <?php if ($this->type == 'edit') { ?>
    <div class="">
        <div class="load-box">
                    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
                </div>
        <div class="">
            <div class="row">
               
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Pass-Fail Semester Report</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>
                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">

                   
                </div>
                <?php
                //  }
                ?>
            </div>                      
       
            <div class="clearfix"></div>
        </div>
       
            <div class="x_panel">
               
                <div class="x_title">
                    <b> <u><?= $this->department['department_type']; ?></u> Core Course Report</b>
                   
                   
                    <a class="btn btn-primary pull-right" style="margin-top: 25px;" onClick="window.print();return false;"  >Print </a>
                    <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>/report/pass-fail-report">Back </a>
                   
                    <div class="clearfix"></div>
                </div>

            <div class="x_content">
                
                <div class="padding-md clearfix">
                    <div class="table-responsive" id="studentData">
                         <table class="table right-column table-striped table-bordered mb30 jambo_table bulk_action testTable" id="" style="height:100%">
                        <thead>
                            <tr>
                                <th>S.No.</th>
                                <th>Core Course Name</th>
                                <th>Pass Student</th>
                                <th>Failed Student</th>  
                                <th>Total Student</th>  
                               
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $i = 1;
                            $pagination_tr = '';
                            if (count($this->paginator) != 0) {
                                $passFail_model = new Application_Model_GradeAllocation();
                                foreach ($this->paginator as $key=> $results) {
                                        //echo '<pre>';print_r($results);exit;
                                        $failCount=$passFail_model->getFailStudents($results['term_id'],$results['academic_year_id']);
                                        $passCount=$passFail_model->getPassStudents($results['term_id'],$results['academic_year_id']);
                                        
                                       
                                   
                                    //echo '<pre>'; print_r($passCount);
                                    //$result[$key]['Totalapplied']=$results['applied'];
                                   
                                    $allDepartmentIds[$key]=$results['id'];
                                    $allAcademicIds[$key]=$results['academic_year_id'];
                                       
                                    ?>
                                    <tr>
                                        <td><?php echo $i;
                                        $i++;
                                    ?>
                                        </td>

                                        <td><?php echo $results['department']; ?></td>
                                        <td>
                                            <?= !empty($passCount)?count($passCount):'0';?>
                                           
                                       
                                        </td>
                                        <td>
                                            <?= !empty($failCount)?count($failCount):'0' ?>
                                        </td>
                                        <td>
                                            <?= count($failCount)+ count($passCount); ?>
                                        </td>
                                        
                                        
                                        <td id="hindi"> </td>
                                   
                                       
                                    </tr>            
                                   
                                <?php
                                }
                                  $deptIds= implode(",",$allDepartmentIds);
                                  $academicIds= implode(",",$allAcademicIds);
                                    // echo '<pre>';print_r($academicIds);
                               
                                ?>
                        <tfoot>
                           
                        </tfoot>            
                       
                               <?php
                                $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                            }
                            ?>

                        </tbody>
                       
                    </table>
                       
                        <?php echo $pagination_tr; ?>
                     </div>
                   
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
                <div class="getablea">
                           
                        </div>
            </div>
         
        </div>
    
<?php } else { ?>

   <?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">
               
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Pass-Fail Semester Report</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>
               
                <?php
                //  }
                ?>
            </div>

            <div class="x_panel">
               
                <div class="x_title">
                    
                       <div class="col-sm-3 employee_class">
                            <div class="form-group">
                                <label class="control-label">Academic Year<span class="asterisk">*</span></label>
                                <?php echo $this->form->academic_year; ?>
                            </div>
                        </div>
                       <div class="col-sm-3 employee_class">
                            <div class="form-group">
                                <label class="control-label">Session<span class="asterisk">*</span></label>
                                <?php echo $this->form->session; ?>
                            </div>
                        </div>
                       <div class="col-sm-3 employee_class">
                            <div class="form-group">
                                <label class="control-label">Semester<span class="asterisk">*</span></label>
                                <?php echo $this->form->cmn_terms; ?>
                            </div>
                        </div>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                   
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="ajaxData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                                 <caption> <b> <u> Under Graduate Department Wise Report</u></b> </caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th> 
                                    <th class="no_print">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    foreach ($this->paginator as $results) {
                                        //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                           
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>report/pass-fail-report/type/edit/id/<?php echo $results['id']; ?>"class="edit" title="Edit" target="_blank" ><span class="fa fa-edit fa-lg"></span></a></td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         
                
                <div class="x_panel">
               
              

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                            <caption> <b> <u>Post Graduate Department Wise Report</u></b> </caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th class="no_print">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->pgData) != 0) {
                                    foreach ($this->pgData as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                             <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>report/pass-fail-report/type/edit/id/<?php echo $results['id']; ?>"class="edit" title="Edit" target="_blank" ><span class="fa fa-edit fa-lg"></span></a></td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->
<?php } ?>
</div>
<script>
    //To filter Session
    $('body').on('change', '#academic_year', function () {
        var year_id = $('#academic_year').val();
        if (year_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
     //Get Batch By Session
    $('body').on('change', '#session', function () {
        var year_id = $('#session').val();
        if (year_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch'; ?>',
                data: {session: year_id}
            }).done(function (data) {
                $('#academic_id').empty('');
                $('#academic_id').html(data);
                $('#academic_id').trigger("chosen:updated");
            });
        }
    });
    //End   
    
//Added By Kedar : 08 Oct 2020
$('body').on('change', '#cmn_terms', function() {
    let term= $('#cmn_terms').val();
    let session=$('#session').val();
    if(term){
        $('.load-box').css('display','block');
        $.ajax({ 
                type: "POST",
                url:'<?php echo $this->mainconfig['host'].'report/ajax-get-stream';?>',
                data: {term:term,session:session}
            }).done(function( data ) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
                $('.load-box').css('display','none');
        });
    }
});
//End : 08 Oct 2020
</script>