<style>
    .multistepformArea{
    padding-top: 1px;
    background-color: white;
	width: 60%;
    min-width: 300px;
	margin: 50px auto;
	position: relative;
}
/*form styles*/
.regForm {
    width: 90%;
    min-width: 300px;
	margin: 50px auto;
	position: relative;
}
#formValidate1 fieldset {
	background: white;
	border: 0 none;
	border-radius: 3px;
	box-shadow: 0 0 1px 1px rgba(0, 0, 0, 0.1);
	box-sizing: border-box;
	position: relative;
}
.table-bordered td, th {
    padding: 8px;
}
</style>

<script type="text/javascript" src="wz_jsgraphics.js"></script>

<div class="instruction">
    <div class="multistepformArea">
        <form class="regForm" id="formValidate1" action="" method="post" data-validate="parsley" >

            <div class="row">
                <div class="col-sm-12">
                     

                    <p>Dear Applicant,</p>
                    
                    <p> Please read the following notice and instructions and tick on box at the bottom of this page to indicate your agreement to follow the same and to go to the next stage. </p>
                    <p dir="ltr" style="text-align:center">
    ADMISSION NOTICE - 2020
</p>
<object data="<?php echo  $this->mainconfig['publicpath']?>/pdfUpload/Entrance-Exam-Notice-2020.pdf" type="application/pdf" width="100%" height="1000px">
  <p>Your web browser doesn't have a PDF plugin.
  Instead you can <a href="<?php echo  $this->mainconfig['publicpath']?>/pdfUpload/Entrance-Exam-Notice-2020.pdf">click here to
  download the PDF file.</a></p>
</object>
<!--<embed src="<?php echo  $this->mainconfig['publicpath']?>/pdfUpload/Entrance-Exam-Notice-2020.pdf" width="100%" height="1000px"/>-->
<br/>




<div class="col-sm-12" style="margin-top:15px;">
 <div class="col-sm-12 employee_class">
      <div class="form-group">
        <h4 style="color:#d71212;">   
        <input type='Checkbox' name='instruction' id="instruction" class='instruction custom-control-label' value='EVS' style="width:25px; height:25px" />
        I have read the above instructions and agree to follow them.</h4>
  
                        </div>
                        <div class="col-sm-6 col-sm-offset-5 employee_class">
                            <div class="form-group">
                              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                               <a href="<?=  $this->baseUrl("entrance-exam-form/registeration"); ?>"> <button type="button" id="continue" class="btn btn-primary">Continue</button></a>
                            </div>
                        </div>
                     

                    </fieldset> 
                    &nbsp;<br>

                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $('#continue').hide();
    $('#instruction').click(function(){
        if (this.checked) {
            $('#continue').show();
        }else{
            $('#continue').hide();
        }
    });
</script>