
<style type="text/css">

    .bold-checkbox{
        position: absolute; top: 12px; font-weight:bold;
    }
     .modal-header .close {
    margin-top: -2px;
    color: white;
    }
.modal-header {
    border-bottom: 0px solid #666;
}
.modal-body,.modal-header{
    background-color: #666;

}
.register_form{
    padding-top: 20px;
    text-align: center;
}
.form_header{
    color: black;
    background-color: antiquewhite;;
    border-color: #2e6da4;
    display: inline-block;
    margin-bottom: 20px;
    font-size: 20px;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
    font-weight: 400;
}

.register_btn{
    color: #fff;
    background-color: #932e90;
    border-color: #2e6da4;
    display: inline-block;
    margin-bottom: 0;
    font-size: 14px;
    font-weight: 400;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    padding: 6px 55px;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
}

* {
  box-sizing: border-box;
}
.header-text{
    background-color: #932e90;
    min-width: 200px;
    min-height: 30px;
    margin-bottom: 4em;
}


.regForm {
  background-color: #ffffff;
  margin: 100px auto;
  font-family: Raleway;
  padding: 40px;
  width: 50%;
  min-width: 250px;
}

    .load-box{
        display:none;
        position:absolute;
        width:100%;
        height:100%;
        background:rgba(255,255,255,.4);
        z-index: 999;
    }
    
    .load-box>img{
        position:absolute;
        top:60%;
        left:50%;
        width:40em;
        transform: translate(-50%,-50%);
        
        
    }
    
    .mob_info{
        position:absolute;
    }
    .input-container {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  width: 100%;
  margin-bottom: 15px;
}
.icon {
    border: 1px solid #ccc;
    border-radius: 4px;
  background: white;
}
</style>
<link href="<?php echo $this->mainconfig['publicpath']; ?>css/custom.css" rel="stylesheet">


<form class="regForm" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

    <div class="row">
        <div class="col-sm-12  form_header"><label>Registration</label>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 employee_class">
            <div class="form-group disabled" >
                <label style="float:left;"><b>Applicant Name:</label><span class="asterisk">*</span>

            </div>
        </div>
        <div class="col-sm-9 employee_class">
            
            <div class="form-group disabled" >
                <div class="input-group-prepend">
                    <?php echo $this->form->applicant_name; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 employee_class">
            <div class="form-group disabled" >
                <label style="float:left;"><b>Email Id:</label><span class="asterisk">*</span>

            </div>
        </div>
        <div class="col-sm-9 employee_class">
              <span id="emailError" style="color:red;"></span>
            <div class="form-group disabled" >
                 <?php echo $this->form->email_id; ?>
            </div>
        </div>
    </div>
    
    
    
    <div class="row">
        <div class="col-sm-3 employee_class">
            <div class="form-group disabled" >
              <label style="float:left;"><b>Mobile No:</label><span class="asterisk">*</span>

            </div>
        </div>
        <div class="col-sm-9 employee_class">
            <div class="form-group disabled " >
                  <?php echo $this->form->phone; ?>
            </div>
        </div>
        <!---<div class="mob_info">
            
        </div>
        <div class="col-sm-1 employee_class">
        <div class="load-box">
            <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader2.gif" style="width:8em"  class="loder_img1" />
        </div>
        </div>
         <div class="col-sm-2 employee_class">
            <div class="form-group disabled" >
                <button type="button" onclick="sendOtp()" class="btn btn-primary">Send OTP</button>
            </div>
        </div>-->
    </div>
   <!--- <div class="row">
        
        <div class="col-sm-3 employee_class">
           
            <div class="form-group disabled" >
                
              <label style="float:left;"><b>Validate OTP:</label><span class="asterisk">*</span>
            </div>
            
        </div>
        <div class="col-sm-9 employee_class">
            <span id="otpSucessMsg" style="color:green;float: right;"></span>
            <span id="otpError" style="color:red;"></span>
            <div class="form-group disabled" >
                <?php echo $this->form->check_otp; ?>

            </div>
        </div>
       
    </div>--->
    <div class="row">
        <div class="col-sm-3 employee_class">
            <div class="form-group disabled" >
               <label style="float:left;"><b> Create Password:</b></label><span class="asterisk">*</span>

            </div>
        </div>
        <div class="col-sm-9 employee_class">
            <div class="form-group disabled" >
                <div class="input-container">
                   
                    <?php echo $this->form->password; ?>
                     <i class="fa fa-eye icon" onClick="showPasswordFunction()" style="font-size:24px"></i>
                </div>
                
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 employee_class">
            
            <div class="form-group disabled" >
               <label style="float:left;"><b>Confirm Password:</b></label><span class="asterisk">*</span>

            </div>
        </div>
        <div class="col-sm-9 employee_class">
            <span id="cnfpassError" style="color:red;"></span>
            <div class="form-group disabled" >
                <?php echo $this->form->cnf_password; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-offset-1 employee_class register_form" >
                <button  type="submit" class="register_btn" id="submit" >Verify & Register</button>
            </div>
        </div>
         
         <div class="col-sm-12 employee_class register_form" >
            <b style="color:red">*Note : Please enter a valid and active email Id, as your Application Registration Number and Password will be sent to the same.</b>
        </div>
    </div>
</form>

</div>

 
<script src="<?php echo $this->mainconfig['publicpath']; ?>js/customradio.js"></script> 
<script>
    
    /*$('.load-box2').css('display','none');
        var myVar='';
    function sendOtp(){
        var phone = $('#phone').val();
        var email_id = $('#email_id').val();
        if(phone.length == 0 ){
        alert('Please enter a valid mobile number.');
        }else if(email_id.length == 0){
            alert('Please enter email id.');
        }else{
     
        $('.load-box').css('display','block');
             myVar = setInterval(myTimer, 9000);
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'entrance-exam-form/ajax-send-otp'; ?>',
            data: {phone : phone,email_id:email_id}
        }).done(function( data ) {
            //alert(data);
            if(data==1){
            $('.load-box').css('display','none');
            $('#otpSucessMsg').text("An OTP has been sent to your mobile number and email address. Please enter the same below:");
            $('.mob_info').removeAttr('class');
            $('.mob_info').attr('class',"mob_info form-group glyphicon glyphicon-ok").css("color", "red");
            myStopFunction();
      }else{
        $('.load-box').css('display','none');
        myStopFunction();
        $('.mob_info').removeAttr('class');
        $('.mob_info').attr('class',"mob_info form-group glyphicon glyphicon-remove").css("color", "red");   
    }
        }); 
        }
    }*/
    //Check Duplicate email id in table
    $('#emailError').text("");
    $("#email_id").change(function(){
    //Email validation by kedar : 13 April
    let userinput = $(this).val();
    let pattern = /^[a-zA-Z0-9._-]+@[a-zA-Z]+\.[a-z]+$/i

    if(!pattern.test(userinput)){
        alert('Enter a valid email id.');
        $('#email_id').val('');
    }
    //End
     var email_id = $('#email_id').val();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'entrance-exam-form/ajax-check-duplicate-email'; ?>',
            data: {email_id:email_id}
        }).done(function( data ) {
            //alert(data);
            if(data==1){
                $('#emailError').text("*Email id is already registered with us.");
                $('#email_id').val('');
            }else{
                $('#emailError').text("");
            }
        }); 
    });
    //End
    
//To MATCH PASSWORD
   
    $('#cnf_password').blur(function() {
        if ($('#password').val() == $('#cnf_password').val()) {
            $('#cnf_password').css("color", "green");
            $('#cnf_password').val('' + 'Matched');
            $('#cnfpassError').text("");
            return false;
        } else { 
            $('#cnf_password').css("color", "red");
            $('#cnfpassError').text("Password does not matched.");
            $('#cnf_password').val('');
            return true; 
        }
    });
//End
function myTimer() {
    $('.load-box').css('display','none');
    $('.mob_info').removeAttr('class');
    $('.mob_info').attr('class',"mob_info form-group fa fa-exclamation");
    myStopFunction();
}


function myStopFunction() {
  clearInterval(myVar);
}
$('input[data-toggle="number"]').bind('keyup blur',function(){
    var node = $(this);
    node.val(node.val().replace(/[^0-9]/g,'') );
});

function showPasswordFunction() {
  var x = document.getElementById("password");
  if (x.type === "password") {
    x.type = "text";
  } else {
    x.type = "password";
  }
}
</script>
