<style>
    .multistepformArea{
    padding-top: 1px;
    background-color: white;
	width: 60%;
    min-width: 300px;
	margin: 50px auto;
	position: relative;
}
/*form styles*/
.regForm {
    width: 95%;
    min-width: 300px;
	margin: 50px auto;
	position: relative;
}
#formValidate1 fieldset {
	background: #d4b7b7;
	border: 0 none;
	border-radius: 3px;
	box-shadow: 0 0 1px 1px rgba(0, 0, 0, 0.1);
	box-sizing: border-box;
	position: relative;
}
</style>
<div class="instruction">
    <div class="multistepformArea">
        <form class="regForm" id="formValidate1" action="" method="post" data-validate="parsley" >

            <div class="row">
                <div class="col-sm-12">
                    <fieldset>
                       <?php //echo '<pre>'; print_r($this->paginator); ?>

                        <h4>&nbsp; Dear Applicant <b><u><?= ucfirst($this->paginator['applicant_name'])?></u></b> ,</h4>
                        <div class="col-sm-12 employee_class">
                          
                                <h4> Please note down the <b><u>"Application Number"</u></b> and <b><u>"Password"</u></b> for further <b><u>Application Form(2020)</u></b> process. </h4>
                                <h4>Application Number : <b style="color: red"> <u>"<?= $this->paginator['application_no'] ?>" </u> </b></h4>
                                <h4>Password : <b style="color: red"> <u> "<?= $this->paginator['password'] ?>" </u> </b></h4><br>

                        </div>
                       
                        <div class="col-sm-8 employee_class">
                            <div class="form-group">
                                <h4> Click on the Continue Button to fill your application form.</h4>
                            </div>
                        </div>
                            
                                <div class="col-sm-4 employee_class">
                                    
                                    <a href="<?=  $this->baseUrl("multi-step-form/index/type/step1/a_id/".md5($this->paginator['application_no'])); ?>"> <button type="button" id="continue" class="btn btn-primary">Continue</button></a>
                                </div>
                         <div class="col-sm-12 employee_class" >
                            <b style="color:#ff471a">*Note :Your Application Number and Password also sent on your registered Email Id and Phone Number.</b>
                        </div>
                          
                        </div>
                     
            </div>
                    </fieldset> 
                    &nbsp;<br>
                    <br>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    /*$('#continue').hide();
    $('#instruction').click(function(){
        if (this.checked) {
            $('#continue').show();
        }else{
            $('#continue').hide();
        }
    });*/
</script>