<table class="table table-striped table-bordered mb30 jambo_table bulk_action "
                            id="datatable-responsive">
                            <thead>
                                <tr>
                                    <th>S.  No.</th>
                                     <th>UID</th>
                                    <th>Student Name</th>
                                    <th>Core Course</th>
                                    <th>Generic Electives</th>
                                    <th >REG NO.</th>
                                    <th>Exam Roll No.</th>
                                    <th>Signature of Student</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                        
                                <?php
                                
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {

                                    foreach ($this->paginator as $results) {
                                       
                                        ?>
                                        <tr>
                                            <td><?php
                                                echo $i;

                                                $i++;
                                                ?>
                                            </td>   
                                            <td><?php echo $results['stu_id']; ?></td>
                                            <td><?php echo $results['stu_fname'].' '. $results['stu_lname']; ?></td>
                                           
                                           
                                            <td><?php echo $results['dept_name']; ?></td>
                                            <td ><?php echo $results['ge_name']; ?></td>
          
                                            <td style="vertical-align:middle;" class="form-group-sm">
                                                <?php if ($results['reg_no'] != '0000') { ?>
                                                    <label class='changebox ' style='font-weight:normal;' ><?php echo $results['reg_no']; ?></label>
                                                <?php } else { ?>
                                                    <input type='text' class='changebox form-control' size="12" name='reg_no' data-reg = '<?php echo $results['student_id']; ?>' value="<?php echo $results['reg_no']; ?>"/>
                                                <?php } ?>
                                            </td>
                                            <td style="vertical-align:middle;" class="form-group-sm"><?php // echo $results['reg_no'];  ?>
                                                <?php if ($results['exam_roll'] != '0000') { ?>
                                                    <label class='changebox' style='font-weight:normal;' ><?php echo $results['exam_roll']; ?></label>
                                                <?php } else { ?>
                                                    <input type='text' class='changebox form-control' size="12" name='exam_roll' data-exam = '<?php echo $results['student_id']; ?>' value="<?php echo $results['exam_roll']; ?>"/>
                                                <?php } ?>
                                            </td>
                                            
                                             <td>
                                                <?php
                                               $attendance_model = new Application_Model_BatachSemesterAttendance();
                                  $attendance = $attendance_model->checkAttendByUid($results['stu_id'],$results['ge_id']);
                                                //print_r($attendance); 
                                               if($attendance[0]['attend_status']=='0'){
                                                   echo  'Allowed';
                                               }
                                               else if ($attendance[0]['attend_status']=='1') {
                                                   echo  'Not Allowed';
                                               }
                                                else {
                                                    echo "NA";
                                                }
                                                 ?>

                                        </tr>            
                                        <?php
                                    }
                                   
                                }
                                ?>

                            </tbody>
                           
                        </table>
<script> 
modifiedDataTable();

$('div[class="dt-buttons btn-group"]').appendTo('#moved-buttons');
$(document).ready(function(){
    var cells = [];
    var rows = $("#datatable-responsive").dataTable().fnGetNodes();
    for(var i=0;i<rows.length;i++){
        if($(rows[i]).find("input[type='checkbox']").prop('checked')){
            if($(rows[i]).find("input[type='checkbox']").prev('label').find('i').index()== -1)
            $(rows[i]).find("input[type='checkbox']").prev('label').append('<i class="glyphicon glyphicon-ok"></i>');
        }
    }
});
//Method used to update checkbox!
    $('input[type="checkbox"]').click(function () {

        var reg_no = 0;
        var exam_roll = 0;
        var id = $(this).data('id');
        var tr_no = $(this).parent('td').parent('tr').index();
        var td_no = $(this).parent('td').index();
        if ($(this).prop('checked')) {

            exam_roll = $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + td_no + ')').children('input').val();
            reg_no = $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no - 1) + ')').children('input').val();


            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-saved-result'; ?>',
                data: {exam_no: exam_roll, reg_no: reg_no, id: id}
            }).done(function (data) {
              //  if (data = 1){
                  reg_no =   $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no - 1) + ')').children('input').val();
                  exam_roll =   $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no) + ')').children('input').val();
                  
                  $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no - 1) + ')').children('input').remove();
                  $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no) + ')').children('input').remove();
                  
                  
                     $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no - 1) + ')').append("<label class='changebox' style='font-weight:normal;'>"+reg_no+"</label>");
                       $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no) + ')').append("<label class='changebox' style='font-weight:normal;'>"+exam_roll+"</label>")
            });
        } else {

            exam_roll = $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no-1) + ')').children('label').text();
            reg_no = $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no) + ')').children('label').text();
            
            exam_roll_text = $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no-1) + ')').children('input').val();
            reg_no_text = $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no) + ')').children('input').val();

            $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + td_no + ')').children('label').remove();
            $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no - 1) + ')').children('label').remove();
            
            if(exam_roll_text !='0000'){
            $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no - 1) + ')').append("<input type='text' size='12' class='changebox form-control' name='reg_no' data-reg = '"+id+"'  value='" + exam_roll + "'/>")}
            
            if(reg_no_text !='0000'){
            $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no) + ')').append("<input type='text'  size='12' data-exam = '"+id+"' class='changebox form-control' name='exam_roll' value='" + reg_no + "'/>");}

        }

    });
    
    //Method is used to get Total records!
     $(document).ready(function () {

        var text = $('#datatable-responsive_info').text();

        res = text.split("of");

        if (res.length > 0) {

            if (res[1]) {
                act_text = res[1].split("entries");
            $("<div id='custom_data_records'><label>Total Records : <span>" + act_text[0] + "</span></label></div>").insertAfter('#datatable-responsive_length');
                $('input[type="search"]').keyup(function () {
                    $('#custom_data_records').remove();
                    var text = $('#datatable-responsive_info').text();
                    res = text.split("of");
                    act_text = res[1].split("entries");
                    $("<div id='custom_data_records'><label>Total Records : <span>" + act_text[0] + "</span></label></div>").insertAfter('#datatable-responsive_length');
                });
            }
        }
    });
    
    
    $('button').click(function(){

var reg_no = [];
var reg_id = []
var roll_no = [];
var roll_id = [];

$('input[name="reg_no"]').each(function(e){
   reg_no.push($(this).val());
   reg_id.push($(this).data('reg'));
    
});

$('input[name="exam_roll"]').each(function(e){
    roll_no.push($(this).val());
    roll_id.push($(this).data('exam'));
    
});
if(reg_no.length >0 || roll_no > 0 ){
    $('.load-box').show();
   $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-bulk-saved-result'; ?>',
                data: {reg_no: reg_no, reg_id: reg_id, roll_no: roll_no,roll_id:roll_id}
            }).done(function (data) {
               $('head').append("<meta http-equiv='refresh' content = '0'>");
            });
            }

});


    
    </script>