<style>

    @media print {

                    table td:nth-child(5)

                     {

                         display:none;

                     }

                     table th:nth-child(5)

                     {

                         display:none;

                     }

                      *{

                        visibility:hidden;

                     }

                     table,th,td 

                     {

                         visibility:visible;                    

                     } 

                     .title1

                     {

                        visibility:visible; 

                     }

                }
                

    .ui-datepicker-calendar {
    display: none;
    }
    .dataTable  tbody {
    width: 100%;
    
}

.bg-primary{
    background-color: #932e90;
}

#component_paper_chosen{
    display:none;
}

</style>

<div class="right_col">

    <?php if ($this->type == 'add') { ?>

        <div class="padding-md">

            <div class="row">

                <div class="col-md-12 " >

                    <h3 class="page-title txt-color-blueDark" >

                        <div><i class="fa fa-eye">Razor Pay:</i></div>

                    </h3>

                    <div class="panel panel-default">

                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >



                            <div class="panel-body">

                                <div class="row">



                                    <div class="col-sm-2 employee_class">

                                        <div class="form-group" >

                                            <label  class="control-label" >Degree

                                            <span class="asterisk">*</span></label>

                                            <?php echo $this->form->degree_id; ?>

                                        </div>

                                    </div>
                                    <div class="col-sm-4 employee_class">

                                        <div class="form-group" >

                                            <label  class="control-label" >From Semester

                                            <span class="asterisk">*</span></label>

                                            <?php echo $this->form->semester; ?>

                                        </div>

                                    </div>

                                    <div class="col-sm-4">

                                        <div class="form-group">

                                            <label  class="control-label" >To Semester

                                            <span class="asterisk">*</span></label>

                                           <?php echo $this->form->nextSem; ?>

                                        </div>

                                    </div>

                                    

                                    <div class="col-sm-2">

                                        <div class="form-group">

                                            <label  class="control-label" >Minimum Credit(%)

                                                <span class="asterisk">* </span></label>

                                              

                                            <?php echo $this->form->credit_score; ?>

                                            <span id="credit_error" style="color:red;"></span>

                                        </div>

                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-sm-4">

                                        <div class="form-group">

                                            <label  class="control-label" >Passed in No. of papers

                                                <span class="asterisk">*</span></label>

                                            <?php echo $this->form->semester_paper_count; ?>

                                        </div>

                                    </div>

                                    <div class="col-sm-4">

                                        <div class="form-group">

                                            <label  class="control-label" >Must appear in no. of papers

                                                <span class="asterisk">*</span></label>

                                            <?php echo $this->form->appeared_paper; ?>

                                        </div>

                                    </div>

                                    <div class="col-sm-4">

                                        <div class="form-group">

                                            <label  class="control-label" >Appear in Components (paper)

                                                <span class="asterisk">*</span></label>

                                            <?php echo $this->form->component_paper; ?>

                                        </div>

                                    </div>

                                </div>

                            </div>

                            <div>

                                <div class="panel-footer">									

                                    <div class="row">

                                        <div class="col-sm-7 col-sm-offset-5">

                                            <?php if ($this->type == 'add') { ?> 

                                                <div style="float:left;margin-right:2px;">

                                                    <button class="btn btn-primary submit">Submit</button>

                                                </div>

                                                <div style="float:left;padding:0px 10px;">

                                                    <button type="reset" class="btn btn-danger btn-default">Reset</button>

                                                </div>

                                            <?php } else { ?>

                                                <div style="float:left;">

                                                    <button class="btn btn-primary submit">Update</button>

                                                </div>

                                                <div style="float:left;">

                                                    <a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>promotion/index/">Back</a>

                                                </div>

                                            <?php } ?>

                                        </div>

                                    </div>

                                </div>

                            </div>

                        </form>

                    </div><!-- /panel -->

                </div><!-- /.col-->				

            </div><!-- /.row -->



        </div><!-- /.padding-md -->	
         <?php } else if($this->type == "students") { ?>



        <?php

        if (count($this->messages)) {

            foreach ($this->messages as $message) {

                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

            <?php

            }

        }

        ?>

        <!-- widget grid -->

        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> Students </i>



                        </h3>

                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 



<!--                        <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>promotion/index/type/add">Add </a>-->

                    </div>

                </div>



                <div class="x_panel">



                    <div class="x_title">

                        <h2 class="title1">Admission  Records</h2>

                        <ul class="nav navbar-right panel_toolbox">

                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>

                            </li>

                            <li class="dropdown">

                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                            <li><a class=""><i class="fa fa-close"></i></a>

                            </li>

                        </ul>

                        <div class="clearfix"></div>

                    </div>

                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive">

                            

                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;">S. No.</th>	
                                        <th style="text-align:center;">Applicant Name</th>
                                       <th style="text-align:center;">Father's Name</th>
                                        <th style="text-align:center;">Roll No</th>
                                        
                                        <th style="text-align:center;">Form Id</th>

                                        <th style="text-align:center">Course</th>

                                        <th style="text-align:center">core_course1</th>

                                        <th style="text-align:center">ge1</th>
                                        
                                        <th style="text-align:center">core_course2</th>
                                        
                                        <th style="text-align:center">ge2</th>
                                        <th style="text-align:center">compulsory</th>
                                        
                                        <th style="text-align:center">aecc1</th>
                                        <th style="text-align:center">aecc2</th>
                                        <th style="text-align:center">Pay Status</th>
                                        <th style="text-align:center">Photo</th>
                                       <th style="text-align:center">Admit Card</th>

                                        <!--<th class="no_print" style="text-align:center">Edit | Delete</th>-->



                                    </tr>

                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
                                            $geinfo = new Application_Model_Ge();
                                           $deptinfo = new Application_Model_Department();
                                           $deptType = new Application_Model_DepartmentType();
                                          $educdet = new Application_Model_ApplicantCourseDetailModel();
                                          
                                         
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {



                                        foreach ($this->paginator as $results) {

                                            //print_r($results);die;

                                            ?>

                                            <tr>

                                                <td><?php

                                                    echo $i;



                                                    $i++;

                                                    ?>

                                                </td>	
                                                <td><?php echo $results['applicant_name'];?></td>
                                                <td><?php echo $results['father_name'];?></td>
<?php  $edu_details = $educdet->getApplicationCourseDetails($results['form_id']); ?>
                                                <td><?=$results['roll_no1']; ?></td>

                                                <td><?php echo $results['form_id'];?></td>
                                                
                                                 <td><?php echo $deptType->getRecord($results['course'])['department_type']; ?></td>
                                                 <td><?php if($edu_details['core_course1']){echo $deptinfo->getRecordbyAcademic($edu_details['core_course1'])['dpt_name'];}else{echo '--';}?></td>
                                                        
                                                <td><?php if($edu_details['ge1']){echo $geinfo->getRecord($edu_details['ge1'])['general_elective_name'];}else echo '--'; ?></td>
                                                <td><?php if($edu_details['core_course2']){echo $deptinfo->getRecordbyAcademic($edu_details['core_course2'])['dpt_name'];}else{echo '--';}?></td>

                                                <td><?php if($edu_details['ge1']){echo $geinfo->getRecord($edu_details['ge2'])['general_elective_name'];}else echo '--'; ?></td>
                                                <td><?php echo $edu_details['comp_evs']; ?></td>
                                                <td><?php echo $edu_details['aecc1'];?></td>

                                                <td><?php echo $edu_details['aecc2']; ?></td>
                                                <td class='<?php if($results['payment_status1'] == 1){ echo 'text-success';}else{echo "text-danger";};?>'><?php if($results['payment_status1'] == 1){echo "Paid";}else{ echo "NA";} ?></td>
                                              <td><img src = "/academic/<?= $results['photo'];?>" width ="70em" alt ='NA'/></td>
                                              
                                              <td><a class="btn btn-primary" target='_blank' href ='/academic/entrance-exam-form/document-dashboard/a_id/<?=md5($results['application_no']); ?>'>click here</a></td>

<!--                                                <td><a href="<?php echo $this->mainconfig['host']; ?>promotion/index/type/edit/id/<?php echo $results['id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>promotion/index/type/delete/id/<?php echo $results['id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>-->

                                            </tr>            

                                            <?php

                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                                </tbody>

                            </table>

    <?php// echo $pagination_tr; ?>

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->		



    <?php } else { ?>



        <?php

        if (count($this->messages)) {

            foreach ($this->messages as $message) {

                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

            <?php

            }

        }

        ?>

        <!-- widget grid -->

        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> Students </i>



                        </h3>

                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 



<!--                        <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>promotion/index/type/add">Add </a>-->

                    </div>

                </div>



                <div class="x_panel">



                    <div class="x_title">

                        <h2 class="title1">Admission  Records</h2>

                        <ul class="nav navbar-right panel_toolbox">

                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>

                            </li>

                            <li class="dropdown">

                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                            <li><a class=""><i class="fa fa-close"></i></a>

                            </li>

                        </ul>

                        <div class="clearfix"></div>

                    </div>

                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive">

                            

                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;">S. No.</th>	
                                        

                                        <th style="text-align:center">Course</th>
                                        <th style="text-align:center">Applied Students</th>
                                        <th style="text-align:center">Paid Students</th>

                                     
<!--                                        <th style="text-align:center">Degree</th>-->
                                       

                                        <th class="no_print" style="text-align:center">View</th>



                                    </tr>

                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
                                            $geinfo = new Application_Model_Ge();
                                           $deptinfo = new Application_Model_Department();
                                           $deptType = new Application_Model_DepartmentType();
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {

                                        $totpaid = $totapp = 0;

                                        foreach ($this->paginator as $results) {

                                            //print_r($results);die;

                                            ?>

                                            <tr>

                                                <td><?php

                                                    echo $i;



                                                    $i++;

                                                    ?>

                                                </td>	
                                                

                                                <td class='<?php if(!$results['course'])echo "text-danger"; ?>'><?php if($results['course']){echo $deptType->getRecord($results['course'])['department_type'];}else{echo "<b>Warning !</b> students without courses...";} ?></td>
                                                <td data-id = '#totapp' class='app' ><?php echo $results['total_applied']; $totapp += $results['total_applied']; ?></td>
                                                <td data-id='#totpaid' class='paid' ><?php echo $results['paid']; $totpaid+=$results['paid']; ?></td>
                                               
                                                
                                              

                                                <td><a href="<?php echo $this->mainconfig['host']; ?>student/form-student/type/students/id/<?php echo $results['course']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>
<!--<td></td>-->
                                            </tr>            

                                            <?php

                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th class="bg-primary text-center" colspan = 2 style="letter-spacing:.3em;">TOTAL STUDENTS</th>
                                         <th class="bg-primary text-center" id="totapp" style="letter-spacing:.3em; font-size:1.3em"><?=$totapp; ?></th>
                                        <th class="bg-primary text-center" id="totpaid" style="letter-spacing:.3em; font-size:1.3em"><?=$totpaid;?></th>
                                       
                                      
                                        <th class="bg-primary text-center" id="np" style="letter-spacing:.2em;"><small>Not Paid Students</small> = <?=$totapp-$totpaid;?></th>
                                    </tr>
                                </tfoot>

                            </table>

    <?php// echo $pagination_tr; ?>

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->		

<?php } ?>

</div>

<script>



setDatatables();
$(document).ready(function(){
 
        alert($('select[name="datatable-responsive_length"]').val());
    
    
});

</script>

