<?php if(!empty($this->paginator)){ 
    
    //echo '<pre>'; print_r($this->paginator);exit;
?>
   

                                                 
                                                 
  
<style>
@media print {
  
  button,fieldset{
      position:fixed !important;
      display:none !important;
  }
  
  .slno{
      float: right;
      text-align: right;
  }
  .rightAssign{
      float: right;
      text-align: right;
      
  }
    #applicationFormPreview{
        padding-left: 2em;
        padding-right:2em;
        position:absolute !important;
        top:0px !important;
        width:100%;
    }
  
    p{
        font-size: 18px;
    }
  .pagebreak {
       clear: both;
      page-break-after: always; }
}
 @page 
    {
        position:absolute !important;
        size:  auto;   /* auto is the initial value */
        margin: 1mm;
        margin-top:0; 
       /* this affects the margin in the printer settings */
    }   
    
</style>
<div class="right_col">
<div class="appForm" id="applicationFormPreview">
<div class="" id="applicationFormPreview">
       <div style="float:right;padding-bottom: 3em;" id="divbutton">
            <button type="button" id="printAppForm2"  class="btn btn-primary" onclick="window.print()"></button>
        </div>
 
        <div id="section-to-print">
               <div class="col-xs-1 slno" >
                                <b>S.No.- <?php echo "\t"; echo $this->paginator['mig_no']; ?></b>
                            </div>    
            <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action " >

                <thead>
                    <tr>
                       
                    </tr>
                </thead>
                <tbody>
                   
                    <tr>
                        <td class="col-sm-3 ">
                            <div class="form-group">
                                 <img src="<?php echo $this->mainconfig['publicpath']; ?>img/logo.png" width="100" height="90">          
                            </div>
                        </td>
                       

                        <td class="col-sm-9" style="text-align: center;">
                            <div class="col-xs-9"  style="text-align: center;">
                            <h1> PATNA WOMEN'S COLLEGE</h1>

                            <div class="sameline" style="display: inline-block;">

                                <h3> AUTONOMOUS <br>
                                PATNA UNIVERSITY</h3>
                                
                            </div> 

                            </div>
                        </td>
                        
                    </tr>
                  
                </tbody>
            </table>            
                 
            <div class="col-xs-12">
                <h2  style="text-align: center"> <u>Migration Certificate </u> </h2> 
                
                <?php $studentName=strtolower($this->paginator['stu_fname']);
                     $fatherName=strtolower($this->paginator['father_fname']);
                ?>
                
               
                
                <p> Ms./ Mrs. <b><i><?php echo ucwords($studentName);echo "\t";?> </i></b> Daughter of<b> <i><?php echo ucwords($fatherName); echo "\t";?> </i> </b> Department <b> <i><?php echo $this->paginator['batch'];?> </i></b>College <b><i>PATNA WOMEN'S COLLEGE </i></b> Registration No. <b><i> <?php echo $this->paginator['reg_no'];?>.</i></b> </p>
                
                

            <p>The College has no objection to her joining any recognised College/ Institute/University established by law.</p>

            </div>
          
           <div class="col-sm-6">
               Date <?php echo date('d/m/Y') ?>
               
            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;	&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
               <img src="<?php echo $this->mainconfig['publicpath']; ?>images/principal.jpg" alt="..."  height ="40" width="200"><br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;	&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;	&emsp;&emsp;&emsp;&emsp;&emsp;	&emsp;&emsp; &emsp;&emsp; Principal <br>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;	&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; Patna Women's College<br>
                   &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;	&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;	&emsp;&emsp;&emsp;&emsp;&emsp;	&emsp; Bailey Road, Patna-1
          
          

        </div>
</div>
</div>
</div>
<?php }else{ ?>   

<div class="right_col">
    <label id="alert_msg" style="color:red; ">
       Result not found.....!Oop's:) 
    </label> 
    
</div>
<?php  } ?>                                         