
<script>
    
    
var id = '<?=$this->id?$this->id:0;?>';
if(id != 0){
$('#fac').hide();
   $('<div class="col-sm-12 text-center"><h4 class="text-danger"><strong>**Published TABULATION REGISTER Cannot be Modified.<br><small class="text-danger"><b>(Note:</b>&nbsp; Course Listed only with Created Evaluation Components.<b>)</b></small></strong></h4></div>').insertBefore('table');
}
else
{
   $('#fac').show(); 
}
</script>
<style>
@media print {
  * {
    display: none;
  }
  #printBox {
    display: block;
  }
}
    
/*    button{*/
/*        display:none;*/
/*    }*/
    
/*     table
    {
        width: auto;
        font-size: 1em;
    }
    table tr{
        padding:0 !important;
    }
    table tr,th,td {
        min-width: .1em !important;
        max-width:3.5em !important;
        word-wrap:break-word !important;
         padding:0.5em !important;
    }*/
    
/*     table {
    table-layout: auto !important;
}

.table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
    width: auto !important;
    padding:0 !important;
}*/

/*   @media print*/
/*{*/
/*  table { page-break-after:auto !important; }*/
/*  tr    { page-break-inside:avoid !important; page-break-after:auto !important; }*/
/*  td    { page-break-inside:avoid !important; page-break-after:auto !important; }*/
/*  thead { display:table-header-group !important;}*/
/*  tfoot { display:table-footer-group !important; }*/
/*}*/
/*</style>*/
<?php
 $eval_items = new Application_Model_EvaluationComponentsItems();
    $course_learning = new Application_Model_ElectiveSelection();
                    $StudentPortal_model = new Application_Model_StudentPortal();
                      
                        $Corecourselearning_model = new Application_Model_Corecourselearning();
                         $acd_details = new Application_Model_Academic();
                        $deg_details = new Application_Model_Department();
                          $term_details = new Application_Model_TermMaster();
                             $semester_rule = new Application_Model_SemesterRule();
                              $course_details = new Application_Model_Course();
                                 $GradeAllocation_model = new Application_Model_GradeAllocation();
$fail_Val = array('D'=>'F','F'=>'F');
$item_result = $this->result;
$passpercent = $this->passpercent;
$acad = $this->acad;
$ter = $this->term;
$dept_name = $this->dept_name;


//====Variable Declaration==========//
$i = 1;
$k = 0;
$mks = $tot_credit=$mksweightage = $tot_credit_point = $tot_grade_point = $one_row = $stu_data_pr = $component = $weightage = 0;
$EvaluationComponents_model = '';
$geData = array();
$geWeightage = array();
$ct_arr = $weightage_arr = $component_arr = array();
$extraSem = 0;

//======['start printing tabulation register']=======//

    ?>
<!--[table head to be aligned into middle]---------->
    <style>


        
    </style>
    <div class="box-body table-responsive" >
        <div style="overflow-x:scroll" >
            <div id='printBox'>
            <table class="mb30 jambo_table bulk_action datatable datatable-multi-row"  border ='1' id='dataTable' style="height:20em;" >
                <thead>
                    <tr style="padding:0">
                        <?php  ?>
                        <input type ="hidden" id='tabl_id' value="<?=$this->id?$this->id:0;?>"/>
                        <th rowspan="4"  class="complex">S. No.</th>
                        <th rowspan="4" data-datatable-multi-row-rowspan="4" class="complex">UID</th> 
                             <th rowspan="4" data-datatable-multi-row-rowspan="4" class="complex">Reg. No./Exam. Roll No./Candidate Name/Father Name</th>
                        <th></th>
                        <?php
                       
                        for ($i = 0; $i < count($item_result); $i++) { 
                         $course_type_result = $Corecourselearning_model->getcourseTypeOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);  ?>
                       
                        <th colspan = "<?=count($course_type_result)+2?>">Semester <?=$i+1;?></th>
                        
                        <?php } ?>
                        <th rowspan="2"   style='padding: 0.2em;'>Grand Total</th>
                        <th rowspan="2"   style='padding: 0.2em;'>CGPA (cr. point/cr.)</th>
                        <th rowspan="2"   style='padding: 0.2em;'>%(Percentage)</th>
                        <th rowspan="2"   style='padding: 0.2em;'>CGPA Grades</th>
                        <th rowspan="2"   style='padding: 0.2em;'>Remarks/Fail in</th>
                        </tr>
                        
                        
<!--                        <th rowspan="2" class="complex">ID Number</th>-->
                        
                     <tr>
            
                <?php
                /*
                 * calling model course_corse_learning
                 * if course credit has been created
                 * then get the courseType value 
                 * 
                 */
                 $student_course = [];
                for ($i = 0; $i < count($item_result); $i++) {
                 
                $tot_arr = array(); 
        $credit_head_arr = array();
                
                $course_type_result = $Corecourselearning_model->getcourseTypeOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);
//-------------------------------------------------------****************------------------------------------------------------------------------------------------------//     
                foreach ($course_type_result as $course_type_key => $course_type_val) {//====printing upper head with component==// 
          
                    $item_result[$i]['course_id'] = $course_type_val['course_id'];
                    $student_course[] = $course_type_val;
                    ?>
                  
<!--                    <th rowspan="2" class="complex">Course Code</th>-->
                    <?php if ($component == 0) { ?>
                   
                        <th class="complex" >Course Code</th>
 
                        <?php $component++;
                    } ?>
                    <?php
                    //====================[getting all the evaluation component]======================================//
                  $EvaluationComponents_model = new Application_Model_EvaluationComponents();
                    $result = $EvaluationComponents_model->getAllComponentsonTerms(0, 0, $item_result[$i]['course_id']); 
                     if($course_type_key == 1 && $item_result[$i]['term_id']===310){
                                    $course_type_val = $course_type_result[2]; 
                                }
                                else if($course_type_key == 2 && $item_result[$i]['term_id']===310){
                                   $course_type_val = $course_type_result[1];
                                } 
                    
                    ?>
                    <th class="complex" style='padding: .2em;'><?php if(!in_array($course_type_val['ge_id'],array(34,37,38,14,35))){ echo $course_type_val['course_code'];  }else{ echo $course_type_val['ct_name']; } ?></th>
                   
                 
                    
    <?php } ?>
                <th rowspan="1"   style='padding: 0.2em;'>Total</th>
                <th class="complex" style='padding: 0.2em;'>SGPA <br/>(Cr. Point/ Cr.)</th>
                
               
                <?php  } ?>
                </tr> <?php //==========[END Printing upper components]====================//  ?>
  <!-----------------------------------------------------------**************************---------------------------------------------------------------------------->
                <tr>
                    <?php
                     
                    for ($i = 0; $i < count($item_result); $i++) {
                       
                    //========================[Getting all the course and ge_id for the weightage]============================//
                    $newData = $EvaluationComponents_model->getAllComponentsonTerms1($item_result[$i]['academic_year_id'], $item_result[$i]['term_id'], 0);

                   
                    $getNewWeightage = $ct_arr = $getWeightage = array();

                    //==================[Fettering Weightage according to their courses_id]=============================================]=======//
                    foreach ($newData as $Studkey => $newVal) {
                        $getWeightage[$newVal['ct_id']][$newVal['course_id']][$newVal['component_id']] = $newVal['weightage'];
                    }
                    
                     $course_type_result = $Corecourselearning_model->getcourseTypeOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);
                    //===========================[Start printing the lower head with weightage]==============================================//
                    foreach ($course_type_result as $course_type_key => $course_type_val) {
                        $component_arr = array();
                        $item_result[$i]['course_id'] = $course_type_val['course_id'];
                        //===============[Filtering according to their component id]======================//
                        foreach ($getWeightage[$course_type_val['ct_id']] as $Studkey => $newVal) {
                            Ksort($newVal);
                            foreach ($newVal as $component_id => $weightage_val) {
                                $getNewWeightage[$course_type_val['ct_id']][$component_id][] = $weightage_val;
                            }
                        }
                        
                        $result = $getNewWeightage[$course_type_val['ct_id']];
                        if($course_type_val['count_id'] == 0){
                        $credit_head_arr[$item_result[$i]['term_id']][] = $course_type_val['credit_value'];
                        }
                        ?>
                        <?php if ($weightage == 0) { ?>
                            <th >Credit</th>
                            <?php $weightage++;
                        }else if($course_type_key == 0){  ?>
                      
                        <th></th>
                        <?php } ?>
                        <?php $arr_check = array(); ?>
                        <!--weightage---->
                        <th><?= $course_type_val['credit_value'];?></th>
                        <?php
                        $tot_credit+=$course_type_val['credit_value'];
                        /*
                         * this loop making single head uniqe if duplicates 
                         * marks and print the weightage
                         * 
                         * 
                         */
                         
                        foreach ($result as $k => $val) {
                            $val1 = $val;
                            $val = array_unique($val);
                            ?>
                            
                              
                             <?php // implode('/', $val);
                                $new_arr = $val1;
                                foreach ($new_arr as $weightage_key => $to_val) {
                                    $tot_arr[$course_type_val['ct_id']][$weightage_key] += $to_val;
                                }
                                ?>
                           
                            <?php
                        }

                        $total_sub_mks = array_unique($tot_arr[$course_type_val['ct_id']]);
                        ?>
                        
    <?php }?> 
      <th><?= array_sum($credit_head_arr[$item_result[$i]['term_id']]); ?></th>
    <?php } ?>
    <th></th>
    <th><?=$tot_credit;?></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
                </tr>
                
                
                
                   <tr>
                    <?php
                    for ($i = 0; $i < count($item_result); $i++) {
                              
                $tot_arr = array(); 
                $credit_head_arr = array();
                 $total_head_arr = array();
                    //========================[Getting all the course and ge_id for the weightage]============================//
                    $newData = $EvaluationComponents_model->getAllComponentsonTerms1($item_result[$i]['academic_year_id'], $item_result[$i]['term_id'], 0);

                   
                    $getNewWeightage = $ct_arr = $getWeightage = array();

                    //==================[Fettering Weightage according to their courses_id]=============================================]=======//
                    foreach ($newData as $Studkey => $newVal) {
                        $getWeightage[$newVal['ct_id']][$newVal['course_id']][$newVal['component_id']] = $newVal['weightage'];
                    }
                    
                     $course_type_result = $Corecourselearning_model->getcourseTypeOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);
                    //===========================[Start printing the lower head with weightage]==============================================//
                    foreach ($course_type_result as $course_type_key => $course_type_val) {
                        $component_arr = array();
                        $item_result[$i]['course_id'] = $course_type_val['course_id'];
                        //===============[Filtering according to their component id]======================//
                        foreach ($getWeightage[$course_type_val['ct_id']] as $Studkey => $newVal) {
                            Ksort($newVal);
                            foreach ($newVal as $component_id => $weightage_val) {
                                $getNewWeightage[$course_type_val['ct_id']][$component_id][] = $weightage_val;
                            }
                        }
                        
                        $result = $getNewWeightage[$course_type_val['ct_id']];
                        ?>
                        <?php if ($mksweightage == 0) { ?>
                            <th >Full Marks/ Pass Marks</th>
                            <?php $mksweightage++;
                        }else if($course_type_key == 0){ ?>
                    
                        <th></th>
                        <?php } ?>
                        <?php $arr_check = array(); ?>
                        <!--weightage---->
                        <th>
                        <?php
                        $x = 0;
                        /*
                         * this loop making single head uniqe if duplicates 
                         * marks and print the weightage
                         * 
                         * 
                         */
                         
                        foreach ($result as $k => $val) {
                            $val1 = $val;
                            $val = array_unique($val);
                            ?>
                            
                             <?php // implode('/', $val);
                                $new_arr = $val1;
                                foreach ($new_arr as $weightage_key => $to_val) {
                                    $tot_arr[$course_type_val['ct_id']][$weightage_key] += $to_val;
                                }
                                ?>
                           
                            <?php
                        }
                        $passpercent = $this->passpercent;
                        $total_sub_mks = array_unique($tot_arr[$course_type_val['ct_id']]);
                           if($total_sub_mks[0]==250){
                                    $passpercent = 50;}
                               else if($total_sub_mks[0]==25){
                                   $passpercent = 50;
                    }
                    
                                   $passmarks = ((int)$passpercent/100)*(int)$total_sub_mks[0];
                                   if($course_type_val['count_id'] == 0){
                            $total_head_arr[$item_result[$i]['term_id']][]  =  $total_sub_mks[0]; 
                             $mks += $total_sub_mks[0];
                                   }
                        echo $total_sub_mks[0].'/<br/>'.$passmarks;
                     
                        ?>
                    
                        
    <?php }?>  
    <th><?=array_sum($total_head_arr[$item_result[$i]['term_id']]);?></th>
    <?php }?>
    <th></th>
   <th><?=$mks;?></th>
   <th></th>
   <th></th>
   <th></th>
   <th></th>
                </tr>
               
                
                
               
  <!-----------------------[End printing head]--------------------------------------------------------------------------------------------------->
                </thead>
                <tbody>
                     
                    <?php 
                    $m = 1;
                    $inde = 0;
                    $corce = array();
                 
                //===============[Degree_id & cmn terms]==========================//    
                       
                        $d_id = $acd_details->getRecord($item_result[0]['academic_year_id'])['department'];
                        $degree_id= $deg_details->getRecord($d_id)['degree_id'];
                      
                        $cmn_term = $term_details->getRecord($item_result[0]['term_id'])['cmn_terms'];
                     
                        $details = $semester_rule->checkRow($degree_id, $cmn_term);
               //========================[END]========================//
               
                    $category_data = $StudentPortal_model->getstudentsdetailsFinal($item_result[0]['academic_year_id'],$cmn_term);
                    foreach ($category_data as $stu_data){
                    $credit_arr = array();
                    $grade_arr = array();
                     $gp_tot = $gr_tot = $count_id = $p_count = $appear_count = $tot_credit_point = $total_gradepoint = $one_row = $stu_data_pr = 0;
                    $gp =  $fcourse_ids= $promotion = $pass_in_ct_id  = $fail_ct_id = $fail_in = $ge_check_arr = array();
                    
                    $sgparem = '';
                        ?>
                   
                        <tr title = "<?php echo $stu_data['students']; ?>">
                            <input type='text' style="display:none;" name='stu_ids[]' value="<?=$stu_data['student_id'];?>" />
                           
                            <?php
                            for ($i = 0; $i < count($item_result); $i++) {
                            $tot_arr = array(); 
                           $tgp = $tcp = $tot_term_cr = $tot_term_mks_head =  $tot_term_masrks = 0;
                        $ge_check_arr = array();
                        
                            $course_type_result = $Corecourselearning_model->getcourseTypeOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);
  
    
                            foreach ($course_type_result as $course_type_key => $course_type_val) {
                                  if($course_type_key == 1 && $item_result[$i]['term_id']===310){
                                    $course_type_val = $course_type_result[2]; 
                                }
                                else if($course_type_key == 2 && $item_result[$i]['term_id']===310){
                                   $course_type_val = $course_type_result[1];
                                } 
                                $ge_id_arr = $Corecourselearning_model->getcourseTypeOn1($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);
                                $ge_id = 0;
                                if ($course_type_val['ge_id'] != 0) {
                                    $ge_id = $course_type_val['ge_id'];
                                    foreach ($ge_id_arr as $ge_key => $ge_val) {
                                        $item_result[$i]['course_id'] = $course_learning->getStudentSelectedElectivesOnGeId($item_result[$i]['academic_year_id'], $item_result[$i]['term_id'], $stu_data['student_id'], $ge_val['ge_id'],$ge_val['course_id']);
                                        
                              if (!empty($item_result[$i]['course_id']) && !in_array($ge_val['course_id'], $ge_check_arr) && $course_type_val['ct_id']==$ge_val['ct_id']) {
                                            $ge_check_arr[] = $ge_val['course_id'];
                                            $count_id = $ge_val['count_id'];
                                            $prin_len = 0;
                                            break;
                                        } else {
                                         $item_result[$i]['course_id']='';
                                         $count_id = 0;
                                        }
                                    }
                                } else{
                                          $item_result[$i]['course_id'] = $course_type_val['course_id'];
                                }
                                
                             //   $result = $EvaluationComponents_model->getAllComponentsonTerms(0, 0, $item_result[$i]['course_id']);
                            if(empty($item_result[$i]['course_id']))
                                   $prin_len = 1;
                                ?>

                                <?php if ($stu_data_pr == 0) { ?>
                                    <td rowspan="3" data-datatable-multi-row-rowspan="3" class="group" style="vertical-align:middle;"><?php echo $m; ?></td>	
                                    <td rowspan="3" data-datatable-multi-row-rowspan="3" class="group" style="vertical-align:middle;"><?php echo $stu_data['stu_id']; ?></td>
                            <input type='text' style="display:none;"  name="grade[student_id_<?= $stu_data['student_id'].$item_result[$i]['academic_year_id']; ?>_<?php echo $item_result[$i]['term_id']; ?>_<?php echo $item_result[$i]['course_id']; ?>][]" id="student_id" value="<?php echo $stu_data['student_id']; ?>" />
<!--                            <td><?php echo $stu_data['stu_id']; ?></td>-->
                          
                            <?php $stu_data_pr++;
                        }
                        ?>

                        <?php
                          if($item_result[$i]['course_id']){
                       
                        $course = $course_details->getRecord($item_result[$i]['course_id']);
                          }
                          else{
                                    $course['course_name'] ='--'; 
                                $course['course_code'] ='--'; 
                          }
                        ?>

                        <?php 
                        if (!in_array($item_result[$i]['course_id'], $corce[$course_type_val['ct_id']])) {
                            $corce[$course_type_val['ct_id']][] = $item_result[$i]['course_id'];
                        } ?> 
<!--                        <td><?php echo $course['course_code']; ?></td>-->
                        <?php
                        ?>
                        <?php if ($one_row == 0) { ?>
                            <td><?php echo $stu_data['reg_no']; ?>/ <?php echo $stu_data['exam_roll']; ?>/ <?php echo $stu_data['students']; ?>/ <?=$stu_data['father_name']; ?></td>
                            <td></td>
                            <?php $one_row++;
                        } ?>
                        <?php
                        $total_divisor = $total_marks_obained = $total = 0;
                        if(!empty($item_result[$i]['course_id'])){
                        $component_grades = '';
                        $letter_grade1 = '';
                        $pass_fail = 'P';
                        $pass_fail_final = 'P';
                        $new_numeric = 0;
                        // foreach($result as $k => $val) { 
                     
                        $grade_result = $GradeAllocation_model->getGradeRecordson($item_result[$i]['academic_year_id'], $item_result[$i]['term_id'], $item_result[$i]['course_id'], $stu_data['student_id']);
      
                        $component_grades = $grade_result['component_id'];
                        //$grade = $grade_result['grade_value'];
                        $component_res = explode(",", $grade_result['component_id']);
                        $number_result = explode(",", $grade_result['number_value']);
                        $grade_result = explode(",", $grade_result['grade_value']);
                        ?>

                        <?php
                        $comp_weightages = '';
                       
                        foreach ($grade_result as $k => $grade_value) {
                            $prin_len--;
                                $pass_fail = 'P';
                            // echo "<pre>";print_r($number_result);
                            $style = '';
                                $letter_grade='';
                                        if (array_key_exists($grade_value,$fail_Val)) {
                                            $style = '';
                                            $pass_fail = 'F';
                                            $pass_fail_final = 'F';
                                            $style="style='color:red'";
                                            
                                        } else if (strtolower($grade_value) == 'ab') {
                                            $number_result[$k] = $grade_value;
                                            $style = 'style="color: #ff0000"';
                                            $style1 = 'style="color: #ff0000"';
                                            $pass_fail = 'F';
                                             $pass_fail_final = 'F';
                                              $style="style='color:red'";
                                            
                                        } else if (strtolower($grade_value) == 'na') {
                                            $number_result[$k] = 'NA';
                                            $style = 'style="color: #ff0000"';
                                            $pass_fail = 'F';
                                             $pass_fail_final = 'F';
                                           $style="style='color:red'";
                                        }
                                        else if($number_result[$k] == ''){
                                        $number_result[$k] = '--';
                                        $letter_grade = '--';
                                        }
                                        elseif ($number_result[$k] == 0) {
                                            $number_result[$k] = 0;
                                        } else if (empty($grade_value)) {
                                            $number_result[$k] = '--';
                                            $letter_grade = '--';
                                        }
                            ?>

                          

                            <?php  $total_marks_obained += is_numeric($number_result[$k]) ? (int) $number_result[$k] : 0; ?>


                            <?php $marks_obained = is_numeric($number_result[$k]) ? (int) $number_result[$k] : 0; ?>
                            <?php
                            if($course_type_val['count_id'] == 0){
                            $gr_tot+=$marks_obained;
                            }
                            $EvaluationComponentsItems_model = new Application_Model_EvaluationComponentsItems();


                            $comp_weigh = $EvaluationComponentsItems_model->getweightages(0, 0, $item_result[$i]['course_id'], $component_res[$k]);
                            $comp_name = $comp_weigh['component_name'];
                            if(in_array($comp_name,explode(',',$details[0]['component_paper']))
                                    && strtolower($grade_value) != 'ab' 
                                    && strtolower($grade_value) != 'na'
                                    && !empty($grade_value)){
                                $appear_count+=1;
                                                        
                            } 

                            $comp_weightages = $comp_weightages . $comp_weigh['weightage'] . ",";
                            $tot_marks = (int) $comp_weigh['weightage'];
                            $total_divisor += (int) $tot_marks;
                      if($letter_grade == '--'){
                                $letter_grade = '--';
                            }
                            elseif ($tot_marks != 0 && $marks_obained > 0) {
                                
                                $letter_grade = $pass_fail;
                            } 
                            
                            elseif ($tot_marks == 0) {
                                $letter_grade = '--';
                            } elseif ($marks_obained == 0) {
                                $letter_grade = 'F';
                                $pass_fail = 'F';
                                 $pass_fail_final = 'F';
                                  $style="style='color:red'";
                            }
                            ?>
                            <?php if(count($grade_result) == 1 && empty($grade_result[0])){ 
                                $prin_len = 0;
                            for ($o = 0; $o < $prin_len; $o++) { ?>

                            <!--<td>--</td>-->
                          
                            <?php } } ?>
                            
                            <?php
                             if($total_marks_obained == 0){
                                $pass_fail = '--';
                            }
                if (in_array(strtolower($letter_grade),array('f','d'))) {
                    $pass_fail='F';
                     $pass_fail_final = 'F';
                     $style="style='color:red'";
                   
                }
                            ?>
            <?php } 
                        } else{
                            $total_marks_obained = '--';
            for ($o = 0; $o < $prin_len; $o++) { ?>

                            <!--<td>--</td>-->
                            
            <?php 
                
            }      }
            ?>
                           
                          <td <?= $style; ?>><?= $total_marks_obained; ?><?php if($pass_fail_final == 'F' && $total_marks_obained!= '--'){echo '*';} ?>  <?php if(!in_array($ge_id,array(0,34,37,38,14,5,4,30,24,25,32,33))){echo $course['course_code']; } ?></td>

            <?php
            if($item_result[$i]['course_id']){
            // total credit value 
           
            $course_credit_info = $Corecourselearning_model->getCoreCouseDetailByTermAcademicCourse($item_result[$i]['academic_year_id'], $item_result[$i]['term_id'], $item_result[$i]['course_id']);
            //  echo "<pre>";print_r($course_credit_info);exit;
            ?>                  
                        <?php
                        //==========[Add all the credit point of all the coure of student simply]
                         $tot_credit_point += (double) ($course_credit_info['count_id'] == 0 ? $course_credit_info['credit_value'] : 0);
                         $tcp +=(double) ($course_credit_info['count_id'] == 0 ? $course_credit_info['credit_value'] : 0);
                        ?>
                      
                        <!--<td class="no_print"><?= $course_credit_info['count_id'] == 0 ? $course_credit_info['credit_value'] : 0; ?></td>-->
            <?php
            
             
                       
            
            //letter grade
            $total_marks_obained = $total_marks_obained != 0 ? $total_marks_obained : '--';
//$tot_term_masrks
            $original_grade = '';
            $tot_marks = $tot_arr[$course_type_val['ct_id']][array_keys($corce[$course_type_val['ct_id']], $item_result[$i]['course_id'], true)[0]];
            if (!empty($total_divisor)) {
                if($total_marks_obained != '--' ){
                $num = round(((int)$total_marks_obained / $total_divisor) * 100);
                $ref_grade_item = new Application_Model_ReferenceGradeMasterItems();  
                $letter_grade = $ref_grade_item->getRecordByNumGrade($num,$degree_id);
                $original_grade =$letter_grade;
                $letter_grade = strtolower($letter_grade) == 'd'?'F':$letter_grade;
                }
                else {
                    $letter_grade = 'F';
                }
            } else {
                $letter_grade = 'F';
                $pass_fail='F';
                 $pass_fail_final = 'F';
            }
            ?>
                        <?php
                        if (strtolower($letter_grade) == 'f') {
                           
                            $pass_fail = 'F';
                             $pass_fail_final = 'F';   
                        }
                        $pass_fail =  $letter_grade == 'F' ? 'F' : 'P';
            ?> 
            <?php
            //grade point
            $pass_fail = $pass_fail_final;
            
            if($letter_grade == 'F'){
            $sgparem = 'F';}
            if (!is_numeric($letter_grade) && !empty($letter_grade)  ) {
                $ReferenceGradeMaster_model = new Application_Model_ReferenceGradeMaster();
                     $letter_grade = $pass_fail == 'F' ? 'F' : $letter_grade;
                     
                $letter_grade_result = $ReferenceGradeMaster_model->getNumberGradeValue(0, $letter_grade,$degree_id);
                $numeric_grade = $letter_grade_result['number_grade'];
            } else if (is_numeric($letter_grade)) {
                
                $numeric_grade = $letter_grade;
            } $total = $course_credit_info['count_id'] == 0 ? $numeric_grade * $course_credit_info['credit_value'] : 0;
            }
            $credit_arr[$i][] = empty($numeric_grade)?0:$numeric_grade;
            ?>
                        <!--<td class="no_print"><?=empty($numeric_grade)?0:$numeric_grade;?></td>-->
            <?php
            //======[Adding all the grade point of all the core of same student];
            if($course_type_val['count_id'] == 0){
             $tot_term_masrks += $total_marks_obained;
            }
            $total_gradepoint += $total;
            $tgp+=$total;
            $grade_arr[$i][] = $total;
            ?>
                        <!--<td class="no_print"><?php echo number_format($total, 0); ?></td>-->
                         <?php
            if (strtolower($pass_fail) == 'f' ) {
                if(!empty($item_result[$i]['course_id'])){
                    $fail_in[] = $course_type_val['ct_name'];
                    $fail_ct_id[] = $course_type_val['ct_id'];
                     $fcourse_ids[] =   $item_result[$i]['course_id'];
                    
                }
               
            }else if(strtolower($pass_fail) == 'p'){
                    if(!empty($item_result[$i]['course_id']))
                    $pass_in_ct_id[] = $course_type_val['ct_id'];
                    $gp[] = $total;
                }
            ?>
                        <input type='text' style="display:none;"  name="grade[grade_point_<?= $stu_data['student_id'].$item_result[$i]['academic_year_id']; ?>_<?php echo $item_result[$i]['term_id']; ?>_<?php echo $item_result[$i]['course_id']; ?>][]" value="<?php $tot = number_format($total, 2);
            echo $tot;
            ?>" />
                           <?php }
                           if(empty($fail_in)){
                            $sgpa = $tgp / $tcp;
                           }else{
                           $sgpa ='0';
                           } 
                           
                           ?>
                        
                        
                       <?php //==================[Promotion Rules]=====================//
                       
                               $final_remarks = 'P';
                               if($details[0]['credit_score']<=round(number_format($sgpa, 2)*10) 
                                   && $details[0]['semester_paper_count'] <= count(array_unique($pass_in_ct_id))
                                   && $details[0]['appeared_paper'] <= $appear_count){
                                   $term_name = $term_details->getAcademicTermIdAction($item_result[$i]['academic_year_id'],$cmn_term);
                                   $promotion = "Promoted to $term_name";
                               }
                           else {
                                    $final_remarks ='F';
                                    $promotion = "--";
                                }
                       ?>
                        
                        
                    <td rowspan="1" data-datatable-multi-row-rowspan="3" class="group" style="vertical-align:middle;"><?php if($sgparem == 'F' && $count_id == 0){echo '--';}else{ echo $tot_term_masrks; }?></td>    
                      <td rowspan="3" data-datatable-multi-row-rowspan="3" class="group" style="vertical-align:middle;"><?php if($sgparem == 'F' && $count_id == 0){echo '--';}else{ echo number_format($sgpa, 2); }?></td>
                      
                    <!--<td><?=$promotion;?></td>-->
                    <?php if (strtolower($final_remarks) == 'f') {
              
            }?>
        <!--<td><?=implode('/', array_unique($fail_in)); ?></td>-->
         <?php $termDet = new Application_Model_TermMaster();
        
                $year_id = $termDet->getRecord($item_result[$i]['term_id']);
                $term_string = "/term/{$year_id['cmn_terms']}";
                $year_id = $year_id['year_id'];
        ?>
        <!--            <td>  <a class="btn btn-primary" target="_blank" href="<?php echo $this->mainconfig['host'];?>report/secondyeargradesheetreport/id/<?php echo $stu_data['student_id']; ?>/acd_id/<?php echo $item_result[$i]['academic_year_id']; ?>/year/<?php echo $year_id.$term_string; ?>">Download</a></td>-->
        <!--<td>   <a class="btn btn-link" target="_blank"  onclick="window.open('<?php echo $this->mainconfig['host'];?>report/secondyeargradesheetreport/id/<?php echo $stu_data['student_id']; ?>/acd_id/<?php echo $item_result[$i]['academic_year_id']; ?>/year/<?php echo $year_id.$term_string; ?>/mode/view', '_blank', 'toolbar=yes,scrollbars=yes,resizable=yes,top=100,left=100,width=1100,height=800');" href="#">View </a></td>-->
       
        
                      
                        <?php }  $cgpa = number_format($total_gradepoint/$tot_credit,2);   $percent =  number_format(($cgpa*9),2);
                                if($degree_id==3)
                                $percent = number_format(($cgpa*9.25),2);
                                else if($degree_id > 1 ){
                                    $percent = number_format(($cgpa*9.5),2);
                                }
                               
                                 $letter_grade = $ref_grade_item->getRecordByNumGrade1($percent,$degree_id); 
                                 if(!empty($fail_in)){
                                     $sgparem ='F';
                                     $count_id = 0;
                                 }
                                 ?>
                                 
                        <td><?php if($sgparem == 'F' && $count_id == 0){echo '--';}else{ echo $gr_tot;} ?></td>
                      <td rowspan="3" data-datatable-multi-row-rowspan="3"><?php if($sgparem == 'F' && $count_id == 0){echo '--';}else{ echo number_format($total_gradepoint/$tot_credit,2);} ?></td>
                       <td rowspan="3" data-datatable-multi-row-rowspan="3"><?php if($sgparem == 'F' && $count_id == 0){echo '--';}else{ echo $percent.'%'; } ?></td>
                        <td rowspan="3" data-datatable-multi-row-rowspan="3"><?php if($sgparem == 'F' && $count_id == 0){if($degree_id!=3){echo 'Pending';}else{echo 'Pending';}}else{ echo $letter_grade['letter_grade']." (".$letter_grade['des'].")"; } ?></td>
                         <td rowspan="3" data-datatable-multi-row-rowspan="3"><?=implode('/', array_unique($fail_in)); ?></td>
                    </tr> 
                    
                    <tr>
  
                        <?php 
                         $k=0;
                        for ($i = 0; $i < count($item_result); $i++) {
                            
                        foreach($credit_arr[$i] as $credit_key => $cval) {  ?>
                        
                        <?php if($k == 0){?>
                        
                        <td>GRADE POINT</td>
                        <td></td>
                        
                        <?php $k++; } ?>
                       <td class="no_print"><?= $cval ?>
                        <?php } ?>
                        <th></th>
                        <?php }?>
                        <td>--</td>
                    </tr>
                    
                       <tr>
                
                        <?php 
                        $gp_term_total = $k=0;
                        for ($i = 0; $i < count($item_result); $i++) {
                           $gp_term_total = 0;
                        foreach($grade_arr[$i] as $grade_key => $gval) { ?>
                        
                        <?php if($k == 0){?>
                         <td>Credit Point (Cr. X  Grade Point)</td>
                      
                        <td></td>
                        <?php $k++; } ?>
                       <td class="no_print"><?php if($gval == 0){echo "--";}else{echo $gval;} ?>
                        <?php $gp_tot+=$gval; $gp_term_total+=$gval;} ?>
                        <th class="group" style="vertical-align:middle;"><?=$gp_term_total; ?></th>
                        <?php } ?>
                      
                        <td><?php if($sgparem == 'F' && $count_id == 0){echo '--';}else{echo $gp_tot;}?></td>
                        
                    </tr>
                    
        <?php $m++; ?>
       
    <?php }
    ?>	
   
    <tr>
        <th>Core Course</th>
        <th></th>
        <th></th>
         <th></th>
            <?php
            
                       
                        for ($i = 0; $i < count($item_result); $i++) { 
                         $course_type_result = $Corecourselearning_model->getcourseTypeOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);  ?>
                         
                      
                        <th colspan = "<?=count($course_type_result)+2?>"><?php foreach($Corecourselearning_model->getcorecourselearning($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']) as $key =>$res){
                                if($res['ge_id'] == 0){
                            echo "<u>".($key+1)."</u> ".$res['course_code']." : ".$res['course_name']."<br/>";
                        } } ?></th>
                        <?php } ?>
                        <th></th>
        <th></th>
        <th></th>
        <th></th>
   <th></th>
        
    </tr>
      <tr>
        <th>Generic Electives</th>
        <th></th>
        <th></th>
             <th></th>
            <?php
            
                       
                        for ($i = 0; $i < count($item_result); $i++) { 
                         $course_type_result = $Corecourselearning_model->getcourseTypeOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);  ?>
                         
                    
                        <th colspan = "<?=count($course_type_result)+2?>"><?php foreach($Corecourselearning_model->getcorecourselearning($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']) as $key =>$res){
                                if($res['ge_id'] != 0){
                            echo "<u>".($key+1)."</u> ".$res['course_code']." : ".$res['course_name']."<br/>";
                        } } ?></th>
                        <?php } ?>
        <th></th>       
        <th></th>
        <th></th>
        <th></th>
       <th></th>
    </tr>
                </tbody>
                
            </table>
        </div>
        </div>
       
    </div>
    <iframe name="print_frame" width="0" height="0" frameborder="0" src="about:blank"></iframe>
    <div id="addmore_items_<?php echo $i; ?>"></div>
    <br>
    <?php


function selectData($array, $fieldname, $number = 0) {
    try {
        $filterd_value = array();
        if (is_array($array) && is_array($fieldname)) {
            for ($i = 0; $i < $number; $i++) {
                foreach ($fieldname as $field_key => $field_value) {
                    $filterd_value[$i][$field_value] = $array[$i][$field_value];
                }
            }
            return $filterd_value;
        } else {
            throw new Exception('first and second param should be of type array !');
        }
    } catch (Exception $e) {

        echo '<strong>Error Message !</strong>' . $e->getMessage();
    }
}
?>
<!--<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>-->


<script>

    $('table').each(function () {
        var check_val = $(this).find('thead>tr:nth-child(3)>th:nth-child(1)').text();
        if (check_val.toLowerCase() != 'credit') {
            $(this).prev().attr('style', 'display:none');
            $(this).removeAttr('id');
            $(this).attr('style', 'display:none');

        }
    });

    $('<div class="row" id="moved-buttons" style="margin-top:1em; margin-right:.09em;"></div>').appendTo('#datatable-responsive_filter')

    $('div[class="dt-buttons btn-group"]').appendTo('#moved-buttons');
    
   
        let ele = document.querySelectorAll('tbody>tr');
        let x = [];
        let rowgrp = [];
        let i =0;
        let table = '';
     while(i<=(ele.length-1)){
          let y = [];
          table += '<tr>'
         //  console.log(ele[i]); 
        for(j=0;j<ele[i]['cells'].length; j++){
            
            if(ele[i]['cells'][j]['rowSpan'] == 3){
                table += '<td data-datatable-multi-row-rowspan="3">';
                y.push(ele[i]['cells'][j]['innerText']);
              table +=ele[i]['cells'][j]['innerText']+'</td>';
            }
            else{
                table += '<td >';
                y.push(ele[i]['cells'][j]['innerText']);
                 table +=ele[i]['cells'][j]['innerText']+'</td>';
            }
        }
        x[i] = y;
         //console.log(i);
          table += '<script type="x/template" class="extra-row-content">';
        for(k=i+1; k<=i+2;k++){
            let y = [];
            table += '<tr>';
            
             let a = 0;
         for(j=0;j<ele[i]['cells'].length; j++){
            
                if(ele[i]['cells'][j]['rowSpan'] == 3){
                y.push(ele[i]['cells'][j]['innerText']);
                a +=1 ;
                if(i==0)
                rowgrp.push(j);    
                }
            else{
                 
               
                if((j-a) >= 0){
                     table += '<td >';
              y.push(ele[k]['cells'][j-a]['innerText']);
              table +=ele[k]['cells'][j-a]['innerText']+'</td>';
            }
            
            
         }
         inc = k==(i+2)?k+1:i;
         x[k] = y;
      //  console.log(k); 
     }
     table += '</tr>';
  
        }
       
      i = inc;  
         table +='</script';
     table +='>';
      table += '</tr>';
      
     }
     $('tbody').empty();
     $('tbody').html(table);
     console.log(x);




$('.datatable').DataTable({
 "scrollX": true,
            "paging": true,
            "bSort": true,
            "lengthChange":true,
            "sScrollXInner": "100%",
            "lengthMenu": [[50, 100, 500, -1], ["50", "100", "500", "All"]],
            "pageLength":-1,
            dom: 'Blfrtip',
            buttons: [{
                extend:'excelHtml5',
                text: '<b class="btn  btn-xs text-primary"><strong><span class="fa fa-file-excel-o"></span> Excel </strong></b>',
             customize: function (xlsx) {
                var sheet = xlsx.xl.worksheets['sheet1.xml'];
                console.log(sheet);
                var numrows = 5;
                var clR = $('row', sheet);
 let msg = '';
 //======['addng row']===//
                function Addrow(index, data) {
                msg = '<row r="' + index + '">';
                    for (var i = 0; i < data.length; i++) {
                        var key = data[i].key;
                        var value = data[i].value;
                        msg += '<c t="inlineStr" r="' + key + index + '">';
                        msg += '<is>';
                        msg += '<t>' + value + '</t>';
                        msg += '</is>';
                        msg += '</c>';
                    }
                    msg += '</row>';
                    return msg;
                }
                
               //========[generating Excel columns]=========// 
                function getNameFromNumber(num) {
                    
                      for (var ret = '', a = 1, b = 26; (num -= a) >= 0; a = b, b *= 26) {
                        ret = String.fromCharCode(parseInt((num % b) / a) + 65) + ret;
                      }
                      return ret;

                }
                
                
                  let x = [];
     let i =0;
       var r = '';
     while(i<=(ele.length-1)){
          
          
           for(j=0;j<ele[i]['cells'].length; j++){
            
            if(ele[i]['cells'][j]['rowSpan'] == 3){
                
                
                r += Addrow((i+2), [{ key: getNameFromNumber(j+1), value: ele[i]['cells'][j]['innerText']}]);
            
                
            }
            else{
             
              r += Addrow((i+2), [{ key: getNameFromNumber(j+1), value: ele[i]['cells'][j]['innerText']}]);
            }
        }
          
          
          
          for(k=i+1; k<=i+2;k++){
            let y = [];
             let a = 0;
          
               
         for(j=0;j<ele[i]['cells'].length; j++){
            
                if(ele[i]['cells'][j]['rowSpan'] == 3){
                a +=1 ;  
                r += Addrow((k+2), [{ key: getNameFromNumber(j+1), value: ""}]);
               
                }
            else{
               if((j-a) >= 0){  
               r += Addrow((k+2), [{ key: getNameFromNumber(j+1), value: ele[k]['cells'][j-a]['innerText'] }]);
             
               }

         }
         inc = k==(i+2)?k+1:i;
      
     }
        sheet.childNodes[0].childNodes[1].innerHTML = r + sheet.childNodes[0].childNodes[1].innerHTML
        }
       
      i = inc;  
     }
                

 
            }
 
            },{
                extend: 'print',
                            text: '<b  class="btn  btn-xs text-primary" onclick="printDiv()"><strong><span class="fa fa-print"></span> Print </strong></b>', 
                
            },{
                extend: 'copy',
                            text: '<b  class="btn  btn-xs text-primary" ><strong><span class="fa fa-print"></span> copy </strong></b>', 
                
            }],
  "fnDrawCallback": function() {
    $table = $(this);
    // only apply this to specific tables
    if ($table.closest(".datatable-multi-row").length) {
      // for each row in the table body...
      $table.find("tbody>tr").each(function() {
        var $tr = $(this);
        // get the "extra row" content from the <script> tag.
        // note, this could be any DOM object in the row.
        var extra_row = $tr.find(".extra-row-content").html();
        // in case draw() fires multiple times, 
        // we only want to add new rows once.
        if (!$tr.next().hasClass('dt-added')) {
          $tr.after(extra_row);
          $tr.find("td").each(function() {
            // for each cell in the top row,
            // set the "rowspan" according to the data value.
            var $td = $(this);
            var rowspan = parseInt($td.data("datatable-multi-row-rowspan"), 10);
            if (rowspan) {
              $td.attr('rowspan', rowspan);
            }
          });
        }
      });

    } // end if the table has the proper class
  }
});

 var trs = document.querySelectorAll("tr");
for (var sel = 0; sel < trs.length; sel++)
  (function (e) {
    trs[e].addEventListener("click", function () {
      console.log(this);
    }, false);
  })(sel);
  
$('<div class="row" id="moved-buttons" style="margin-top:1em; margin-right:.09em;"></div>').appendTo('#datatable-responsive_filter,#dataTable_filter');
$('div[class="dt-buttons btn-group"]').appendTo('#moved-buttons');
$('select[name="dataTable_length"],select[name="datatable-responsive_length"]').select2();
    
  function printDiv() {
         window.frames["print_frame"].document.body.innerHTML = document.getElementById("printBox").innerHTML;
         window.frames["print_frame"].window.focus();
         window.frames["print_frame"].window.print();
       }
</script>