<style>
    
    #batch{
        display:none;
    }
    
    
    </style>

<div class="right_col">
<div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
 </div>   
<div class="padding-md ">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">Back Tabulation Register</i></div>
		</h3>
			<div class="panel panel-default">
                            
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
					<div class="row">
						<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Batch<span class="asterisk">*</span></label>
                                <?php echo $this->form->academic_year_id; ?>
                            </div>
							</div>
							<?php /* <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Year<span class="asterisk">*</span></label>
                                <?php echo $this->form->year; ?>
                            </div>
							</div>	 */ ?>
						<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Term<span class="asterisk">*</span></label>
                                <?php echo $this->form->term_id; ?>
                            </div>
						</div>
												
					</div>
					<div class="row">
							<div class="col-sm-3">
							<div class="form-group">
							<input type="text" id="batch" class="form-control" style="background-color:#fdf59a;"  readonly /></div>
							</div>
							</div>
					<div class="row">
					<div id="course_grade_details"></div>
					</div>
				
				
 			</div>
			
                                        <div class="panel-footer">									
                                <div class="row">
                                    <div class="col-sm-7 col-sm-offset-5">
                                            <div style="float:left;margin-right:2px;">
                                                                                  <?php
                                                if (in_array($this->role_id, $this->administrator_role)) {
                                                    ?>
                                                    <div style="float:left;">
                                                        <button class="btn btn-primary submit" data-toggle="tooltip" data-placement="top"  onclick="return ConfirmPublish()" id ="update_bt">Update</button>
                                                    </div>
                                                    <?php
                                                }else{ ?>
                                                            <button class="btn btn-danger submit" onclick = "return ConfirmPublish()">Publish</button>
                                                <?php } ?>
                                                            
                                            </div>
                                    </div>
                                </div>
                            </div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->
<script>
    
     function ConfirmPublish()
    {
        var x = confirm("Are you sure you want to Publish?");
        if (x){
            $('.load-box').css('display','block');
            return true;
        }
        else
            return false;
    }
    
   $('body').on('change', '#academic_year_id', function () {
        var academic_id = $('#academic_year_id').val();
        if (academic_id) {
            $('#batch').show();
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch-code'; ?>',
                data: {academic_id: academic_id}
            }).done(function (data) {
                var result = $.parseJSON(data);
                if ((data != '')) {
                    $('#batch').val(result['short_code']);
                }
                else{
                    $('#batch').hide();
                }
                
            });
            
            
               $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms'; ?>',
            data: {academic_year_id: academic_id}
        }).done(function (data) {
            $('#term_id').empty();
            $('#term_id').html(data);
            $('#term_id').trigger("chosen:updated");
            });
            
        }

    });
    
    
    
    $('body').on('change','#term_id',function(){
     var academic_id = $('#academic_year_id').val();
     var term_id = $(this).val();
     //alert(term_id);
     if(term_id)
     $('.load-box').css('display','block');
    if(academic_id && term_id){
       $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-grade-details-tr-back'; ?>',
            data: {academic_year_id: academic_id,term_id:term_id}
        }).done(function (data) {
            
            $('#course_grade_details').empty();
            $('.load-box').css('display','none');
            $('#course_grade_details').html(data);
            $('#course_grade_details').trigger("chosen:updated");
            });
            }
    });
</script>