<style>
.modal-dialog {
    width:850px;
    margin: 30px auto;
}
</style>
<div class="right_col">
    <div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
    <?php if($this->type == "getStudents") { ?>

        <?php

        if (count($this->messages)) {

            foreach ($this->messages as $message) {

                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

            <?php

            }

        }

        ?>

        <!-- widget grid -->

        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> Entrance Exam (Scrutiny Interface) </i>



                        </h3>

                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">



                    </div>

                </div>



                <div class="x_panel">



                    <div class="x_title">

                        <h2 class="title1">Students  Records</h2>

                        <ul class="nav navbar-right panel_toolbox">

                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>

                            </li>

                            <li class="dropdown">

                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                            <li><a class=""><i class="fa fa-close"></i></a>

                            </li>

                        </ul>

                        <div class="clearfix"></div>

                    </div>

                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive">

                           

                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;" rowspan="2">S. No.</th>
                                        <th style="text-align:center;" rowspan="2">Applicant Name</th>
                                       
                                        <th style="text-align:center;" rowspan="2">Roll No</th>
                                       
                                        <th style="text-align:center;" rowspan="2">Form Id</th>

                                        <th style="text-align:center" rowspan="2">Course</th>

                                        <th style="text-align:center" colspan="3">First Preference</th>
                                        <th style="text-align:center" colspan="2">Second Preference</th>

                                        <th style="text-align:center"rowspan="2">Photo</th>
                                        <th style="text-align:center"rowspan="2">Edit Form</th>
                                        <th style="text-align:center"rowspan="2">Doc. Submitted</th>
                                       

                                        <!--<th class="no_print" style="text-align:center">Edit | Delete</th>-->



                                    </tr>
                                    <tr>
                                        <th>Core Course</th>
                                        <th>Generic</th>
                                        <th>Aecc</th>
                                        <th>Core Course</th>
                                        <th>Generic</th>
                                    </tr>
                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
                                            $geinfo = new Application_Model_Ge();
                                            $deptinfo = new Application_Model_Department();
                                            $deptType = new Application_Model_DepartmentType();
                                            $educdet = new Application_Model_ApplicantCourseDetailModel();
                                         
                                         
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {



                                        foreach ($this->paginator as $results) {

                                            //echo '<pre>'; print_r($results);die;

                                            ?>

                                            <tr>

                                                <td><?php

                                                    echo $i;
                                                        $i++;

                                                    ?>

                                                </td>
                                                <td><?php echo $results['applicant_name'];?></td>
                                                    <?php  $edu_details = $educdet->getApplicationCourseDetails($results['form_id']); ?>
                                                <td><?=$results['roll_no1']; ?></td>

                                                <td><?php echo $results['form_id'];?></td>

                                                 <td><?php echo $deptType->getRecord($results['course'])['department_type']; ?></td>
                                                 <td><?php if($edu_details['core_course1']){echo $deptinfo->getRecordbyAcademic($edu_details['core_course1'])['dpt_name'];}else{echo '--';}?></td>
                                                       
                                                <td><?php if($edu_details['ge1']){echo $geinfo->getRecord($edu_details['ge1'])['general_elective_name'];}else echo '--'; ?></td>
                                                 <td><?= !empty($edu_details['aecc1'])?$edu_details['aecc1']:'--'?></td>
                                                <td><?php if($edu_details['core_course2']){echo $deptinfo->getRecordbyAcademic($edu_details['core_course2'])['dpt_name'];}else{echo '--';}?></td>

                                                <td><?php if($edu_details['ge2']){echo $geinfo->getRecord($edu_details['ge2'])['general_elective_name'];}else echo '--'; ?></td>
                                                <!--<td><?= !empty($edu_details['aecc2'])?$edu_details['aecc2']:'--'?></td>-->
                                              <td><img src = "/academic/<?= $results['photo'];?>" width ="70em" alt ='NA'/></td>
                                              <?php if($results['scrutiny_status'] !=1){ ?>
                                              <td><a href="<?php echo $this->mainconfig['host']; ?>multi-step-form/index/type/step4/a_id/<?php echo md5($results['application_no']); ?>"target="_blank" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>
                                              <?php }else {?>
                                              <td>
                                                  <button type="#" class="btn btn-primary" >Scrutiny Completed.</button></td>
                                              </td> 
                                             <?php } ?>

                                              <td class="view_document">
                                                  <input type="hidden" value="<?= $results['application_no']; ?>" id="app_number">
                                                  <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">View Docs.</button></td>
                                            </tr>            

                                            <?php

                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                                </tbody>

                            </table>

    <?php// echo $pagination_tr; ?>

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->
        <!-- Modal -->
            <div class="modal fade" id="myModal" role="dialog">
              <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                 
                    <div class="modal-body" id="resultas">
                       
                  </div>
                  <div class="modal-footer">
                       
                        <button type="button" id="" data-dismiss="modal" class="btn btn-default">Cancel</button>
                        <button type="button" id="cnf_cert" class="btn btn-primary">Save/Update</button>
                  </div>
                </div>

              </div>
            </div>
        <!---End Modal--->
 
</div>
   
<?php } else { ?>

   <?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">
               
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Entrance Exam [Scrutiny Interface]</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>
               
                <?php
                //  }
                ?>
            </div>

            <div class="x_panel">
               
                <div class="x_title">
                    <div class="col-sm-3 employee_class">
                        <div class="form-group disabled" >
                            <label class="control-label">Academic Year<span class="asterisk">*</span></label>
                            <?php echo $this->form->academic_year_list; ?>
                        </div>
                    </div>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                   
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="ajaxData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                                 <caption> <b> <u> Under Graduate Department Wise Report</u></b></caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>
                                    <th>Applied Students</th>  
                                    <th>On-Board Applicants</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                           
                                            
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>entrance-report/scrutiny/type/getStudents/dept_id/<?php echo $results['course']; ?>" target="_blank" class="edit" title="Edit"><button type="button" class="btn btn-info">View Applicants</button></a></td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="5">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                <div class="x_panel">
               
                    
                   

                        <div class="table-responsive" id="">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                                 <caption><b> <u>Post Graduate Department Wise Report</u></b></caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>  
                                    <th>Applied Students</th>   
                                    <th class="no_print">On-Board Applicants</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->pgData) != 0) {
                                    foreach ($this->pgData as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                            </td>
                                           
                                           
                                            <td style="text-align:center">
                                               
                                               
                                          <a class="btn btn-info"  href="<?php echo $this->mainconfig['host']; ?>entrance-report/scrutiny/type/getStudents/dept_id/<?php echo $results['course']; ?>" target="_blank">View Applicants </a>  
                                            </td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="5">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
<?php } ?>
</div>
<script>

//Script for modal

$(".view_document").click(function() {
    let application_no = $(this).closest("td").find("#app_number").val();        
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-get-applicant-info'; ?>',
            data: {application_no:application_no}
        }).done(function (data) {
            //alert(data);
            $('#resultas').html(data);
           });
    //$("#resultas").append(application_no);      
});
$("#cnf_cert").click(function() {
    let docArray = [];
    let form_id = $('.documentTable').find("#form_id").html();
    let app_id = $('.documentTable').find("#app_id").val();
    let course_id = $('.documentTable').find("#course_id").val();
        //alert(app_id);
    $(".documentTable td input[type=checkbox]:checked").each(function () {
        let documents = $(this).val();
        docArray.push(documents);
    });
    //alert(docArray);
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-upsert-documents'; ?>',
        data: {docArray:docArray,form_id:form_id,app_id:app_id,course_id:course_id}
    }).done(function (data) {
        //alert(data);
         $('#alert_msg').text(data);
        //$('#msg').html(data);
       });
    //console.log(docArray);
});

//Added By Kedar : 08 Oct 2020
$('body').on('change', '#academic_year_list', function() {
    let year_id= $('#academic_year_list').val();
    
    if(year_id){
        $('.load-box').css('display','block');
        $.ajax({ 
                type: "POST",
                url:'<?php echo $this->mainconfig['host'].'entrance-report/ajax-get-scrutiny-applicants-by-year-id';?>',
                data: {year_id:year_id}
            }).done(function( data ) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
                $('.load-box').css('display','none');
        });
    }
});
//End : 08 Oct 2020

</script>