<!-- Latest compiled JavaScript -->
<script src="<?php echo $this->mainconfig['publicpath'];?>js/bootstrap/jquerymin1.js"></script>
<script type="text/javascript" src="<?php echo $this->mainconfig['publicpath'];?>js/bootstrap/moment.js"></script>
<script type="text/javascript" src="<?php echo $this->mainconfig['publicpath'];?>js/bootstrap/daterange.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->mainconfig['publicpath'];?>css/daterange.css" />
<style>
    .toDoParrent{
        padding-top:3%;
        background:#ffc10a; min-height:70px;
    }
    .toDoChild{

        color:#fff;

    }
    .toDoChild:hover{
        opacity:0.6;

    }
    .circle{
        padding:40px;

        -webkit-border-radius: 100%;
        -moz-border-radius: 100%;
        border-radius: 100%;
        border:3px solid #fff;

    }

    .toDoRight{
        -webkit-box-shadow: 0px 0px 0px #fff;
        -moz-box-shadow: 0px 0px 0px #fff;
        box-shadow:0px 0px 0px #fff;
        opacity:1;
        background:#9B59B6;
        -webkit-transition: all .5s ease;
        -moz-transition: all .5s ease;
        transition: all .5s ease;
        cursor:pointer;
    }


    .toDoRight:hover{
        opacity:0.6;
    }

    .toDoRight:active{
        opacity:1;
        border-right: 3px solid #000;
    }
    .todoleft:active{
        opacity:1;
        border-right: 3px solid #000;
    }

    .todoleft:hover{
        opacity:0.6;
    }

    .todoleft{
        cursor:pointer;
        -webkit-box-shadow: 0px 0px 0px #fff;
        -moz-box-shadow: 0px 0px 0px #fff;
        box-shadow:0px 0px 0px #fff;
        background:#3498DB;
        min-height:200px;
        opacity:1;
        -webkit-transition: all .5s ease;
        -moz-transition: all .5s ease;
        transition: all .5s ease;
    }

    .btn-align{
        position:absolute;
        bottom:0%;
        right:0%;
    }

    .hide{
        display:none;
    }
    .table-bordered>tbody>tr>td, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>td, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>thead>tr>th {
    position: relative;
   max-width:100%;
white-space:nowrap;
padding:1em;
    border: 1px solid #ddd;
}
.loder_img,.loder_img1,.loder_img3,.loder_img4,.loder_img2{width:4em;}
</style>

<?php //print_r($_SESSION)?>
<!-- page content -->
<div class="right_col" role="main" >
    <!-- top tiles -->
    <div class="row tile_count hide">
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Users</span>
            <div class="count">2500</div>
            <span class="count_bottom"><i class="green">4%</i> From last Week</span>
      //  </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-clock-o"></i> Average Time</span>
            <div class="count">123.50</div>
            <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Male Students</span>
            <div class="count green">2,500</div>
            <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Female Students</span>
            <div class="count">4,567</div>
            <span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>12% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Collections</span>
            <div class="count">2,315</div>
            <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Connections</span>
            <div class="count">7,325</div>
            <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
        </div>
    </div>
    <!-- /top tiles -->

    <div class="row" >
        <div class="col-md-12 col-sm-12 col-xs-12" >
            <div class="dashboard_graph">

                <div class="row x_title" >
                    <div class="col-md-4 pull-left" style="border:0px solid #fff;">
                      <!--  <h3>Report Range <small>&nbsp; on the basis of 'Term' and 'Academic ID' </small></h3>-->
                    </div>
                    <div class='col-md-2 '> <h2 class='green' style='font-weight: 600;' id="batch" class="form-control"></h2></div>
                    <div class="col-md-6">
                        <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 0px solid #ccc">

                            <ul class="list-unstyled list-inline">
                                <li><?= $this->form->academic_year_id; ?></li>
                                <li><?= $this->form->term_id; ?></li>	
                            </ul>			
                        </div>
                    </div>
                </div>



                <div class="clearfix"></div>
            </div>
        </div>

    </div>
    <br />




    <div class="col-md-4 col-sm-4 col-xs-12" >
        <div class="x_panel tile fixed_height_320" style='overflow:scroll;'>
            <div class="x_title">
                <h2>Today's Sessions </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Settings 1</a>
                            </li>
                            <li><a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content text-center">
                <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
                <h4></h4>

                <div class='row'>
                    <div class="col-md-12" id='data'>

                    </div>
                </div>

                <div class="clearfix"></div>
            </div>
           <!-- <a class="btn btn-default btn-align" href='#' id='view_more'>View More</a>-->
        </div>
    </div>









    <div class="col-md-4 col-sm-6 col-xs-12" >
        <div class="x_panel tile fixed_height_320 overflow_hidden">
            <div class="x_title">
                <h2>To Do List</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Settings 1</a>
                            </li>
                            <li><a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>

                <div class="clearfix"></div>
            </div>
            <div class='x_content text-center'>
                <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img2" />
                <div id="piechart_3d" style='width:100%; height:100%;'></div>
                <div class="pull-right">
                    <small></small></div>

            </div>
            <a class='btn btn-default btn-align' href="<?php echo $this->mainconfig['host']; ?>To-do/index/type/add">Create New Task</a>
        </div>
    </div>









    <div class="col-md-4 col-sm-4 col-xs-12" >
        <div class="x_panel tile fixed_height_320 overflow_hidden" style="overflow-x:scroll;">
            <div class="x_title">
                <h2>Sessions:&nbsp;<small id='column_chart_data'></small></h2>
                <div class="clearfix"></div>
            </div>
            <div class='x_content text-center'>
                <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px' class="loder_img" />
                <div id="columnchart_values" ></div>
            </div>
        </div>
    </div>




    <div class="col-md-8 col-sm-8 col-xs-12" >
        <div class="x_panel tile fixed_height_320 overflow_hidden">
            <div class="x_title">
                <h2>Attendance:&nbsp;<small id='column_chart_data'></small></h2>
                <div class="clearfix"></div>
            </div>
            <div class='x_content text-center'>
                <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px' class="loder_img3" />
                <div id="chart_div" style="width: 100%;"></div>
            </div>
        </div>
    </div>


    <div class="col-md-4 col-sm-4 col-xs-12" >
        <div class="x_panel tile fixed_height_320 overflow_hidden">
            <div class="x_title">
                <h2>Course Rating:&nbsp;<small id='column_chart_data'></small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="#"><?= $this->form->course; ?></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content" id='course_rating'>
                <h4></h4>
                <div class="widget_summary">
                    <div class="w_left w_25">
                        <span id="Ratings_c_5"></span>
                    </div>
                    <div class="w_center w_55">
                        <div class="progress">
                            <div class="progress-bar bg-green" id='course_ratinge_5' role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" >
                                <span class="sr-only"><i>0%</i> Complete</span>
                            </div>
                        </div>
                    </div>
                    <div class="w_right w_20"  id='i_no_5'>
                        <span>0</span>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="widget_summary">
                    <div class="w_left w_25">
                        <span id="Ratings_c_4"></span>
                    </div>
                    <div class="w_center w_55">
                        <div class="progress">
                            <div class="progress-bar bg-green" id='course_ratinge_4' role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" >
                                <span class="sr-only"><i>0%</i> Complete</span>
                            </div>
                        </div>
                    </div>
                    <div class="w_right w_20" id='i_no_4'>
                        <span>0</span>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget_summary">
                    <div class="w_left w_25">
                        <span id='Ratings_c_3'></span>
                    </div>
                    <div class="w_center w_55">
                        <div class="progress">
                            <div class="progress-bar bg-green" id='course_ratinge_3' role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" >
                                <span class="sr-only"><i>0%</i> Complete</span>
                            </div>
                        </div>
                    </div>
                    <div class="w_right w_20" id='i_no_3'>
                        <span>0</span>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget_summary">
                    <div class="w_left w_25">
                        <span id='Ratings_c_2'></span>
                    </div>
                    <div class="w_center w_55">
                        <div class="progress">
                            <div class="progress-bar bg-green" role="progressbar" id='course_ratinge_2' aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" >
                                <span class="sr-only"><i>0%</i> Complete</span>
                            </div>
                        </div>
                    </div>
                    <div class="w_right w_20" id='i_no_2'>
                        <span>0</span>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget_summary">
                    <div class="w_left w_25">
                        <span id='Ratings_c_1'></span>
                    </div>
                    <div class="w_center w_55">
                        <div class="progress">
                            <div class="progress-bar bg-green" role="progressbar" id='course_ratinge_1' aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" >
                                <span class="sr-only"><i>0%</i> Complete</span>
                            </div>
                        </div>
                    </div>
                    <div class="w_right w_20" id='i_no_1'>
                        <span>0</span>
                    </div>
                    <div class="clearfix"></div>
                </div>

            </div>
        </div>
    </div>


    <div class="col-md-8 col-sm-8 col-xs-12" >
        <div class="x_panel tile fixed_height_320 overflow_hidden">
            <div class="x_title">
                <h2>Grade After Penalties:&nbsp;<small id='column_chart_data'></small></h2>
                <div class='form-group col-md-2 col-xs-4 pull-right'> <?= $this->form->top; ?> </div>
                <div class="clearfix"></div>
            </div>
            <div class='x_content text-center'>
                <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px' class="loder_img4" />
                <div id="chart_div1" ></div>
            </div>
        </div>
    </div>


    <div class="col-md-4 col-sm-4 col-xs-12" >
        <div class="x_panel tile fixed_height_320 overflow_hidden">
            <div class="x_title">
                <h2>Instructor Rating:&nbsp;<small id='column_chart_data'></small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="#"><?= $this->form->instructor ?></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content" id='instructor_rating'>
                <h4></h4>
                <div class="widget_summary">
                    <div class="w_left w_25">
                        <span id='Ratings_i_5'></span>
                    </div>
                    <div class="w_center w_55">
                        <div class="progress">
                            <div class="progress-bar bg-red" id='instructor_rating_5' role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" >
                                <span class="sr-only">0% Complete</span>
                            </div>
                        </div>
                    </div>
                    <div class="w_right w_20" id='c_no_5'>
                        <span>0</span>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="widget_summary">
                    <div class="w_left w_25">
                        <span id='Ratings_i_4'></span>
                    </div>
                    <div class="w_center w_55">
                        <div class="progress">
                            <div class="progress-bar bg-red" id='instructor_rating_4'  role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" >
                                <span class="sr-only"><i>0%</i> Complete</span>
                            </div>
                        </div>
                    </div>
                    <div class="w_right w_20"  id='c_no_4'>
                        <span>0</span>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget_summary">
                    <div class="w_left w_25">
                        <span id='Rating_i_3'></span>
                    </div>
                    <div class="w_center w_55">
                        <div class="progress">
                            <div class="progress-bar bg-red" id='instructor_rating_3' role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">
                                <span class="sr-only"><i>0%</i> Complete</span>
                            </div>
                        </div>
                    </div>
                    <div class="w_right w_20"  id='c_no_3'>
                        <span>0</span>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget_summary">
                    <div class="w_left w_25">
                        <span id='Ratings_i_2'></span>
                    </div>
                    <div class="w_center w_55">
                        <div class="progress">
                            <div class="progress-bar bg-red" id='instructor_rating_2' role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" >
                                <span class="sr-only"><i>0%</i> Complete</span>
                            </div>
                        </div>
                    </div>
                    <div class="w_right w_20"  id='c_no_2'>
                        <span>0</span>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget_summary">
                    <div class="w_left w_25">
                        <span id='Ratings_i_1'></span>
                    </div>
                    <div class="w_center w_55">
                        <div class="progress">
                            <div class="progress-bar bg-red" id='instructor_rating_1' role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" >
                                <span class="sr-only"><i>0%</i> Complete</span>
                            </div>
                        </div>
                    </div>
                    <div class="w_right w_20"  id='c_no_1'>
                        <span>0</span>
                    </div>
                    <div class="clearfix"></div>
                </div>

            </div>
        </div>
    </div>
    
    
     <!--<div class="col-md-12 col-sm-12 col-xs-12" >
        <div class="x_panel tile fixed_height_320 overflow_hidden">
            <div class="x_title">
                <h2>Attendance:&nbsp;<small id='column_chart_data'></small></h2>
                <div class="clearfix"></div>
            </div>
            <div class='x_content text-center'>
                <img src="<?php //echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px' class="loder_img3" />
                <div id="barchart_material" ></div>
            </div>
        </div>
    </div>-->
    
     


    <div class="col-md-4 col-sm-4 col-xs-12" style="display:none;">
        <div class="x_panel tile fixed_height_320">
            <div class="x_title">
                <h2>Quick Settings</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Settings 1</a>
                            </li>
                            <li><a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="dashboard-widget-content">
                    <ul class="quick-list">
                        <li><i class="fa fa-calendar-o"></i><a href="#">Settings</a>
                        </li>
                        <li><i class="fa fa-bars"></i><a href="#">Subscription</a>
                        </li>
                        <li><i class="fa fa-bar-chart"></i><a href="#">Auto Renewal</a> </li>
                        <li><i class="fa fa-line-chart"></i><a href="#">Achievements</a>
                        </li>
                        <li><i class="fa fa-bar-chart"></i><a href="#">Auto Renewal</a> </li>
                        <li><i class="fa fa-line-chart"></i><a href="#">Achievements</a>
                        </li>
                        <li><i class="fa fa-area-chart"></i><a href="#">Logout</a>
                        </li>
                    </ul>


                </div>
            </div>
        </div>
    </div>

</div>


<div class="row" style="display:none;">
    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Recent Activities <small>Sessions</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Settings 1</a>
                            </li>
                            <li><a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="dashboard-widget-content">

                    <ul class="list-unstyled timeline widget">
                        <li>
                            <div class="block">
                                <div class="block_content">
                                    <h2 class="title">
                                        <a>ANNOUNCEMENT</a>
                                    </h2>
                                    <!-- <div class="byline">
                                      <span>13 hours ago</span> by <a>Jane Smith</a>
                                    </div> -->
                                    <p class="excerpt"><a href="http://www.dmi.ac.in/content/career" target="_blank">Recruitment Notification for Programme Associate for CEPs</a></br><a href="http://dmi.ac.in/symposia/third-symposium" target="_blank">Third Foundation Day Symposium</a> </br><a href="http://www.dmi.ac.in/announcements/shortlisted-candidates-faculty-selection-process" target="_blank">Shortlisted Candidates for Faculty Selection Process</a></br><a href="http://www.dmi.ac.in/announcements/admissions-notification-pdm-2017-19" target="_blank">Admissions Notification for PDM (2017 - 19)</a></br><a href="http://www.dmi.ac.in/announcement" target="_blank">Read&nbsp;More</a>
                                    </p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="block">
                                <div class="block_content">
                                    <h2 class="title">
                                        <a>DMI IN MEDIA</a>
                                    </h2>
                                    <!--<div class="byline">
                                      <span>13 hours ago</span> by <a>Jane Smith</a>
                                    </div>-->
                                    <p class="excerpt"><a href="http://www.dmi.ac.in/lat/press-clipings" target="_blank">Press Clipings</a></br><a href="http://www.dmi.ac.in/lat/dmi-times-now" target="_blank">DMI in Times Now</a></br><a href="http://www.dmi.ac.in/lat/news-about-dmi-foundation" target="_blank">News about DMI Foundation</a></br><a href="http://www.dmi.ac.in/lat/news-coverage-rural-development-department" target="_blank">News coverage Rural Development Department</a></br> <a href="http://www.dmi.ac.in/news-and-events" target="_blank">Read&nbsp;More</a>
                                    </p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="block">
                                <div class="block_content">
                                    <h2 class="title">
                                        <a>REPOSITORY</a>
                                    </h2>
                                    <!-- <div class="byline">
                                      <span>13 hours ago</span> by <a>Jane Smith</a>
                                    </div> -->
                                    <p class="excerpt"><a href="http://www.dmi.ac.in/repo/first-foundation-day-symposium-development-management-pathways-towards-good-society" target="_blank">First Foundation Day Symposium on Development Management Pathways towards Good Society</a>
                                    </p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="block">
                                <div class="block_content">
                                    <h2 class="title">
                                        <a>ACADEMIC PROGRAMME</a>
                                    </h2>
                                    <!-- <div class="byline">
                                      <span>13 hours ago</span> by <a>Jane Smith</a>
                                    </div> -->
                                    <p class="excerpt"><a href="http://www.dmi.ac.in/pdm/admissions" target="_blank">Admissions 2017-19</a>
                                    </p>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div class="col-md-8 col-sm-8 col-xs-12">



        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Visitors location <small>geo-presentation</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Settings 1</a>
                                    </li>
                                    <li><a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="dashboard-widget-content">
                            <div class="col-md-4 hidden-small">
                                <h2 class="line_30">125.7k Views from 60 countries</h2>

                                <table class="countries_list">
                                    <tbody>
                                        <tr>
                                            <td>United States</td>
                                            <td class="fs15 fw700 text-right">33%</td>
                                        </tr>
                                        <tr>
                                            <td>France</td>
                                            <td class="fs15 fw700 text-right">27%</td>
                                        </tr>
                                        <tr>
                                            <td>Germany</td>
                                            <td class="fs15 fw700 text-right">16%</td>
                                        </tr>
                                        <tr>
                                            <td>Spain</td>
                                            <td class="fs15 fw700 text-right">11%</td>
                                        </tr>
                                        <tr>
                                            <td>Britain</td>
                                            <td class="fs15 fw700 text-right">10%</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div id="world-map-gdp" class="col-md-8 col-sm-12 col-xs-12" style="height:230px;"></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">


            <!-- Start to do list -->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>To Do List <small>Sample tasks</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Settings 1</a>
                                    </li>
                                    <li><a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="">
                            <ul class="to_do">
                                <li>
                                    <p>
                                        <input type="checkbox" class="flat"> Schedule meeting with new client </p>
                                </li>
                                <li>
                                    <p>
                                        <input type="checkbox" class="flat"> Create email address for new intern</p>
                                </li>
                                <li>
                                    <p>
                                        <input type="checkbox" class="flat"> Have IT fix the network printer</p>
                                </li>
                                <li>
                                    <p>
                                        <input type="checkbox" class="flat"> Copy backups to offsite location</p>
                                </li>
                                <li>
                                    <p>
                                        <input type="checkbox" class="flat"> Food truck fixie locavors mcsweeney</p>
                                </li>
                                <li>
                                    <p>
                                        <input type="checkbox" class="flat"> Food truck fixie locavors mcsweeney</p>
                                </li>
                                <li>
                                    <p>
                                        <input type="checkbox" class="flat"> Create email address for new intern</p>
                                </li>
                                <li>
                                    <p>
                                        <input type="checkbox" class="flat"> Have IT fix the network printer</p>
                                </li>
                                <li>
                                    <p>
                                        <input type="checkbox" class="flat"> Copy backups to offsite location</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>



            <!-- End to do list -->

            <!-- start of weather widget -->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Daily active users <small>Sessions</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Settings 1</a>
                                    </li>
                                    <li><a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="temperature"><b>Monday</b>, 07:30 AM
                                    <span>F</span>
                                    <span><b>C</b></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="weather-icon">
                                    <canvas height="84" width="84" id="partly-cloudy-day"></canvas>
                                </div>
                            </div>
                            <div class="col-sm-8">
                                <div class="weather-text">
                                    <h2>Texas <br><i>Partly Cloudy Day</i></h2>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="weather-text pull-right">
                                <h3 class="degrees">23</h3>
                            </div>
                        </div>

                        <div class="clearfix"></div>

                        <div class="row weather-days">
                            <div class="col-sm-2">
                                <div class="daily-weather">
                                    <h2 class="day">Mon</h2>
                                    <h3 class="degrees">25</h3>
                                    <canvas id="clear-day" width="32" height="32"></canvas>
                                    <h5>15 <i>km/h</i></h5>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="daily-weather">
                                    <h2 class="day">Tue</h2>
                                    <h3 class="degrees">25</h3>
                                    <canvas height="32" width="32" id="rain"></canvas>
                                    <h5>12 <i>km/h</i></h5>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="daily-weather">
                                    <h2 class="day">Wed</h2>
                                    <h3 class="degrees">27</h3>
                                    <canvas height="32" width="32" id="snow"></canvas>
                                    <h5>14 <i>km/h</i></h5>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="daily-weather">
                                    <h2 class="day">Thu</h2>
                                    <h3 class="degrees">28</h3>
                                    <canvas height="32" width="32" id="sleet"></canvas>
                                    <h5>15 <i>km/h</i></h5>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="daily-weather">
                                    <h2 class="day">Fri</h2>
                                    <h3 class="degrees">28</h3>
                                    <canvas height="32" width="32" id="wind"></canvas>
                                    <h5>11 <i>km/h</i></h5>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="daily-weather">
                                    <h2 class="day">Sat</h2>
                                    <h3 class="degrees">26</h3>
                                    <canvas height="32" width="32" id="cloudy"></canvas>
                                    <h5>10 <i>km/h</i></h5>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- end of weather widget -->
        </div>
    </div>
</div>
</div>
<!-- /page content -->

<!-- Flot -->

<!-- /Flot -->

<!-- JQVMap -->

<!-- /JQVMap -->


<!-- /Skycons -->


<!-- /Doughnut Chart -->
<!-- gauge.js -->




<style>
    a:hover{
        color:#9b131f;
        text-decoration:underline;
    }
</style>


<script src="<?php echo $this->mainconfig['publicpath'];?>js/jquerymin.js"></script>

<!-- Latest compiled JavaScript -->
<script src="<?php echo $this->mainconfig['publicpath'];?>js/bootstrap.js"></script>

<script>
    
    $('#batch').hide();
//get-terms
    $("#academic_year_id").change(function () {
        var academic_id = $('#academic_year_id').val();
        if (academic_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms-default'; ?>',
                data: {academic_year_id: academic_id}
            }).done(function (data) {
                //alert(data);
                $('#term_id').empty('');
                $('#term_id').html(data);
            })
        }
    });

//==============[GET LATEST TERM AND BATCH ACCORDING TO CURRENTDATE]==========//

   /* $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-recent-term-and-batch'; ?>',
        data: {my_date: '<?= date('d-m-Y'); ?>'}
    }).done(function (data) {
        json_obj = JSON.parse(data);
        $('#academic_year_id').val(json_obj.batch_id);
        var academic = json_obj.batch_id;
        if (academic) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms-default'; ?>',
                data: {academic_year_id: academic}
            }).done(function (data) {
                //alert(data);
                $('#term_id').empty('');
                $('#term_id').html(data);
                $('#term_id').val(json_obj.term_id);
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-course'; ?>',
                    data: {academic_year_id: academic, term_id: json_obj.term_id}

                }).done(function (data) {
                    $('#course').after('<input style="display:none" type="text" name="batch" value = "' + academic + '"/>')
                    $('#course').after('<input type="text" style="display:none"  name="term" value="' + json_obj.term_id + '"/>')
                    $('#course').empty();
                    $('#course').html(data);



                    $.ajax({
                        type: "POST",
                        url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-faculty'; ?>',
                        data: {academic_year_id: academic, term_id: json_obj.term_id, course_id: $('#course').val()}
                    }).done(function (data) {
                        $('#instructor').empty();
                        $('#instructor').html(data);
                        setCourseRatings();
                        setInstructorRatings();

                    });



                });


            });
        }
    });*/


    var getCourseAndFaculty = () => {
        academic = $('#academic_year_id').val();
        term_id = $('#term_id').val();
        if (academic) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-course'; ?>',
                data: {academic_year_id: academic, term_id: term_id}

            }).done(function (data) {
                $('#course').after('<input style="display:none" type="text" name="batch" value = "' + academic + '"/>')
                $('#course').after('<input type="text" style="display:none"  name="term" value="' + term_id + '"/>')
                $('#course').empty();
                $('#course').html(data);



                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-faculty'; ?>',
                    data: {academic_year_id: academic, term_id: term_id, course_id: $('#course').val()}
                }).done(function (data) {
                    $('#instructor').empty();
                    $('#instructor').html(data);
                    setCourseRatings();
                    setInstructorRatings();

                });
            });
        }
    }



</script>
<script>

    //==========[GETTING COURSE RATINGS]=================//



    var setCourseRatings = () => {
        academic = $('#academic_year_id').val();
        term_id = $('#term_id').val();
        if (academic_year_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-faculty'; ?>',
                data: {academic_year_id: academic, term_id: term_id, course_id: $('#course').val()}
            }).done(function (data) {
                $('#instructor').empty();
                $('#instructor').html(data);

                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-rating'; ?>',
                    data: {academic_year_id: academic, term_id: term_id, course_id: $('#course').val(), instructor_id: $('#instructor').val()}
                }).done(function (data) {
                    json_obj = JSON.parse(data);
                    $('#course_ratinge_5').css('width', json_obj.rating_five_percent);
                    $('#course_ratinge_4').css('width', json_obj.rating_four_percent);
                    $('#course_ratinge_3').css('width', json_obj.rating_three_percent);
                    $('#course_ratinge_2').css('width', json_obj.rating_two_percent);
                    $('#course_ratinge_1').css('width', json_obj.rating_one_percent);

                    $('#course_ratinge_5>span>i').text(json_obj.rating_five_percent);
                    $('#course_ratinge_4>span>i').text(json_obj.rating_four_percent);
                    $('#course_ratinge_3>span>i').text(json_obj.rating_three_percent);
                    $('#course_ratinge_2>span>i').text(json_obj.rating_two_percent);
                    $('#course_ratinge_1>span>i').text(json_obj.rating_one_percent);
                    
                     $('#Ratings_c_5').text(json_obj.rating_five_label);
                    $('#Ratings_c_4').text(json_obj.rating_four_label);
                    $('#Ratings_c_3').text(json_obj.rating_three_label);
                    $('#Ratings_c_2').text(json_obj.rating_two_label);
                    $('#Ratings_c_1').text(json_obj.rating_one_label);
                    
                    $('#i_no_5>span').text(json_obj.rating_five_no);
                    $('#i_no_4>span').text(json_obj.rating_four_no);
                    $('#i_no_3>span').text(json_obj.rating_three_no);
                    $('#i_no_2>span').text(json_obj.rating_two_no);
                    $('#i_no_1>span').text(json_obj.rating_one_no);

                });
            });
        }

    }



    $('#course').change(function () {
        setCourseRatings();
        setInstructorRatings();
    });

</script>

<script>

    //==========[GETTING RATINGS OF INSTRUCTOR]=================//

    var setInstructorRatings = () => {
        academic = $('#academic_year_id').val();
        term_id = $('#term_id').val();
        if (academic) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-rating-instructor'; ?>',
                data: {academic_year_id: academic, term_id: term_id, course_id: $('#course').val(), instructor_id: $('#instructor').val()}
            }).done(function (data) {
                json_obj = JSON.parse(data);
                $('#instructor_rating_5').css('width', json_obj.rating_five_percent);
                $('#instructor_rating_4').css('width', json_obj.rating_four_percent);
                $('#instructor_rating_3').css('width', json_obj.rating_three_percent);
                $('#instructor_rating_2').css('width', json_obj.rating_two_percent);
                $('#instructor_rating_1').css('width', json_obj.rating_one_percent);

                $('#instructor_rating_5>span>i').text(json_obj.rating_five_percent);
                $('#instructor_rating_4>span>i').text(json_obj.rating_four_percent);
                $('#instructor_rating_3>span>i').text(json_obj.rating_three_percent);
                $('#instructor_rating_2>span>i').text(json_obj.rating_two_percent);
                $('#instructor_rating_1>span>i').text(json_obj.rating_one_percent);
                
                  $('#Ratings_i_5').text(json_obj.rating_five_label);
                    $('#Ratings_i_4').text(json_obj.rating_four_label);
                    $('#Rating_i_3').text(json_obj.rating_three_label);
                    $('#Ratings_i_2').text(json_obj.rating_two_label);
                    $('#Ratings_i_1').text(json_obj.rating_one_label);

                $('#c_no_5>span').text(json_obj.rating_five_no);
                $('#c_no_4>span').text(json_obj.rating_four_no);
                $('#c_no_3>span').text(json_obj.rating_three_no);
                $('#c_no_2>span').text(json_obj.rating_two_no);
                $('#c_no_1>span').text(json_obj.rating_one_no);

            });
        }

    }

    $('#instructor').change(function () {
//setCourseRatings();
        setInstructorRatings();
        
          getCourse();
    });



</script>


<!--=============[TODAY'S CLASS]============-->
<script>
    var myClass = () => {

        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'index/get-course'; ?>',
            data: {start_date: '<?php echo date('d-m-Y'); ?>', term_id: $('#term_id').val()}
        }).done(function (data) {
            //alert(data);
            $('.loder_img1').css("display", "none");
            $('#data').html(data);
        })

        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'index/get-view-url'; ?>',
            data: {start_date: '<?php echo date('d-m-Y'); ?>', term_id: $('#term_id').val()}
        }).done(function (data) {
            $('#view_more').attr('href', data);

        })
    }


    /*$(function() {
     $('input[name="daterange"]').daterangepicker({
     opens: 'left'
     }, function(start, end, label) {
     $.ajax({
     type: "POST",
     url: '<?php //echo $this->mainconfig['host'] . 'index/get-course';           ?>',
     data: {start_date: start.format('DD/MM/YYYY'),
     end_date:   end.format('DD/MM/YYYY')  }
     }).done(function (data){
     $('#data').html(data);
     
     })
     });
     });*/
    $(function(){
        myClass();
    });
    
</script>
<script src='<?php echo $this->mainconfig['publicpath'];?>js/google.js'></script>	

<!--<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>-->

<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<!--=============TODO LIST CHART===========-->

<script type="text/javascript">
    google.load("visualization", "1", {packages: ["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
        //alert('Smita');
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-todo-list-report'; ?>',
            data: {empl_id: '<?=!empty($this->login_storage->empl_id)?$this->login_storage->empl_id:'';?>'}
    
        }).done(function (data) {
            
            data = JSON.parse(data);
            //alert(data);
            $('.loder_img2').css("display", "none");
            $('#no_started_no_display').text(data.not_started_in_no);

            $('#inprogress_no_display').text(data.in_progress_in_no);

            var data = google.visualization.arrayToDataTable([
                ['Task', 'link', 'Hours per Day'],
                ['Completed', '<?php echo $this->mainconfig['host']; ?>To-do/index/type/comp', data.completed_in_no],
                ['In Progress', '<?php echo $this->mainconfig['host']; ?>To-do/index/type/in', data.in_progress_in_no],
                ['Not Started', '<?php echo $this->mainconfig['host']; ?>To-do/index/', data.not_started_in_no]

            ]);
            //alert(data);
            var view = new google.visualization.DataView(data);
            view.setColumns([0, 2]);

            var options = {

                title: '',
                is3D: true,
                'legend': 'top'
            };

            var chart = new google.visualization.PieChart(
                    document.getElementById('piechart_3d'));
            chart.draw(view, options);

            var selectHandler = function (e) {
                window.location = data.getValue(chart.getSelection()[0]['row'], 1);
            }
            myClass();
            getAll();
            getSessions();
            // Add our selection handler.
            google.visualization.events.addListener(chart, 'select', selectHandler);
            $('#top').val('3');
        });


    }
</script>

<!--=========[ATTENDANCE SESSIONS CHART]===========-->

<script type="text/javascript">
    google.charts.load('current', {'packages': ['corechart']});
    google.charts.setOnLoadCallback(drawVisualization);

    function drawVisualization(json_obj) {
        $('#top').val('3');

        var course_details = [];

        var second_arr = [["Course", "Faculty", 'Visiting Faculty', 'Course H.O.D']];
        var course_count = [];


        for (x in json_obj.faculty_sessions)
        {

            if (x != 'course_count') {
                if (json_obj.faculty_sessions[x].course_name) {
                    var one_arr = [];
                    one_arr.push(json_obj.faculty_sessions[x].course_name);
                    one_arr.push(json_obj.faculty_sessions[x].DMI_Faculty);
                    one_arr.push(json_obj.faculty_sessions[x].Visiting_Faculty);
                    one_arr.push(json_obj.faculty_sessions[x].course_coodinator);
                    second_arr.push(one_arr);
                }
            }
        }

        $('.loder_img3').css("display", "none");

        // Some raw data (not necessarily accurate)
        var data = google.visualization.arrayToDataTable(second_arr);



        var options = {
            title: '',
            vAxis: {title: 'Classes'},

            seriesType: 'bars',
            series: {5: {type: 'line'}},
            'legend': 'top'
        };

        var chart = new google.visualization.ComboChart(document.getElementById('chart_div'));
        chart.draw(data, options);
        $('#chart_div > div >div > span').removeAttr('style');
        $('#chart_div > div >div > span').empty();
        $('#chart_div > div >div > span').html("<div class='text-center'><p style='font-size:14px; '><b>No Record Found</p></h4></div>");

    }
</script>

<!--=========[SUBJECTS SESSIONS CHART]===========-->

<script type="text/javascript">
    var i =0;
    google.charts.load("current", {packages: ['corechart']});
    google.charts.setOnLoadCallback(drawChart);
    function drawChart(json_obj) {
        $('#top').val('3');



        var course_details = [];

        var second_arr = [["Element", "Density", {role: "style"}]];
        var course_count = [];


        for (x in json_obj)
        {
            var seq = getRandomColor();
            if (json_obj[x].course_code) {
                var one_arr = [];
                one_arr.push(json_obj[x].course_code);
                if (json_obj[x].course_count != null) {

                    one_arr.push(json_obj[x].course_count);
                    one_arr.push(seq);

                } 
                second_arr.push(one_arr);
               
            }
        }
        var data = google.visualization.arrayToDataTable(second_arr);
        var view = new google.visualization.DataView(data);
        view.setColumns([0, 1,
            {calc: "stringify",
                sourceColumn: 1,
                type: "string",
                role: "annotation"},
            2]);

        var options = {
            title: "",
            width: "500",
            bar: {groupWidth: "100%"},
            legend: {position: "none"},
        };
        var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));

        chart.draw(view, options);
   
    
        $('#columnchart_values > div >div > span').removeAttr('style');
        $('#columnchart_values > div >div > span').empty();
        $('#columnchart_values > div >div > span').html("<div class='text-center'><p style='font-size:14px; '><b>No Record Found</p></h4></div>");

    }




    //=======[TRIGGER ON CHANGE ON THE BASIS OF TERM_ID]=====//
    $('#term_id').change(function () {
        $('#columnchart_values > div >div > span').removeAttr('style');
        $('#columnchart_values > div >div > span').empty();

        $('#chart_div > div >div > span').removeAttr('style');
        $('#chart_div > div >div > span').empty();


        $('#chart_div1 > div >div > span').removeAttr('style');
        $('#chart_div1 > div >div > span').empty();
        $('.loder_img').css("display", "initial");
        $('.loder_img3').css("display", "initial");
        $('.loder_img4').css("display", "initial");
        myClass();
        getCourseAndFaculty();
        setCourseRatings();
        setInstructorRatings();
        getAll();
        getSessions();
    });
//=======[TRIGGER ON CHANGE ON THE BASIS OF BATCH_ID]=====//
    $('#academic_year_id').change(function () {
        $('#columnchart_values > div >div > span').removeAttr('style');
        $('#columnchart_values > div >div > span').empty();

        $('#chart_div > div >div > span').removeAttr('style');
        $('#chart_div > div >div > span').empty();

        $('#chart_div1 > div >div > span').removeAttr('style');
        $('#chart_div1 > div >div > span').empty();

        $('.loder_img').css("display", "initial");
        $('.loder_img3').css("display", "initial");
        $('.loder_img4').css("display", "initial");
        setCourseRatings();
        setInstructorRatings();
        getAll();
        getSessions();
    });

    //======[GET RANDOM COLOR]=======// 
    function getRandomColor() {
        var letters = '0123456789ABCDEF';
        var color = '#';
        for (var i = 0; i < 6; i++) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
    }




</script>


<script type="text/javascript">
    google.charts.load('current', {'packages': ['corechart']});
    google.charts.setOnLoadCallback(drawChart1);

    function drawChart1(json_obj) {

        var course_details = [];
        var second_arr = [["Course", "Heighest Grade", 'Second Heighest Grade', 'Third Heighest Grade']];

        for (x in json_obj.student_penalties)
        {
            if (x != 'course_count') {
                if (json_obj.student_penalties[x].top.length == 1)
                    var second_arr = [["Course", "Heighest Grade"]];
                if (json_obj.student_penalties[x].top.length == 2)
                    var second_arr = [["Course", "Heighest Grade", 'Second Heighest Grade']];
                if (json_obj.student_penalties[x].top.length == 3)
                    var second_arr = [["Course", "Heighest Grade", 'Second Heighest Grade', 'Third Heighest Grade']];
                if (json_obj.student_penalties[x].top.length == 4)
                    var second_arr = [["Course", "Heighest Grade", 'Second Heighest Grade', 'Third Heighest Grade', 'Fourth Heighest Grade']];
                if (json_obj.student_penalties[x].top.length == 5)
                    var second_arr = [["Course", "Heighest Grade", 'Second Heighest Grade', 'Third Heighest Grade', 'Fourth Heighest Grade', 'Fifth Heighest Grade']];
                break;
            }
        }

        var course_count = [];


        for (x in json_obj.student_penalties)
        {
            if (x != 'course_count') {
                if (json_obj.student_penalties[x].course_name) {
                    var one_arr = [];
                    one_arr.push(json_obj.student_penalties[x].course_name);
                    for (y in json_obj.student_penalties[x].top) {
                        one_arr.push(json_obj.student_penalties[x].top[y]);
                    }
                    second_arr.push(one_arr);
                }
            }
        }

        var data = google.visualization.arrayToDataTable(second_arr
                );

        var options = {
            title: '',
            vAxis: {title: 'Grade Range'},

            seriesType: 'bars',
            series: {5: {type: 'line'}},
            'legend': 'top'
        };

        var chart = new google.visualization.ComboChart(document.getElementById('chart_div1'));
        $('.loder_img4').css('display', 'none');
        chart.draw(data, options);
        $('#chart_div1 > div >div > span').removeAttr('style');
        $('#chart_div1 > div >div > span').empty();
        $('#chart_div1 > div >div > span').html("<div class='text-center'><p style='font-size:14px; '><b>No Record Found</p></h4></div>");

    }



    $('#top').change(function () {

        $('#chart_div1 > div >div > span').removeAttr('style');
        $('#chart_div1 > div >div > span').empty();
        $('.loder_img4').css("display", "initial");
        getChartOnly();
    });
</script>

<!---==============[GLOBAL FUNCTION]========---->  

<script>

    function getAll() {
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-batch-scedule-sessions'; ?>',
            data: {term_id: $('#term_id').val(), batch_id: $('#academic_year_id').val(), top_id: $('#top').val()}
        }).done(function (data) {
            var json_obj = JSON.parse(data);
            drawVisualization(json_obj);
            drawChart1(json_obj);
        });
    }


    function getSessions() {
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-batch-scedule-sessions1'; ?>',
            data: {term_id: $('#term_id').val(), batch_id: $('#academic_year_id').val(), top_id: $('#top').val()}
        }).done(function (data) {
            //alert(data);
            var json_obj = JSON.parse(data);
            $('.loder_img').css("display", "none");
            drawChart(json_obj);
        });
    }


    function getChartOnly() {
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-batch-scedule-sessions'; ?>',
            data: {term_id: $('#term_id').val(), batch_id: $('#academic_year_id').val(), top_id: $('#top').val()}
        }).done(function (data) {
            var json_obj = JSON.parse(data);
            drawChart1(json_obj);
        });
    }
    
    function getCourse(){
        
            drawChart2();
    }



</script>


<!--====================[]======================---->
 <script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawChart2);
      
      function drawChart2() {
         
         
          one_arr = [];
      second_arr = [];
      question_obj ='';
      temp_data = ['Questions'];
      main_data =[];
	  
	   $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-question'; ?>',
            data: {term_id: $('#term_id').val(), 
                   batch_id: $('#academic_year_id').val(), 
                   top_id: $('#top').val(),
                   empl: $('#instructor').val(),
                   course:$('#course').val()
        }
        
        
        /*
         * 
         * {calc: "stringify",
                sourceColumn: 1,
                type: "string",
                role: "annotation"},
            2])
         * 
         */
        }).done(function (data) {
             question_obj = JSON.parse(data);
            for(x in question_obj.feed){  
                            temp_data.push(x);
                         }
                         temp_data.push({role: 'annotation'});
                         main_data.push(temp_data);
                         
                         
                         for(x in question_obj.question_array){
                                main_data.push(question_obj.question_array[x]);
                                    }
          var data = google.visualization.arrayToDataTable(main_data);
      var options = {
        
        legend: { position: 'top', maxLines: main_data.length},
        bar: { groupWidth: '70%' },
        isStacked: true
     
      };
            var chart = new google.charts.Bar(document.getElementById('barchart_material'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
        
        });
         
      }
    //To get academic year by login id:
    /*$(function(){
        var employee_id='<?=!empty($this->login_storage->empl_id)?$this->login_storage->empl_id:'';?>';
        $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'index/ajax-get-academic-with-empl'; ?>',
                data: {employee_id : employee_id}
            }).done(function (data) {
                $('#academic_year_id').empty('');
                $('#academic_year_id').html(data).trigger("chosen:updated");
            });
    });*/
     
    </script>






