paymode ==='A'<style>
 
* {margin: 0; padding: 0;}

.aecc{
    float:right;
}

body {
	font-family: montserrat, arial, verdana;
}
.multistepformArea{
    padding-top: 1px;
    background-color: white;
	width: 60%;
    min-width: 300px;
	margin: 50px auto;
	position: relative;
}
/*form styles*/
.regForm {
    width: 90%;
    min-width: 300px;
	margin: 50px auto;
	position: relative;
}
#formValidate1 fieldset {
	background: white;
	border: 0 none;
	border-radius: 3px;
	box-shadow: 0 0 1px 1px rgba(0, 0, 0, 0.1);
	box-sizing: border-box;
	position: relative;
}

/*buttons*/
#formValidate1 .action-button {
    float:right;
	width: 100px;
	background: #27AE60;
	font-weight: bold;
	color: white;
	border: 0 none;
	border-radius: 1px;
	cursor: pointer;
	padding: 10px 5px;
	margin: 10px 5px;
}
#formValidate1 .action-button:hover, #formValidate1 .action-button:focus {
	box-shadow: 0 0 0 2px white, 0 0 0 3px #27AE60;
}
/*headings*/
.fs-title {
	font-size: 15px;
	text-transform: uppercase;
	color: #2C3E50;
	margin-bottom: 10px;
}
.fs-subtitle {
	font-weight: normal;
	font-size: 13px;
	color: #666;
}
/*progressbar*/
.progressbar {
   padding-top: 2em;
   overflow: hidden;
   counter-reset: step;
   width: 62%;
   margin-left: 24em;
 }
.progressbar li {
    list-style-type: none;
    width: 20%;
    float: left;
    position: relative;
    text-align: center;
    color: solid black;
}
.progressbar li:before {
    content: counter(step);
    counter-increment: step;
    width: 20px;
    line-height: 20px;
    display: block;
    font-size: 15px;
    color: #333;
    background: white;
    border-radius: 3px;
    margin: 0 auto 5px auto;
}
.progressbar li:after {
    content: '';
    width: 100%;
    height: 2px;
    background: white;
    position: absolute;
    left: -50%;
    top: 9px;
    z-index: -1; /*put it behind the numbers*/
}
.progressbar li:first-child:after {
    content: none;
}
.progressbar li.active {
    color: green;
}
.progressbar li.active:before {
    border-color: #55b776;
}
.progressbar li.active + li:after {
    background-color: #55b776;
}

    td input[type="radio"] {
        width:20px;
        height:20px;
        display:block;
        margin:0px auto;
    }
    input[type="radio"] {
        width:20px;
        height:15px;
        margin:0px auto;
    }
    .custPre{
        color: #333;
        background-color: #ccc;
        border-color: #ccc;
    }
input[type="checkbox"] {
        width:20px;
        height:20px;
        margin:0px auto;
    }
    .custlegnd{
        margin-top: -29px;
    }
    
  legend{
    background-color: antiquewhite;
    display: block;
    width: 100%;
    padding: 0;
    margin-bottom: 20px;
    font-size: 18px;
    line-height: inherit;
    color: #fff;
    border: 0;
    border-bottom: 1px solid #e5e5e5;
}  
#sameAddress{
    margin-left :29em;
    position: auto;
 
}
.zoom:hover {
 
  -ms-transform: scale(1.5); /* IE 9 */
  -webkit-transform: scale(1.5); /* Safari 3-8 */
  transform: scale(1.5); 
   
}
.receipt{
    padding-right: 1px solid black;
        border-right: dashed;
}
.reciptTabale{
        height: 350px;
    text-align: center;
    padding-top: 10em;
}
.customankel{
    text-decoration: none;
    color: green;
}
.cureentLi{
    color: #8E44AD;
}
.feldset{
    margin-top: 10px;
}

</style>
<?php 
$dataArray= array(
    'core_course' =>'Core Course',
    'ge' =>'Generic Elective',
    'aecc'=>'Ability Enhancement Compulsory Course ',
    'comp' =>'Compulsory'
);
$prefArray= array(
    'tablea' =>'(A)	First Preference',
    'tableb' =>'(B)	Second Preference',
);
?>
<!-- multistep form -->
<ul class="progressbar col-xs-12 col-xs-offset-0  col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2  col-lg-8 col-lg-offset-2 " >
 <li class="l1" ><label> <a id="customankel1" href="<?=  $this->baseUrl("multi-step-form/index/type/step1/a_id/{$this->a_id}"); ?>">Course Details</a></label></li>
    <li class="l2" > <label><a  id="customankel2">Personal Details </a></label> </li>
    <li class="l3"><label><a id="customankel3"> Educational Details </a></label></li>
    <li class="l4"><label><a id="customankel4" > Preview </label></li>
    <li class="l5"><label><a id="customankel5"> Payment</a> </label></li>
</ul>
<?php 
    //$application_id = $this->_getParam("a_id");
    // echo '<pre>';    print_r( $this->paginator );
  
?>
<?php if ($this->type == 'step1') {
     
?>

<div class="multistepformArea col-xs-12 col-xs-offset-0  col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2  col-lg-8 col-lg-offset-2">
    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
    <form class="regForm" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

      
    <div class="row">
        <div  id="notice">
            <a style = "float:right;" href="<?=$this->mainconfig['host'] ?>public/pdfUpload/Admission-Notice-for-B.A-B.Sc..pdf" target="_blank" class="btn btn-primary" id="ba2">Notice For B.A./B.SC.</a>  
            <a style = "float:right;" href="<?=$this->mainconfig['host'] ?>public/pdfUpload/Admission-Notce-for-B.Com..pdf" target="_blank" class="btn btn-primary" id="ba2">Notice For B.COM.(Hons.)</a>
             <a style = float:right; href="<?=$this->mainconfig['host'] ?>public/pdfUpload/Admission-Notice-for-all-Streams.pdf" target="_blank" class="btn btn-primary" id="ba2">Notice For All Streams</a>
       
       
        </div>
    </div>
          
    
    <div class="row">
            <div class="col-sm-12">
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Degree<span class="asterisk"> *</span></label>
                        <?php echo $this->form->degree_id; ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Course<span class="asterisk"> *</span></label>
                        <?php echo $this->form->course; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Session<span class="asterisk"> *</span></label>
                        <?php echo $this->form->session; ?>
                    </div>
                </div>	
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 employee_class">
                    <?php foreach ($prefArray as $key => $value) {
                        // echo "<pre>"; print_r($value);
                    ?>
                <table id='<?php echo $key; ?>' class="table table-striped table-bordered mb30 jambo_table bulk_action ">

                    <thead>
                        <tr>
                            <th  style="width:5%" id="pref<?php echo $key; ?>"> <?php echo $value;?></th>
                            <th style="width:15%"></th>   
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($dataArray as $key2 => $value) {
                            //echo "<pre>"; print_r($value);
                        ?>
                        <tr>
                            
                            <td class="<?php echo $key2?>">
                                <label class="control-label"><?php echo $value; ?> <b style="color:red">*</b> </label>
                                
                            </td>
                            
                            <td class="<?php echo $key2.$key;?>">
                                
                            </td>
                            
                        </tr>
                        <?php }?>
                    </tbody>
                </table>
                <?php }?>
            </div>
        </div>
    
    <div style="float:right;margin-right:2px;padding-bottom: 3em;">
        <button id="firstStep" class="btn btn-success submit next">Save & Next</button>
    </div>
  
</div>
</form>
   <?php } if($this->type== 'step2'){ ?>
    <div class="multistepformArea col-xs-12 col-xs-offset-0  col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2  col-lg-8 col-lg-offset-2">
    <form class="regForm" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

        <div class="row">
            
            <div class="col-sm-12">
                <fieldset>
                    &nbsp; <b><legend>&nbsp;Personal Details:</legend></b>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Applicant Name<span class="asterisk">*</span></label>
                        <?php echo $this->form->applicant_name; ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Email<span class="asterisk">*</span></label>
                        <?php echo $this->form->email_id; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Phone No:<span class="asterisk">*</span></label>
                        <?php echo $this->form->phone; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Birth Date:</label><span class="asterisk" style="">*</span>
                        <?php echo $this->form->dob; ?>
                        <span id="dobError" style="color:red;"></span>
                    </div>
                </div>	
            
          <!------Sesond Row------->
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label"> Gender<span class="asterisk">*</span></label>
                        <?php echo $this->form->gender; ?>
                    </div>
                </div>
                
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Nationality<span class="asterisk">*</span></label>
                        <?php echo $this->form->nationality; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Religion<span class="asterisk">*</span></label>
                        <?php echo $this->form->religion; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class" id="others_rel">
                    <div class="form-group">
                       <label class="control-label">Name Of Religion<span class="asterisk">*</span></label>
                        <?php echo $this->form->others_religion; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Aadhar No:<span class="asterisk">*</span></label>
                        <?php echo $this->form->aadhar; ?>
                          <span id="aadharError" style="color:red;  position: absolute;"></span>
                    </div>
                </div>
          <!------Third Row------->
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Father's Name<span class="asterisk">*</span></label>
                        <?php echo $this->form->father_name; ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Father's Qualification<span class="asterisk">*</span></label>
                        <?php echo $this->form->father_qual; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Father's occupation<span class="asterisk">*</span></label>
                        <?php echo $this->form->father_occup; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Father's Contact<span class="asterisk">*</span></label>
                        <?php echo $this->form->father_contact; ?>
                        <span id="fcCodeError" style="color:red;"></span>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Mother's Name<span class="asterisk">*</span></label>
                        <?php echo $this->form->mother_name; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Mother's Qualification</label>
                        <?php echo $this->form->mother_qual; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Mother's Occupation</label>
                        <?php echo $this->form->mother_occup; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Mother's Contact</label>
                        <?php echo $this->form->mother_contact; ?>
                        <span id="mcCodeError" style="color:red;"></span>
                    </div>
                </div>	
            
            <!------Fourth Row------->
        
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Guardian's Name</label>
                        <?php echo $this->form->guard_name; ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Guardian's  Qualification</label>
                        <?php echo $this->form->guard_qual; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Guardian's  Occupation</label>
                        <?php echo $this->form->guard_occup; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Contact No.</label>
                         <?php echo $this->form->guard_contact; ?>
                      <span id="gcCodeError" style="color:red;"></span>
                    </div>
                </div>	
                </fieldset>  
            </div>
        </div>
        <!--Address Details---->
        <div class="row">
            
            <div class="col-sm-12">
                <fieldset>
                    &nbsp;<b><legend>&nbsp;Permanent Address:</legend></b>
                 
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Address<span class="asterisk">*</span></label>
                        <?php echo $this->form->p_address; ?>
                      
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Home Town <span class="asterisk">*</span></label>
                        <?php echo $this->form->p_homeTown; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Post Office <span class="asterisk">*</span></label>
                        <?php echo $this->form->p_postOffice; ?>
                    </div>
                </div>	
               	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Police Station  <span class="asterisk">*</span></label>
                        <?php echo $this->form->p_policeSt; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">District   <span class="asterisk">*</span></label>
                        <?php echo $this->form->p_district; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">State   <span class="asterisk">*</span></label>
                        <?php echo $this->form->p_state; ?>
                    </div>
                </div>	
                    
                 <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Pin Code <span class="asterisk">*</span></label>
                        <?php echo $this->form->p_code; ?>
                       <span id="pCodeError" style="color:red;"></span>
                    </div>
                </div>
               </fieldset> 
            </div>
            <div class="col-xs-12 col-md-12 col-lg-12 col-sm-12">
                <fieldset>
                   
                   
                   &nbsp;<b><legend class="custlegnd"> &nbsp;Local Address: &nbsp; <input  type="checkbox" name="sameAddress" id="sameAddress" name="sameAddress" <?= $this->paginator['same_address'] == '1'?'checked':''?> value="1">&nbsp;&nbsp;<b>Mark if same as Permanent Address</b></legend></b>
                   
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Address<span class="asterisk">*</span></label>
                        <?php echo $this->form->l_address; ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Home Town <span class="asterisk">*</span></label>
                        <?php echo $this->form->l_homeTown; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Post Office <span class="asterisk">*</span></label>
                        <?php echo $this->form->l_postOffice; ?>
                    </div>
                </div>	
               	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Police Station  <span class="asterisk">*</span></label>
                        <?php echo $this->form->l_policeSt; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">District   <span class="asterisk">*</span></label>
                        <?php echo $this->form->l_district; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">State   <span class="asterisk">*</span></label>
                        <?php echo $this->form->l_state; ?>
                    </div>
                </div>	
                    
                 <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Pin Code <span class="asterisk">*</span></label>
                        <?php echo $this->form->l_code; ?>
                       <span id="lCodeError" style="color:red;"></span>
                    </div>
                </div>
                </fieldset>
                <fieldset>
                   
                   
                   &nbsp;<b><legend class="custlegnd"> &nbsp;Blood Group</legend></b>
                   <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Blood Group <span class="asterisk">*</span></label>
                        <?php echo $this->form->blood_group; ?>
                       <span id="lCodeError" style="color:red;"></span>
                    </div>
                </div>
               </fieldset> 
            </div>   
        </div>
        <br/>
        <div style="float:right;margin-right:2px;padding-bottom: 3em;">
            
            <a href="<?=  $this->baseUrl("multi-step-form/index/type/step1/a_id/{$this->a_id}"); ?>"> <button type="button"  id="previous" class="btn custPre">Previous</button></a>
            <button id="secondStep" class="btn btn-primary submit">Save & Next</button>
        </div>
   
  
</div>
</form>
   <?php } if ($this->type== 'step3') { 
        //echo '<pre>'; print_r($this->paginator);
       //echo '<pre>'; print_r($this->followup);
    ?>
    <div class="multistepformArea multistepformArea col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2  col-lg-8 col-lg-offset-2 table-responsive">
        <form class="regForm" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >

        <div class="row">
            <div class="col-sm-12">
                <div class="col-sm-8 employee_class">
                    <div class="form-group">
                        <label class="control-label">If you are Appearing Student Select Here<span class="asterisk">*</span></label>
                     </div>
                    <div class="col-sm-4 employee_class">
                        <label class="control-label">Yes</label> <input type="radio" name="appearingStatus"  value="1" <?= $this->paginator['appearingStatus'] == '1'?'checked':''?> id="as"   required />
                    </div>
                    <div class="col-sm-4 employee_class">
                       
                        <label class="control-label">No</label> <input type="radio" <?= $this->paginator['appearingStatus'] == '0'?'checked':''?>  name="appearingStatus" id="as" value="0"  required  /> 
                    </div>
                  
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12">
                <fieldset>
                     <?php if($this->followup['degree_id'] != 1){ ?>
                    &nbsp;<b><legend>  &nbsp; Academic Details</legend></b>
                <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                    <thead>
                        <tr>
                            <th>Name Of Examination</th>
                            <th>Board/University</th>
                            <th>Name of Institution</th>
                            <th>Division/Grade</th>    
                            <th>Subject</th>
                            <th>Passing Year</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if($this->followup['course'] == 10){  ?>
                        <tr>
                            <td><b>Matric</b></td>
                            <td>
                                <?php 
                                    echo $this->form->mat_board; 
                                ?>
                            </td>
                            <td>
                                <?php  echo $this->form->mat_school; ?>
                            </td>
                            <td>
                                <?php  echo $this->form->mat_division;  ?>
                            </td>
                            <td>
                                <?php  echo $this->form->mat_subject;  ?>
                            </td>
                            <td>
                                <?php   echo $this->form->mat_pass_year;  ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b>10+2</b></td>
                            <td>
                                <?php   echo $this->form->i_board;  ?>
                            </td>
                            <td>
                                <?php 
                                        echo $this->form->school;  ?>
                            </td>
                            <td>
                                <?php echo $this->form->i_division; ?>
                            </td>
                            <td>
                                <?php  echo $this->form->subject; ?>
                            </td>
                            <td>
                                <?php echo $this->form->i_pass_year;  ?>
                            </td>
                                
                        </tr>
                        
                        <tr>
                            <td><b> BCA/B.Sc(CS)</b></td>
                            <td>
                                <?php echo $this->form->bca_board;   ?>
                            </td>
                            <td>
                                <?php  echo $this->form->bca_school; ?>
                            </td>
                            <td>
                                <?php echo $this->form->bca_division;    ?>
                            </td>
                            <td>
                                <?php  echo $this->form->bca_subject; ?>
                            </td>
                            <td>
                                <?php  echo $this->form->bca_pass_year;  ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td> <b>Graduation with Maths and One year Diploma in computing </b></td>
                            <td>
                                <?php echo $this->form->grad_math_board;  ?>
                            </td>
                            <td>
                                <?php echo $this->form->grad_math_school;  ?>
                            </td>
                            <td>
                                <?php  echo $this->form->grad_math_division;  ?>
                            </td>
                            <td>
                                <?php echo $this->form->grad_math_subject;  ?>
                            </td>
                            <td>
                                <?php echo $this->form->grad_math_pass_year;   ?>
                            </td>
                                
                        </tr>
                       <!--- <tr>
                            <td> <b>Certification CS</b></td>
                            <td>
                                <?php echo $this->form->cert_board;   ?>
                            </td>
                            <td>
                                <?php  echo $this->form->cert_school;   ?>
                            </td>
                            <td>
                                <?php  echo $this->form->cert_division;  ?>
                            </td>
                            <td>
                                <?php echo $this->form->cert_subject;  ?>
                            </td>
                            <td>
                                <?php echo $this->form->cert_pass_year;   ?>
                            </td>
                                
                        </tr>--->
                        <tr>
                            <td><b> Other </b></td>
                            <td>
                                <?php echo $this->form->other_board;    ?>
                            </td>
                            <td>
                                <?php echo $this->form->other_school;  ?>
                            </td>
                            <td>
                                <?php echo $this->form->other_division;  ?>
                            </td>
                            <td>
                                <?php echo $this->form->other_subject; ?>
                            </td>
                            <td>
                                <?php  echo $this->form->other_pass_year;  ?>
                            </td>
                                
                        </tr>
                        <?php }else { ?>
                        <tr>
                            <td><b>Matric</b></td>
                            <td>
                                <?php echo $this->form->mat_board;   ?>
                            </td>
                            <td>
                                <?php  echo $this->form->mat_school;   ?>
                            </td>
                            <td>
                                <?php  echo $this->form->mat_division;  ?>
                            </td>
                            <td>
                                <?php echo $this->form->mat_subject;  ?>
                            </td>
                            <td>
                                <?php   echo $this->form->mat_pass_year;  ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b>10+2</b></td>
                            <td>
                                <?php echo $this->form->i_board; ?>
                            </td>
                            <td>
                                <?php  echo $this->form->school;   ?>
                            </td>
                            <td>
                                <?php  echo $this->form->i_division;     ?>
                            </td>
                            <td>
                                <?php  echo $this->form->subject; ?>
                            </td>
                            <td>
                                <?php echo $this->form->i_pass_year;   ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b> Graduation  </b></td>
                            <td>
                                <?php  echo $this->form->grad_board;    ?>
                            </td>
                            <td>
                                <?php echo $this->form->grad_school;  ?>
                            </td>
                            <td>
                                <?php  echo $this->form->grad_division;  ?>
                            </td>
                            <td>
                                <?php   echo $this->form->grad_subject;  ?>
                            </td>
                            <td>
                                <?php echo $this->form->grad_pass_year; ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b> Other </b></td>
                            <td>
                                <?php echo $this->form->other_board;  ?>
                            </td>
                            <td>
                                <?php echo $this->form->other_school; ?>
                            </td>
                            <td>
                                <?php  echo $this->form->other_division;   ?>
                            </td>
                            <td>
                                <?php echo $this->form->other_subject;   ?>
                            </td>
                            <td>
                                <?php echo $this->form->other_pass_year;   ?>
                            </td>
                                
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
                
               	
                </fieldset>   
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12">
               <fieldset class="col-xs-12 col-sm-12 col-md-12 col-lg-12 table-responsive">
                   
                        &nbsp;<b><legend>  &nbsp;Last Examination Details</legend></b>

                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                            <thead>
                                <tr>
                                    <th>Name of Institution</th>
                                    <th>Place</th>
                                    <th>Board/University</th>
                                    <th>Passing Year</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td><?php echo $this->form->l_institution; ?></td>
                                    <td><?php echo $this->form->l_place; ?></td>
                                    <td><?php echo $this->form->last_board; ?></td>
                                    <td><?php echo $this->form->l_p_year; ?></td>

                                </tr>

                            </tbody>
                        </table>
                        </fieldset>
                    <?php }else{ ?>
                        <fieldset class="col-xs-12 col-sm-12 col-md-12 col-lg-12 table-responsive">
                   
                    &nbsp;<b><legend>  &nbsp; Intermediate Education Details</legend></b>
                <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                    <thead>
                        <tr>
                            <th>School/College</th>
                            <th>Board/University</th>
                            <th>Division/Grade</th>
                            <th>Roll Number</th>
                            <th>Obtained Marks</th>
                            <th>Total Marks</th>
                            <th>Percent(%) </th>
                            <th>Passing Year</th>
                        </tr>
                    </thead>
                    <tbody>
                      
                        <tr>
                            <td><?php echo $this->form->school; ?></td>
                            <td><?php echo $this->form->i_board; ?></td>
                            <td><?php echo $this->form->i_division; ?></td>
                            <td><?php echo $this->form->i_roll; ?></td>
                            <td><?php echo $this->form->obt_marks; ?></td>
                            <td><?php echo $this->form->total_marks; ?></td>
                            <td><?php echo $this->form->percent; ?></td>
                            <td><?php echo $this->form->i_pass_year; ?></td>
                                
                        </tr>
                   
                    </tbody>
                </table>
                </fieldset>
                     &nbsp;<fieldset class="col-xs-12 col-sm-12 col-md-12 col-lg-12 table-responsive"><b><legend>  &nbsp;Last Examination Details</legend></b>

                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                            <thead>
                                <tr>
                                    <th>Name of Institution</th>
                                    <th>Place</th>
                                    <th>Board/University</th>
                                    <th>Passing Year</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td><?php echo $this->form->l_institution; ?></td>
                                    <td><?php echo $this->form->l_place; ?></td>
                                    <td><?php echo $this->form->last_board; ?></td>
                                    <td><?php echo $this->form->l_p_year; ?></td>

                                </tr>

                            </tbody>
                        </table>
                </fieldset>  
               <?php } ?>
            </div>
            <div class=" col-xs-12 col-sm-12  col-md-12  col-lg-12 col-sm-12">
                <fieldset>
                
                <div class="col-sm-12 employee_class">
                    <?php 
                        $eduCertificate = explode('/',$this->paginator['educertificate']);
                        $eduCertificate = $eduCertificate[count($eduCertificate)-1];
                    ?>
                    <div class="col-xs-6 col-sm-6  col-md-6  col-lg-6">
                    <label><span style="color:#777;" id="p">Upload certificate: </span></label>
                    <input name="educertificate" id="educertificate" type="file" value="<?=!empty($eduCertificate)?$eduCertificate:'';?>"  accept="image/jpg, image/jpeg, image/png,application/pdf" pattern=".*\.(jpeg|png|pdf|jpg)" <?=!empty($eduCertificate)?'':'';?> />
                    <div class='form-control-statuc' >
                        <span class='text-danger'>*Only .jpg or .png or .pdf files can be uploaded</span>
                    </div>
                    </div>
                    <div class="col-xs-6 col-sm-6  col-md-6  col-lg-6">
                            <?php  preg_match('/.*\.(pdf|jpg|jpeg|png)/', $this->paginator['educertificate'], $output_array); ?>
                   
                           
                        <?php if($output_array[1] == 'pdf'){ ?>
                            <div class="col-sm-12">
                                <a href="<?php echo $this->baseUrl($this->paginator['educertificate']);?> " target="_blank" <i class="fa fa-file-pdf-o" aria-hidden="true"><b><?php echo 'Applicant Educational Certificate';?></b></i></a>
                            </div>
                        <?php } else { ?>
                             <img id="eduFile" src ="<?=$this->baseUrl($this->paginator['educertificate']);?>" style="width:5em;" onerror="this.src='<?php echo $this->mainconfig['publicpath']; ?>images/alt_images.jpg';"  />
                       <?php } ?>
                    </div>
                </div> 
               	  &nbsp;
                </fieldset>   
            </div>
            <!--- Caste Details ----->
            <div class="col-sm-12">
                <fieldset>
                    &nbsp;<b><legend >  &nbsp;Please select if you are applying under the caste category</legend></b>
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 employee_class">
                    <div class="form-group">
                        <label class="control-label"> Caste Category<span class="asterisk">*</span></label>
                        <?php echo $this->form->caste_category; ?>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 employee_class">
                    <div class="form-group">
                        <label class="control-label"> Caste <span class="asterisk">*</span></label>
                        <?php echo $this->form->caste; ?>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 employee_class">
                    <div class="form-group">
                        <label class="control-label"> Certificate Issued by <span class="asterisk">*</span></label>
                        <?php echo $this->form->certificate_issued; ?>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 employee_class">
                    <div class="form-group">
                        <label class="control-label"> Caste Certificate No. <span class="asterisk">*</span></label>
                        <?php echo $this->form->certificate_no; ?>
                    </div>
                </div>
                     
                <div class="col-xs-12 col-sm-12  col-md-12  col-lg-12 col-sm-12 employee_class">
                    <?php 
                        $casteCertificate = explode('/',$this->paginator['casteCertificate']);
                        $casteCertificate = $casteCertificate[count($casteCertificate)-1];
                    ?>
                    <div class="col-xs-6 col-sm-6  col-md-6  col-lg-6">
                    <label><span style="color:#777;">Upload Caste certificate: </span></label>
                    <input name="casteCertificate" id="casteCertificate" type="file" value="<?=!empty($casteCertificate)?$casteCertificate:'';?>"  accept="image/jpg,image/jpeg,image/png,application/pdf" pattern=".*\.(jpeg|png|pdf|jpg)" />
                    <div class='form-control-statuc' >
                        <span class='text-danger'>*Only .jpg or .png or .pdf files can be uploaded</span>
                    </div>
                    </div>
                    <div class="col-xs-6 col-sm-6  col-md-6  col-lg-6">
                        <?php  preg_match('/.*\.(pdf|jpg|jpeg|png)/', $this->paginator['casteCertificate'], $output_array); ?>
                   
                            
                        <?php if($output_array[1] =='pdf'){ ?>
                            <div class="col-sm-12">
                                <a data-file="pdf" href="<?php echo $this->baseUrl($this->paginator['casteCertificate']);?> " target="_blank" <i class="fa fa-file-pdf-o" aria-hidden="true"><b><?php echo 'Applicant Caste Certificate';?></b></i></a>
                            </div>
                        <?php } else{ ?>
                        <img id="casteFile" data-file="img" src ="<?=$this->baseUrl($this->paginator['casteCertificate']);?>" style="width:5em;"onerror="this.src='<?php echo $this->mainconfig['publicpath']; ?>images/alt_images.jpg';"/>
                        <?php }?>
                    </div>
                </div>
               &nbsp;
               	
                </fieldset>   
            </div>
            <!---Extra-Curricular Activities----->
            <div class="col-xs-12 col-sm-12  col-md-12  col-lg-12 col-sm-12">
                <?php //echo '<pre>'; print_r($savedData);?>
                <fieldset>
                    &nbsp;<b><legend >  &nbsp;Extra-Curricular Activities</legend></b>
                <div class="col-xs-12 col-sm-3  col-md-3  col-lg-3  employee_class">
                   
                    <div class="form-group">
                       
                        <input type="checkbox" name="ExtraCurricularSelection[]" <?php if( in_array("NCC", explode(',',$this->paginator['ExtraCurricularSelection']))){
                             echo "checked";
                             
                         } 
                             ?> value="NCC">
                        <label class="control-label"> NCC </label>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4  col-md-4  col-lg-4 employee_class">
                    <div class="form-group">
                       <input type="checkbox" name="ExtraCurricularSelection[]" <?php if( in_array("Literacy Program", explode(',',$this->paginator['ExtraCurricularSelection']))){
                             echo "checked";
                             
                         } 
                             ?> value="Literacy Program">
                        <label class="control-label"> Literacy Program </label>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-3  col-md-3  col-lg-3 employee_class">
                    <div class="form-group">
                        <input type="checkbox" name="ExtraCurricularSelection[]" <?php if( in_array("NSS", explode(',',$this->paginator['ExtraCurricularSelection']))){
                             echo "checked";
                             
                         } 
                             ?> value="NSS"> 
                        <label class="control-label"> NSS</label>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-2  col-md-2  col-lg-2 employee_class">
                    <div class="form-group">
                       <input type="checkbox" name="ExtraCurricularSelection[]" <?php if( in_array("Athletics", explode(',',$this->paginator['ExtraCurricularSelection']))){
                             echo "checked";
                             
                         } 
                             ?> value="Athletics"> 
                        <label class="control-label"> Athletics</label>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-3  col-md-3  col-lg-3 employee_class">
                    <div class="form-group">
                    
                        <input type="checkbox" name="ExtraCurricularSelection[]" <?php if( in_array("Cultural Activity", explode(',',$this->paginator['ExtraCurricularSelection']))){
                             echo "checked";
                             
                         } 
                             ?> value="Cultural Activity">
                        <label class="control-label"> Cultural Activity	</label>
                    </div>
                </div>
                
                <div class="col-xs-12 col-sm-4  col-md-4  col-lg-4 employee_class">
                    <div class="form-group">
                         
                        <input type="checkbox" name="ExtraCurricularSelection[]" <?php if( in_array("Environment Protection Program", explode(',',$this->paginator['ExtraCurricularSelection']))){
                             echo "checked";
                             
                         } 
                             ?> value="Environment Protection Program"> 
                        <label class="control-label"> Environment Protection Program </label>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-2  col-md-2  col-lg-2 employee_class">
                    <div class="form-group">
                       <input type="checkbox" name="ExtraCurricularSelection[]" <?php if( in_array("Games", explode(',',$this->paginator['ExtraCurricularSelection']))){
                             echo "checked";
                             
                         } 
                             ?> value="Games">
                        <label class="control-label"> Games</label>
                    </div>
                </div>
          
            </fieldset>  
            </div> 
            <!--- Upload Photo Or Signature Section ----->
            <div class="col-xs-12 col-sm-12  col-md-12  col-lg-12 col-sm-12">
                <fieldset>
                    &nbsp;<b><legend >  &nbsp;Upload</legend></b>
                <?php 
                    $filephoto = explode('/',$this->paginator['photo']);
                    $filephoto = $filephoto[count($filephoto)-1];
                ?>
                     
            <div class="col-xs-12 col-sm-12  col-md-12  col-lg-12 employee_class">
                <div class="col-xs-6 col-sm-6  col-md-6  col-lg-6">
                <label><span style="color:#777;">Recent Passport Size Photo: (SIZE:50 X 50) </span></label>
                <input type="file" name= "photo" id="photo" value="<?=!empty($filephoto)?$filephoto:'';?>"  accept="image/jpg, image/jpeg, image/png" <?=!empty($filephoto)?'':'required';?> />
                <div class='form-control-statuc' >
                    <span class='text-danger'>*Only .jpg or .png files can be uploaded</span>
                </div>
                </div>
                <div class="col-xs-6 col-sm-6  col-md-6  col-lg-6">
                
                    <img id="imgLogo" src ="<?=$this->baseUrl($this->paginator['photo']);?>" style="width:5em;" onerror="this.src='<?php echo $this->mainconfig['publicpath']; ?>images/alt_images.jpg';" />

                </div>
            </div>
            <?php if($this->followup['religion'] == 'Christian'){ ?>
                <?php 
                    $baptismFile = explode('/',$this->paginator['baptism']);
                    $baptismFile = $baptismFile[count($baptismFile)-1];
                ?>    
                <div class="col-sm-6 employee_class">
                    <div class="col-sm-6">
                    <label><span style="color:#777;">Upload Baptism Certificate: </span></label>
                    <input name="baptism" id="baptism" type="file" value="<?=!empty($baptismFile)?$baptismFile:'';?>" accept="image/jpg, image/jpeg, image/png,application/pdf" pattern=".*\.(jpeg|png|pdf|jpg)" <?=!empty($baptismFile)?'':'';?>/>
                    <div class='form-control-statuc' >
                        <span class='text-danger'>*Only .jpg or .png or .pdf files can be uploaded</span>
                    </div>
                    </div>
                    <div class="col-sm-6">
                        <?php  preg_match('/.*\.(pdf|jpg|jpeg|png)/', $this->paginator['baptism'], $output_array); ?>
                   
                            
                        <?php if($output_array[1] == 'pdf'){ ?>
                            <div class="col-sm-12">
                                <a href="<?php echo $this->baseUrl($this->paginator['baptism']);?> " target="_blank" <i class="fa fa-file-pdf-o" aria-hidden="true"><b><?php echo 'Applicant Baptism Certificate';?></b></i></a>
                            </div>
                        <?php } else { ?>
                            <img id="baptismFile" src ="<?=$this->baseUrl($this->paginator['baptism']);?>" style="width:5em;" onerror="this.src='<?php echo $this->mainconfig['publicpath']; ?>images/alt_images.jpg';" />
                        <?php } ?>
                    </div>
                </div>
                    
            <?php } ?>
            &nbsp;
            </fieldset>   
            </div>
               
            </div>
            <div class="row">
                <div class="col-sm-12 employee_class">
                     
                </div>
            </div>
            <br />
        <div style="float:right;margin-right:2px;padding-bottom: 3em;">
          <a href="<?=  $this->baseUrl("multi-step-form/index/type/step2/a_id/{$this->a_id}"); ?>"> <button type="button"  id="previous" class="btn custPre">Previous</button></a>
            <button id="preview" class="btn btn-success submit next">Save & Preview Form</button>
        </div>

    </div>
    </form>
        <?php } if($this->type== 'step4'){ ?>
       
        <div class="multistepformArea col-xs-12 col-xs-offset-0  col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2  col-lg-8 col-lg-offset-2" id="previeDivision">
             <form class="regForm" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >
        <div class="col-sm-12 employee_class" id="previewData">
            <fieldset class="feldset">
                     <b><legend>1. Course Details:
                            <a href="<?=  $this->baseUrl("multi-step-form/index/type/step1/a_id/{$this->a_id}"); ?>"><span style="margin-left:26em" class="fa fa-edit fa-lg"></span></a>
                        </legend></b>
                    <div class="col-sm-6 employee_class">
                        <div class="form-group">
                            <label class="control-label"> Course (Applied for)<span class="asterisk">*</span></label><br>
                            <?php echo $this->paginator['course_name']; ?>
                        </div>
                    </div>
                
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <label class="control-label">Session<span class="asterisk">*</span></label><br>
                           <?php echo $this->paginator['session']; ?>
                        </div>
                    </div>
                    <div class="col-sm-3  employee_class">
                        <div class="form-group" style="float:right;">
                            <img src="<?php echo $this->baseUrl($this->paginator['photo']);?>" alt="img" height="100" width="100"> 
                        </div>
                    </div>
                </fieldset>  
                <?php if(!empty($this->paginator['degree'] == 1)){ ?>
            <fieldset class="feldset">
                    <?php
                    $cc_id_InArray = ["4", "16", "17","18","19","20","21"];
                    if (in_array($this->paginator['course'], $cc_id_InArray, TRUE)) { ?>
                    <p><legend>Preference:</legend></p>
                    <?php } else{ ?>
                     &nbsp;<p><legend>&nbsp;&nbsp;i. First Preference:</legend></p>
                    <?php }?>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Core Course:<span class="asterisk">*</span></label><br>
                       <?php if(!empty($this->paginator['corecourse1'])){
                             echo $this->paginator['corecourse1'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Generic Elective:<span class="asterisk">*</span></label><br>
                       <?php if(!empty($this->paginator['ge1'])){
                             echo $this->paginator['ge1'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">AECC<span class="asterisk">*</span></label><br>
                        <?php echo $this->paginator['aecc1']; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Compulsary Subject<span class="asterisk">*</span></label><br>
                        <?php echo $this->paginator['comp_evs']; ?>
                    </div>
                </div>	
            
        
             	
                </fieldset>  
                <?php 
                $cc_id_InArray = ["4", "16", "17","18","19","20","21"];
                if (!in_array($this->paginator['course'], $cc_id_InArray, TRUE)) { ?>
            <fieldset class="feldset">
                    <p><legend> ii.Second Preference:</legend></p>
                
            
          <!------Second Row ------->
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label"> Core Course<span class="asterisk">*</span></label><br>
                         <?php if(!empty($this->paginator['corecourse2'])){
                             echo $this->paginator['corecourse2'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Generic Elective<span class="asterisk">*</span></label><br>
                        <?php if(!empty($this->paginator['ge2'])){
                             echo $this->paginator['ge2'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">AECC<span class="asterisk">*</span></label><br>
                        <?php if(!empty($this->paginator['aecc2'])){
                             echo $this->paginator['aecc2'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Compulsory Subject<span class="asterisk">*</span></label><br>
                        <?php echo $this->paginator['comp_evs']; ?>
                    </div>
                </div>
             	
                </fieldset>  
          
                <?php }} ?>
<!--- Personal Detail -------->
                <fieldset class="feldset">
                   <b><legend>2.Personal Details:
                            <a href="<?=  $this->baseUrl("multi-step-form/index/type/step2/a_id/{$this->a_id}"); ?>"> <span style="margin-left:26em" class="fa fa-edit fa-lg"></span></a>
                        </legend></b>
            <div class="row" style="margin-left: .04em;">
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Applicant Name<span class="asterisk">*</span></label><br>
                        <?php echo ucfirst($this->paginator['applicant_name']); ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Email<span class="asterisk">*</span></label><br>
                        <?php echo $this->paginator['email_id']; ?>    
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Phone No:<span class="asterisk">*</span></label><br>
                           <?php echo $this->paginator['phone']; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Date Of Birth:<span class="asterisk">*</span></label><br>
                        <?php echo $this->form->dob; ?>
                        <?php echo $this->paginator['dob']; ?>
                    </div>
                </div>	
            </div>
          <!------Sesond Row------->
            <div class="row" style="margin-left: .04em;">
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label"> Gender<span class="asterisk">*</span></label><br>
                         <?php if($this->paginator['gender'] == 1){
                            echo 'Female';
                         }else{
                            echo 'Transgender';
                         }  ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Aadhar No:<span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['aadhar']; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Nationality<span class="asterisk">*</span></label><br>
                        <?php echo $this->paginator['nationality']; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Religion<span class="asterisk">*</span></label><br>
                        <?php if($this->paginator['religion'] == 'others'){
                                echo $this->paginator['others_religion'];
                            } else {
                               echo $this->paginator['religion'];
                            } ?>
                    </div>
                </div>	
            </div>   	
          <!------Third Row------->
            <div class="row" style="margin-left: .04em;">
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Father's Name<span class="asterisk">*</span></label><br>
                         <?php echo ucfirst($this->paginator['father_name']); ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Father's Qualification<span class="asterisk">*</span></label><br>
                        <?php echo $this->paginator['father_qual']; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Father's occupation<span class="asterisk">*</span></label><br>
                        <?php echo $this->paginator['father_occup']; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Father's Contact Number<span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['father_contact']; ?>
                    </div>
                </div>
                
            </div>  	
            
            <!------Fourth Row------->
            <div class="row" style="margin-left: .04em;">
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Mother's Name<span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['mother_name']; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Mother's Contact Number<span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['mother_contact']; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Mother's Qualification<span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['mother_qual']; ?>
                    </div>
                </div>
                 <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Mother's occupation<span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['mother_occup']; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Guardian's Name</label><br>
                        <?php if(!empty($this->paginator['guard_name'])){
                            echo$this->paginator['guard_name'];
                        } else {
                            echo 'N/A';
                        }
                        ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Guardian's  Qualification</label><br>
                        <?php if(!empty($this->paginator['guard_qual'])){
                            echo$this->paginator['guard_qual'];
                        } else {
                            echo 'N/A';
                        }
                        ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Guardian's  Occupation</label><br>
                        <?php if(!empty($this->paginator['guard_occup'])){
                            echo$this->paginator['guard_occup'];
                        } else {
                            echo 'N/A';
                        }
                        ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Contact No.</label><br>
                        <?php if(!empty($this->paginator['guard_contact'])){
                            echo$this->paginator['guard_contact'];
                        } else {
                            echo 'N/A';
                        }
                        ?>
                    </div>
                </div>
            </div>
                </fieldset>  
    
        <!--Address Details---->
        <div class="row">
            
            <div class="col-sm-12">
                <fieldset class="feldset">
                    <p><legend>i.Permanent Address:</legend></p>
                 
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Address<span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['p_address']; ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Home Town <span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['p_homeTown']; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Post Office <span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['p_postOffice']; ?>
                    </div>
                </div>	
               	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Police Station  <span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['p_policeSt']; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">District   <span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['p_district']; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">State   <span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['p_state']; ?>
                    </div>
                </div>	
                    
                 <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Pin Code <span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['p_code']; ?>
                       <span id="pCodeError" style="color:red;"></span>
                    </div>
                </div>
               </fieldset> 
            </div>
            <div class="col-sm-12">
                <fieldset>
                    
                   &nbsp;<p><legend class="custlegnd"> &nbsp;&nbsp;ii.Local Address:</legend></p><br>
                   
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Address<span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['l_address']; ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Home Town <span class="asterisk">*</span></label><br>
                        <?php echo $this->paginator['l_homeTown']; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Post Office <span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['l_postOffice']; ?>
                    </div>
                </div>	
               	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Police Station  <span class="asterisk">*</span></label><br>
                        <?php echo $this->paginator['l_policeSt']; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">District   <span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['l_district']; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">State   <span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['l_state']; ?>
                    </div>
                </div>	
                    
                 <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Pin Code <span class="asterisk">*</span></label><br>
                         <?php echo $this->paginator['l_code']; ?>
                    </div>
                </div>
               </fieldset> 
            </div>
            <!----- Educational Details ---->
            
        </div>
            <fieldset>
                    &nbsp; <b><legend>3.&nbsp;Educational Details:
                            <a href="<?=  $this->baseUrl("multi-step-form/index/type/step3/a_id/{$this->a_id}"); ?>"><span style="margin-left:26em" class="fa fa-edit fa-lg"></span></a>
                        </legend></b>
                    <div class="col-sm-6 employee_class">
                        <div class="form-group">
                            <label class="control-label"> Appearing Status<span class="asterisk">*</span></label>
                            <?php if($this->paginator['appearingStatus'] == 1){
                                echo 'Yes';
                            } else {
                                echo 'No';
                            }
                            ?>
                        </div>
                    </div>
                
                </fieldset>  

                
                <fieldset>
                     <?php if($this->paginator['degree'] != 1){ ?>
                    &nbsp;<p><legend>  &nbsp; i. Academic Details</legend></p>
                <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                    <thead>
                        <tr>
                            <th>Name Of Examination</th>
                            <th>Board/University</th>
                            <th>Name of Institution</th>
                            <th>Division/Grade</th>    
                            <th>Subject</th>
                            <th>Passing Year</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if($this->paginator['course_name'] == 'M.C.A'){  ?>
                        <tr>
                            <td><b>Matriculation</b></td>
                            <td>
                                <?php   echo $this->paginator['mat_board']; ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['mat_school']; ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['mat_division'];  ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['mat_subject'];  ?>
                            </td>
                            <td>
                                <?php   echo $this->paginator['mat_pass_year'];  ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b>10+2</b></td>
                            <td>
                                <?php echo  $this->paginator['i_board'];  ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['school'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['i_division']; ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['subject']; ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['i_pass_year'];  ?>
                            </td>
                                
                        </tr>
                        
                        <tr>
                            <td><b> BCA/B.Sc(CS)</b></td>
                            <td>
                                <?php echo  $this->paginator['bca_board'];   ?>
                            </td>
                            <td>
                                <?php  echo  $this->paginator['bca_school']; ?>
                            </td>
                            <td>
                                <?=  !empty($this->paginator['bca_division'])?$this->paginator['bca_division']:'N/A' ?>
                            </td>
                            <td>
                                <?=  !empty($this->paginator['bca_subject'])?$this->paginator['bca_subject']:'N/A' ?>
                            </td>
                            <td>
                                <?=  !empty($this->paginator['bca_pass_year'])?$this->paginator['bca_pass_year']:'N/A' ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td> <b>Graduation with Maths and one year Diploma in computing </b></td>
                             <td>
                                <?=  !empty($this->paginator['grad_math_board'])?$this->paginator['grad_math_board']:'N/A' ?>
                                
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_math_school'])?$this->paginator['grad_math_school']:'N/A' ?>
                               
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_math_division'])?$this->paginator['grad_math_division']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_math_subject'])?$this->paginator['grad_math_subject']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_math_pass_year'])?$this->paginator['grad_math_pass_year']:'N/A' ?>
                            </td>
                            
                           
                                
                        </tr>
                       <!---- <tr>
                            <td> <b>Certification CS</b></td>
                            <td>
                                <?php echo $this->paginator['cert_board'];   ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['cert_school'];   ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['cert_division'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['cert_subject'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['cert_pass_year'];   ?>
                            </td>
                                
                        </tr>---->
                        <tr>
                            <td><b> Other </b></td>
                            <td>
                                <?php echo $this->paginator['other_board'];    ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['other_school'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['other_division'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['other_subject']; ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['other_pass_year'];  ?>
                            </td>
                                
                        </tr>
                        <?php }else { ?>
                        <tr>
                            <td><b>Matriculation</b></td>
                            <td>
                                <?php echo $this->paginator['mat_board'];   ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['mat_school'];   ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['mat_division'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['mat_subject'];  ?>
                            </td>
                            <td>
                                <?php echo$this->paginator['mat_pass_year'];  ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b>Intermediate</b></td>
                            <td>
                                <?php echo $this->paginator['i_board']; ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['school'];   ?>
                            </td>
                            <td>
                                <?php  echo$this->paginator['i_division'];     ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['subject']; ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['i_pass_year'];   ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b> Graduation  </b></td>
                            <td>
                                <?= !empty($this->paginator['grad_board'])?$this->paginator['grad_board']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_school'])?$this->paginator['grad_school']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_division'])?$this->paginator['grad_division']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_subject'])?$this->paginator['grad_subject']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_pass_year'])?$this->paginator['grad_pass_year']:'N/A' ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b> Other </b></td>
                            <td>
                                <?= !empty($this->paginator['other_board'])?$this->paginator['other_board']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['other_school'])?$this->paginator['other_school']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['other_division'])?$this->paginator['other_division']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['other_subject'])?$this->paginator['other_subject']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['other_pass_year'])?$this->paginator['other_pass_year']:'N/A' ?>
                                
                            </td>
                                
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
                
               	
                </fieldset>   
            </div>
            <div class="col-sm-12">
                <fieldset>
                   
                        &nbsp;<p><legend>  &nbsp; ii. Last Examination Details</legend></p>

                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                            <thead>
                                <tr>
                                    <th>Name of Institution</th>
                                    <th>Place</th>
                                    <th>Board/University</th>
                                    <th>Passing Year</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                   
                                    <td> <?= !empty($this->paginator['l_institution'])?$this->paginator['l_institution']:'N/A' ?></td>
                                    <td> <?= !empty($this->paginator['l_place'])?$this->paginator['l_place']:'N/A' ?></td>
                                    <td> <?= !empty($this->paginator['last_board'])?$this->paginator['last_board']:'N/A' ?></td>
                                    <td> <?= !empty($this->paginator['l_p_year'])?$this->paginator['l_p_year']:'N/A' ?></td>
                                   
                                </tr>

                            </tbody>
                        </table>
                    <?php }else{ ?>
                        <fieldset>
                   
                    &nbsp;<p><legend>  &nbsp;i. Intermediate Education Details</legend></p>
                <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                    <thead>
                        <tr>
                            <th>School/College</th>
                            <th>Board/University</th>
                            <th>Division/Grade</th>
                            <th>Roll No</th>
                            <th>Obtained Marks</th>
                            <th>Total Marks</th>
                            <th>Percentage </th>
                            <th>Passing Year</th>
                        </tr>
                    </thead>
                    <tbody>
                      
                        <tr>
                            <td> <?= !empty($this->paginator['school'])?$this->paginator['school']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['i_board'])?$this->paginator['i_board']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['i_division'])?$this->paginator['i_division']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['i_roll'])?$this->paginator['i_roll']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['obt_marks'])?$this->paginator['obt_marks']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['total_marks'])?$this->paginator['total_marks']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['percent'])?$this->paginator['percent']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['i_pass_year'])?$this->paginator['i_pass_year']:'N/A' ?></td>
                                
                        </tr>
                   
                    </tbody>
                </table>
                     &nbsp;<p><legend>  &nbsp;ii. Last Examination Details</legend></p>

                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                            <thead>
                                <tr>
                                    <th>Name of Institution</th>
                                    <th>Place</th>
                                    <th>Board/University</th>
                                    <th>Passing Year</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                   <td> <?= !empty($this->paginator['l_institution'])?$this->paginator['l_institution']:'N/A' ?></td>
                                    <td> <?= !empty($this->paginator['l_place'])?$this->paginator['l_place']:'N/A' ?></td>
                                    <td> <?= !empty($this->paginator['last_board'])?$this->paginator['last_board']:'N/A' ?></td>
                                    <td> <?= !empty($this->paginator['l_p_year'])?$this->paginator['l_p_year']:'N/A' ?></td>

                                </tr>

                            </tbody>
                        </table>
                </fieldset>  
               <?php } ?>
            
        <!--- Caste Detail --->
                <fieldset>
                    &nbsp; <p><legend>&nbsp;&nbsp;iii.Caste Details:</legend></p>
                
            
          <!------Sesond Row------->
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label"> Caste Category<span class="asterisk">*</span></label><br>
                         <?php if(!empty($this->paginator['caste_category'])){
                             echo $this->paginator['caste_category'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Caste <span class="asterisk">*</span></label><br>
                        <?php if(!empty($this->paginator['caste'])){
                             echo $this->paginator['caste'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Certificate Issued By<span class="asterisk">*</span></label><br>
                        <?php if(!empty($this->paginator['certificate_issued'])){
                             echo $this->paginator['certificate_issued'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Caste Certificate No.<span class="asterisk">*</span></label><br>
                       <?php if(!empty($this->paginator['certificate_no'])){
                             echo $this->paginator['certificate_no'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>
              
             	
                </fieldset>  
                <fieldset>
                    &nbsp; <p><legend>&nbsp;&nbsp;iv.Extra-Curricular Activities:</legend></p>
                    <div class="col-sm-12 employee_class">
                        <div class="form-group">
                           <?php if($this->paginator['ExtraCurricularSelection']){
                             echo $this->paginator['ExtraCurricularSelection'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                        </div>
                    </div>
                
                </fieldset> 
                <fieldset>
                    &nbsp; <p><legend>&nbsp;&nbsp;v.Uploaded Documents:</legend></p>
                    <div class="col-sm-12 employee_class">
                        <div class="form-group">
                           
                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                                <tbody>
                                    <thead>
                                        <tr>
                                            <th>Photo</th>
                                            <th> Baptism Certificate</th>
                                            <th>Mark's Sheet/Admit Card</th>  
                                            <th>Caste Certificate</th>  
                                        </tr>
                                    </thead>
                                    <tr>
                                       <?php  preg_match('/.*\.(pdf|jpg|jpeg|png)/', $this->paginator['photo'], $output_array); ?>
                                        <td class="zoom">
                                             <?php if($this->paginator['photo']){
                                                 if($output_array[1] !='pdf'){?>
                                                     <img src="<?php echo $this->baseUrl($this->paginator['photo']);?>" alt="img" height="150" width="200"> 
                                              <?php   }else{?>
                                                     <div class="col-sm-3">
                                                         <a href="<?php echo $this->baseUrl($this->paginator['photo']);?>" <i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>
                                                     </div>
                                                   
                                           <?php    }?>
                                          
                                            <?php } else{
                                            echo 'Not Uploaded';
                                            }
                                            ?>
                                        </td>

                                        <td class="zoom">
                                            <?php  preg_match('/.*\.(pdf|jpg|jpeg|png)/', $this->paginator['baptism'], $output_array); 
                                           // echo '<pre>'; print_r($this->paginator['baptism']);
                                            ?>
                                            <?php if($this->paginator['baptism']){
                                                
                                                  if(isset($output_array[1]) && $output_array[1]!='pdf'){?>
                                                     <img src="<?php echo $this->baseUrl($this->paginator['baptism']);?>" alt="img" height="150" width="200"> 
                                              <?php   }else{?>
                                                     <div class="col-sm-12">
                                                         <a href="<?php echo $this->baseUrl($this->paginator['baptism']);?>"target="_blank">  <i style="font-size:10em"class="fa fa-file-pdf-o" aria-hidden="true"></i></a>
                                                     </div>
                                                   
                                           <?php    }?>
                                        <?php } else{
                                             echo 'Not Uploaded';
                                            }
                                        ?>    
                                        </td> 
                                        <td class="zoom">
                                            <?php  preg_match('/.*\.(pdf|jpg|jpeg|png)/', $this->paginator['educertificate'], $output_array); ?>
                                           <?php if($this->paginator['educertificate']){
                                                 if(isset($output_array[1]) && $output_array[1]!='pdf'){?>
                                                     <img src="<?php echo $this->baseUrl($this->paginator['educertificate']);?>" alt="img" height="150" width="200"> 
                                              <?php   }else{?>
                                                     <div class="col-sm-12">
                                                         <a href="<?php echo $this->baseUrl($this->paginator['educertificate']);?>"target="_blank">  <i style="font-size:10em"class="fa fa-file-pdf-o" aria-hidden="true"></i></a>
                                                     </div>
                                                   
                                           <?php }?>
                                             <?php } else{
                                                echo 'Not Uploaded';
                                            }?>
                                        </td> 
                                        <td class="zoom">
                                            <?php  preg_match('/.*\.(pdf|jpg|jpeg|png)/', $this->paginator['casteCertificate'], $output_array); ?>
                                             <?php if($this->paginator['casteCertificate']){
                                                 if(isset($output_array[1]) && $output_array[1]!='pdf'){?>
                                                     <img src="<?php echo $this->baseUrl($this->paginator['casteCertificate']);?>" alt="img" height="150" width="200"> 
                                              <?php   }else{?>
                                                     <div class="col-sm-12">
                                                         <a href="<?php echo $this->baseUrl($this->paginator['casteCertificate']);?>"target="_blank">  <i style="font-size:10em"class="fa fa-file-pdf-o" aria-hidden="true"></i></a>
                                                     </div>
                                                   
                                           <?php    }?>
                                            
                                            <?php } else{
                                                echo 'Not Uploaded';
                                            }
                                            ?>
                                        </td> 
                                        
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                
                </fieldset> 
        <div class="row">
                <div class="col-sm-12 employee_class">
                
                   
                </div>
            </div>
            <br />
        <div style="float:right;margin-right:2px;padding-bottom: 3em;">
           
            <a href="<?=  $this->baseUrl("multi-step-form/index/type/step3/a_id/".md5($this->paginator['application_no'])); ?>"> <button type="button" id="previous" class="btn custPre">Back</button></a>
            <button type="button" id="finalSubmit" class="btn btn-success  next">Submit Application Form</button>
            
        </div>
        </div>
             </form>
        </div>
        <?php } if($this->type== 'step5'){ ?>
<div class="paymentMode">
<div class="multistepformArea col-xs-12 col-xs-offset-0  col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2  col-lg-8 col-lg-offset-2">
<form class="regForm" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >


<div class="row">
    <div class="col-sm-12">
      <fieldset>

             <p><legend >&nbsp;&nbsp; Payment Mode: </legend></p>
                <?php ///print_r($this->paginator);?>
        <p>&nbsp; &nbsp; Dear <b><?= ucfirst($this->paginator['applicant_name'] )?></b> , your Form Id is: <b><?= $this->paginator['form_id'] ?></b> </p> 
	<?php if($this->paginator['photo']){	  ?>
		<p > &nbsp; &nbsp; Please choose the following payment method for final submission of your form. </p></br>
      <?php } else if($this->paginator['form_id'] == '0' ) { ?> 
        <p style="color:red;">&nbsp; &nbsp;Please Submit your Form..!</p>
        <a href="<?=  $this->baseUrl("multi-step-form/index/type/step4/a_id/".md5($this->paginator['application_no'])); ?>" class='btn btn-primary'>click here</a>
    <?php   }else {?>
                        <p style="color:red;">&nbsp; &nbsp;please upload your photo. size in between 50 to 100 kb</p>
                        <a href="<?=  $this->baseUrl("multi-step-form/index/type/step3/a_id/".md5($this->paginator['application_no'])); ?>" class='btn btn-primary'>Upload</a>
                
                <?php } ?> 
		  <div class="col-sm-6  employee_class"></div>
           <div class="col-sm-6  employee_class">
                 
                 
                <?php if($this->paginator['photo']){ if($this->paymode ==='R') { ?>
                <div class="form-group">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
                    <a href="<?=  $this->baseUrl("multi-step-form/payment/a_id/".md5($this->paginator['application_no'])); ?>"> <button  type="button" id="onlinePayment" value="Online" class="btn btn-primary submit paymentMode">Online Payment</button></a>
                    
                </div>
                 <?php } else if($this->paymode ==='A'){ ?>
               <div class="form-group">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
                    <a href="<?=  $this->baseUrl("multi-step-form/atompayment/a_id/".md5($this->paginator['application_no'])); ?>"> <button  type="button" id="onlinePayment" value="Online" class="btn btn-primary submit paymentMode">Online Payment</button></a>
                    
                </div>
                
                  <!----- Payment- New Admission <div class="form-group">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
                    <a href="<?=  $this->baseUrl("multi-step-form/atompayment/a_id/".md5($this->paginator['application_no'])); ?>"> <button  type="button" id="onlinePayment" value="Online" class="btn btn-primary submit paymentMode">Online Payment</button></a>
                    
                </div>-->
                
                <?php } }?>
                
               
            </div>
        <!----- <div class="col-sm-3 employee_class">
            <div class="form-group">
              <button type="button"  value="Offline" id="offlinePayment" class="btn custPre paymentMode">Offline</button>
               

            </div>
        </div>--->
        
        </fieldset> 

    </div>
</div>


<div style="float:right;margin-right:2px;padding-bottom: 3em;">

</div>

</div>
</div>
        <?php } ?>
         <div class="load-box">
            <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader2.gif" style="width:8em"  class="loder_img1" />
        </div>
    <div class="challan" id="challan">

    </div>
         
<script>
    //step validation
    	$("#customankel4").on("click", function(){
        var a_id='<?php echo isset($this->a_id)? $this->a_id:'';?>';
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/check-form-step'; ?>',
            data: {a_id:a_id}
        }).done(function (data) {
            //alert(data);
          
			if(data == 'preview_ok'){
				window.location ='<?php echo $this->mainconfig['host'] . "multi-step-form/index/type/step4/a_id/"?>'+a_id;
                //alert('kp');
                return false;
			}
            if( data == 'educational_ok' ){
				window.location ='<?php echo $this->mainconfig['host'] . "multi-step-form/index/type/step3/a_id/"?>'+a_id;
			 return false;
            } 
            if( data == 'personal_ok' ){
				window.location ='<?php echo $this->mainconfig['host'] . "multi-step-form/index/type/step2/a_id/"?>'+a_id;
                 return false;
			}
			if(data == 'false'){
				 window.location ='<?php echo $this->mainconfig['host'] . "multi-step-form/index/type/step1/a_id/"?>'+a_id;
                 return false;
			}
            
          
        });
    });
    
    $("#customankel3").on("click", function(){
        var a_id='<?php echo isset($this->a_id)? $this->a_id:'';?>';
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/check-form-step'; ?>',
            data: {a_id:a_id}
        }).done(function (data) {
           // alert(data);
			if(data == 'educational_ok'){
                //alert('kk');
				window.location ='<?php echo $this->mainconfig['host'] . "multi-step-form/index/type/step3/a_id/"?>'+a_id;
                return false;
			} 
            if( data == 'personal_ok' ){
				window.location ='<?php echo $this->mainconfig['host'] . "multi-step-form/index/type/step2/a_id/"?>'+a_id;
                return false;
            }
            if(data == 'false'){
				 window.location ='<?php echo $this->mainconfig['host'] . "multi-step-form/index/type/step1/a_id/"?>'+a_id;
                 return false;
			}else{
                window.location ='<?php echo $this->mainconfig['host'] . "multi-step-form/index/type/step3/a_id/"?>'+a_id;
                return false;
            }
            
          
        });
    });
    
    $("#customankel2").on("click", function(){
        var a_id='<?php echo isset($this->a_id)? $this->a_id:'';?>';
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/check-form-step'; ?>',
            data: {a_id:a_id}
        }).done(function (data) {
            //alert(data);
			 
            if( data == 'personal_ok' ){
				window.location ='<?php echo $this->mainconfig['host'] . "multi-step-form/index/type/step2/a_id/"?>'+a_id;
			
            }
            if(data == 'false'){
				 window.location ='<?php echo $this->mainconfig['host'] . "multi-step-form/index/type/step1/a_id/"?>'+a_id;
			}
            else{
                window.location ='<?php echo $this->mainconfig['host'] . "multi-step-form/index/type/step2/a_id/"?>'+a_id;
                return false;
            }
            
          
        });
    });
	
 //ProgressBar code :10 Jan 2020 : Kedar
    var steps= "<?php echo $this->type ?>";
    var all;
    
    if (steps == 'step1') {
         $("#customankel1").addClass("cureentLi");
        all = document.getElementsByClassName('l1');
        for (var i = 0; i < all.length; i++) {
            all[i].style.color = '#337ab7';
        }
    }else if(steps == 'step2') {
        $("#customankel2").addClass("cureentLi");
        $("#customankel1").addClass("customankel");
        $(".l1").addClass("active");
        all = document.getElementsByClassName('l2');
        
        for (var i = 0; i < all.length; i++) {
            all[i].style.color = '#337ab7';
        }
    }else if(steps == 'step3') {
        $("#customankel2").addClass("customankel");
        $("#customankel1").addClass("customankel");
        $("#customankel3").addClass("cureentLi");
        $(".l2").addClass("active");
        $(".l1").addClass("active");
        all = document.getElementsByClassName('l3');
        
        for (var i = 0; i < all.length; i++) {
            all[i].style.color = '#337ab7';
        }
    }else if(steps == 'step4') {
        $("#customankel2").addClass("customankel");
        $("#customankel1").addClass("customankel");
        $("#customankel3").addClass("customankel");
        $("#customankel4").addClass("cureentLi");
        $(".l3").addClass("active");
        $(".l2").addClass("active");
        $(".l1").addClass("active");
        all = document.getElementsByClassName('l4');
        
        for (var i = 0; i < all.length; i++) {
            all[i].style.color = '#337ab7';
        }
    }else if(steps == 'step5') {
        $("#customankel2").addClass("customankel");
        $("#customankel1").addClass("customankel");
        $("#customankel3").addClass("customankel");
        $("#customankel4").addClass("customankel");
        $("#customankel5").addClass("cureentLi");
        
        $(".l4").addClass("active");
        $(".l3").addClass("active");
        $(".l2").addClass("active");
        $(".l1").addClass("active");
        all = document.getElementsByClassName('l5');
        
        for (var i = 0; i < all.length; i++) {
            all[i].style.color = '#337ab7';
        }
    }else{
         $('.l1,.l2,.l3,.l4,.l5').removeClass("active");
    }
    
//End
$( document ).ready(function() {

  
    var c_id = $('#course').val();
    //alert(c_id);
    if(c_id){
        $('#tablea').show();
        $('.getablea').empty(); 
        $('.getableb').empty();  
    
        var degree_id = $('#degree_id').val();
        var session_id = $('#session').val();

        if(degree_id == 1 && c_id == 1 || c_id == 2){
            $('#preftablea').html('(A) First Preference');
            $('#tableb').show(); 
            $('#tableb').show().prop('required',true);
            //$('.core_coursetableb [name=secondChoice]').prop("required", true);

        }else{
            $('#preftablea').html('');
            $('.coreTable').html('All Course');
            $('[name="aecc2"]').hide().prop('required',false);
           
            $('#tableb').hide().prop('required',false);
        }
        
        $('#academic_id').empty('');
        $('.chosen-select').trigger('chosen:updated');
        
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/ajax-Get-Core-Course'; ?>',
            data: {c_id: c_id,session_id:session_id}
        }).done(function (data) {
            //alert(data);
            if(data){
                $('.core_coursetablea').empty(); 
                $('.core_coursetablea').html(data);
                $('.core_coursetablea input[type="radio"]').attr({
                                                                class:'firstPref', 
                                                                name:'firstChoice'
                                                            });
                //To Select First Core Course1
                var core1=  '<?= isset($this->paginator['core_course1']) ? $this->paginator['core_course1']:''?>';
                if($('.core_coursetablea table').index()!= -1){
                    $('.core_coursetablea table input[type="radio"]').each(function(index){
                       if(parseInt($(this).val()) == core1){
                           $(this).attr('checked','checked');
                       }
                    });
                  }
            $('.core_coursetableb').html(data);
            $('.core_coursetableb input[type="radio"]').attr({
                                                                class:'secondPref', 
                                                                name:'secondChoice'
                                                            });
                                                            
                                                  var core2=  '<?= isset($this->paginator['core_course2']) ? $this->paginator['core_course2']:''?>';          
                      if($('.core_coursetableb table').index()!= -1){
                      $('.core_coursetableb table input[type="radio"]').each(function(index){
                        if(parseInt($(this).val()) == core2){
                            $(this).attr('checked','checked');
                        }
                      });
                  }
        
               
            if(degree_id !=1){
                $('.coreTable').html("<table class='table table-striped table-bordered mb30 jambo_table bulk_action''><tbody><tr><td><label>All Subject (Prescribed in Syllabus)</label> <label></td></tr></tbody></table>");
                $('#tableb').hide().prop('required',false); 
                
                $('tbody tr:nth-child(2),tr:nth-child(3),tr:nth-child(4)').hide();
            }
            else{
                  $('tbody tr:nth-child(2),tr:nth-child(3),tr:nth-child(4)').show();
            }

            $('.core_coursetableb [name=secondChoice]').removeAttr('required');
            } 
               
        });
        
        //To show First Ge
        var academic_id=  '<?= isset($this->paginator['core_course1']) ? $this->paginator['core_course1']:''?>';
       
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/ajax-get-ge'; ?>',
            data: {academic_id: academic_id}
        }).done(function (data) {

            $('.getablea').html(data);
            $('.getablea  input[type="radio"]').attr('name','geFirst');
          
                var ge1= '<?= isset($this->paginator['ge1'])?$this->paginator['ge1']:''?>';
                    //alert(ge1);
                var $radios = $('input:radio[name=geFirst]');
                $radios.filter('[value='+parseInt(ge1)+']').prop('checked', true);
        });
        //To show Second Ge
        
        var academic_id= '<?= isset($this->paginator['core_course2'])?$this->paginator['core_course2']:'' ?>';
         
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/ajax-get-ge'; ?>',
                data: {academic_id: academic_id}
            }).done(function (data) {

                $('.getableb').html(data);
                $('.getableb  input[type="radio"]').attr('name','geSecond');
               
                    var ge2= '<?= isset($this->paginator['ge2'])?$this->paginator['ge2']:'' ?>';
                    //alert(ge2);
                    var $radios = $('input:radio[name=geSecond]');
                    console.log($radios);
                    $radios.filter('[value='+parseInt(ge2)+']').prop('checked', true);
                });
       
    }
    //Code SameAddress on load
    var sameAddress = '<?= $this->paginator['same_address'];?>';
    if(sameAddress){
        $('#l_address').attr("readonly", true); 
        $('#l_homeTown').attr("readonly", true); 
        $('#l_postOffice').attr("readonly", true); 
        $('#l_policeSt').attr("readonly", true); 
        $('#l_district').attr("readonly", true); 
        $('#l_state').attr("readonly", true); 
        $('#l_code').attr("readonly", true); 
    }

});
//Date 08 Jan 2020 : Kedar
    //Course category on the basis of degree
    $('#tableb').hide().prop('required',false);
    $('#tablea').hide().prop('required',false);
   
        //alert(degree_id);
        $('#academic_id').empty('');
        $('.chosen-select').trigger('chosen:updated');

    $('body').on('change', '#degree_id', function () {
        
        var degree_id = $('#degree_id').val();
        
        if(degree_id==1){
           $('#notice').show();
             $('#notice').html('<a style = "float:right" href="<?php echo $this->mainconfig['host'] ?>public/pdfUpload/Admission-Notice-for-B.A-B.Sc.pdf" target="_blank" class="btn btn-primary" id="ba2">Notice For BA/BSC</a>  <a href="<?php echo $this->mainconfig['host'] ?>public/pdfUpload/Admission-Notce-for-B.Com..pdf" target="_blank" class="btn btn-primary" id="ba2">Notice For BCOM</a> <a href="<?php echo $this->mainconfig['host'] ?>public/pdfUpload/Admission-Notice-for-all-Streams.pdf" target="_blank" class="btn btn-primary" id="ba2">Notice For All Streams</a>');
        }
        
       else if(degree_id==2){
          $('#notice').show();
           
             $('#notice').html('<a style = "float:right" href="<?php echo $this->mainconfig['host'] ?>public/pdfUpload/Admission-Notice-for-PG-Courses.pdf" target="_blank" class="btn btn-primary" id="pg">Notice For PG </a><a href="<?php echo $this->mainconfig['host'] ?>public/pdfUpload/Admission-Notice-for-all-Streams.pdf" target="_blank" class="btn btn-primary" id="ba2">Notice For All Streams</a>');
             
        } else 
        { $('#notice').html('<a style = "float:right" href="<?php echo $this->mainconfig['host'] ?>public/pdfUpload/Admission-Notice-for-all-Streams.pdf" target="_blank" class="btn btn-primary" id="ba2">Notice For All Streams</a>');}
        
       // alert(degree_id);
        $('#academic_id').empty('');
        $('.chosen-select').trigger('chosen:updated');
        if (degree_id !=1) {
            
            $('.ge').hide().prop('required',false);
            $('[name="aecc2"]').hide().prop('required',false);
            $('.core_coursetableb input[name="secondChoice"]').hide().prop('required',false);
            $('#tableb').hide().prop('required',false);
            $('.coreTable').hide().prop('required',false);
        }else{
            $('.ge').show();
            //$('#tableb').show();  
            $('.coreTable').show();
            $('.coreTable').html('');
            
        }
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/ajax-Get-Course'; ?>',
            data: {degree_id: degree_id}
        }).done(function (data) {
            //alert(data);
            $('#course').html(data);
            $('#course').trigger("chosen:updated");
        });
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/ajax-Get-Session'; ?>',
            data: {degree_id:degree_id}
        }).done(function (data) {
            //alert(data);
            $('#session').html(data);
            $('#session').trigger("chosen:updated");
        });
    });
    //End 
    //Core Course on the basis of Course
    $('#tableb').hide().prop('required',false);
    $('body').on('change', '#course', function () {
        $('.load-box').show();
        $('#tablea').show();
        $('.getablea').empty(); 
        $('.getableb').empty(); 
        var c_id = $('#course').val();
        var degree_id = $('#degree_id').val();
        var session_id = $('#session').val();
        //alert(c_id);
        
        
        
        if(degree_id == 1 && c_id == 1 || c_id == 2){
            $('#preftablea').html('(A) First Preference');
            $('#tableb').show(); 
            $('[name="aecc2"]').show();
        }else{
            $('#preftablea').html('');
            $('.coreTable').html('All Course');
            $('[name="aecc2"]').hide().prop('required',false);           
            $('#tableb').hide().prop('required',false);
        }
        
        $('#academic_id').empty('');
        $('.chosen-select').trigger('chosen:updated');

        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/ajax-Get-Core-Course'; ?>',
            data: {c_id: c_id,session_id:session_id}
        }).done(function (data) {
            //alert(data);
            $('.core_coursetablea').html(data);
            $('.core_coursetablea input[type="radio"]').attr({
                                                                class:"firstPref", 
                                                                name:"firstChoice"
                                                            });

            $('.core_coursetableb').html(data);
            $('.core_coursetableb input[type="radio"]').attr({
                                                                class:"secondPref", 
                                                                name:"secondChoice"
                                                            });
            if(degree_id !=1){
                $('.coreTable').html("<table class='table table-striped table-bordered mb30 jambo_table bulk_action''><tbody><tr><td><label>All Subject (Prescribed in Syllabus)</label> <label></td></tr></tbody></table>");
                $('#tableb').hide().prop('required',false); 
                
                $('tbody tr:nth-child(2),tr:nth-child(3),tr:nth-child(4)').hide();
            }
            else{
                  $('tbody tr:nth-child(2),tr:nth-child(3),tr:nth-child(4)').show();
            }
            
               
                
               
                var arr =  ["4", "16", "17","18","19","20","21"];
                if($.inArray(c_id , arr) !== -1){
                    $('.core_coursetablea table input[type="radio"]').attr('checked','checked');    
                    var radioValue = $('.core_coursetablea table input[type="radio"]'). val();
                    $('.core_coursetableb [name=secondChoice]').removeAttr('required');
                    $.ajax({
                        type: "POST",
                        url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/ajax-get-ge'; ?>',
                        data: {academic_id: radioValue}
                    }).done(function (data) {

                        $('.getablea').html(data);
                        $('.getablea  input[type="radio"]').attr('name','geFirst');
                   
                         
                    });
                }
                $('.load-box').hide();
                //alert(degree_id);                                                
    });
});
//End 

//To get ge from core course from table A
$('body').on('click', '#tablea', function () {
    $('.firstPref').on('change', function() {
        $('.getablea').empty(); 
        var academic_id=  $(this).closest('tr').find('.firstPref').val( );
        //$(this).prop('checked',true);
        //alert(academic_id);
        // alert('table1');
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/ajax-get-ge'; ?>',
            data: {academic_id: academic_id}
        }).done(function (data) {

            $('.getablea').html(data);
            $('.getablea  input[type="radio"]').attr('name','geFirst');
   
        });
        return false;
    });

});

//To get ge from core course from table B
$('body').on('click', '#tableb', function () {
        $('.secondPref').on('change', function() {
            $('.getableb').empty(); 
            var academic_id=  $(this).closest('tr').find('.secondPref').val( );
            $(this).prop('checked',true);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/ajax-get-ge'; ?>',
                data: {academic_id: academic_id}
            }).done(function (data) {

                $('.getableb').html(data);
                $('.getableb  input[type="radio"]').attr('name','geSecond');
              
            });
            return false;
        });
    });
//Code for aecc subject and compulsory subject
$(document).ready(function () {

       $(".aecctablea").append("<table class='table table-striped table-bordered mb30 jambo_table bulk_action''><tbody><tr><td  style='border: none;float:right;'><label>Hindi </label> </td><td><label> <input type='radio' name='aecc1' class='aecc' value='Hindi' required/></label></td><td  style='border: none;float:right'><label>English </label></td><td> <label> <input type='radio' name='aecc1' class='aecc' value='English' checked required/></label></td></tr></tbody></table>")
       
    
       $(".comptablea").append("<table class='table table-striped table-bordered mb30 jambo_table bulk_action''><tbody><tr><td><label>Environmental Science and Studies </label> <label></td><td> <input type='radio' name='evs1' class='evs' value='EVS' checked='checked'/></label></td></tr></tbody></table>")
       
       $(".comptableb").append("<table class='table table-striped table-bordered mb30 jambo_table bulk_action''><tbody><tr><td><label>Environmental Science and Studies </label> <label></td><td> <input type='radio' name='evs2' class='evs' value='EVS' checked='checked'/></label></td></tr></tbody></table>")
    });
    
$(document).ready(function () {

       $(".aecctableb").append("<table class='table table-striped table-bordered mb30 jambo_table bulk_action''><tbody><tr><td style='border: none;float:right'><label>Hindi </label> </td><td><label> <input type='radio' name='aecc2' class='aecc' value='Hindi' required/></label></td><td  style='border: none;float:right'><label>English </label></td><td> <label> <input type='radio' name='aecc2' class='aecc' value='English' checked required/></label></td></tr></tbody></table>")
});
//End   
//To copy Permanent Address
$(function () {
        $("#sameAddress").click(function () {
            if ($(this).is(":checked")) {
                var p_address= $('#p_address').val();
                var p_homeTown=$('#p_homeTown').val();
                var p_postOffice= $('#p_postOffice').val();
                var p_policeSt=$('#p_policeSt').val();
                var p_district= $('#p_district').val();
                var p_state=$('#p_state').val();
                var p_code=$('#p_code').val();
                $('#l_address').val(p_address).attr("readonly", true); 
                $('#l_homeTown').val(p_homeTown).attr("readonly", true); 
                $('#l_postOffice').val(p_postOffice).attr("readonly", true); 
                $('#l_policeSt').val(p_policeSt).attr("readonly", true); 
                $('#l_district').val(p_district).attr("readonly", true); 
                $('#l_state').val(p_state).attr("readonly", true); 
                $('#l_code').val(p_code).attr("readonly", true); 
            } else {
                $('#l_address').val('').attr("readonly", false); ;
                $('#l_homeTown').val('').attr("readonly", false); ;
                $('#l_postOffice').val('').attr("readonly", false); ;
                $('#l_policeSt').val('').attr("readonly", false); ;
                $('#l_district').val('').attr("readonly", false); ;
                $('#l_state').val('').attr("readonly", false); ;
                $('#l_code').val('').attr("readonly", false); ;
            }
        });
    });
    
//End
$('#dob').datepicker({ format: 'dd/mm/yyyy' });

$('input').focus(function(){
    var selected_date = $("#dob").val();

    if(selected_date){
        var current = selected_date;
        var date_components = current.split("/");
        var current_year = parseInt(date_components[2]);
        //console.log(current_year);
        var day = parseInt(date_components[0]);
        var month = parseInt(date_components[1]);
        var age = 16;
        var setDate = new Date(current_year + age, month - 1, day);
        //console.log(setDate);
        var currdate = new Date();

        if (currdate >= setDate) {
            $('#dobError').text("");
            

        } else {
            $('#dob').val('');
            $('#dobError').text("Age should be greater than 16 years");
            

        }       
    }
});
$("#p_code").keyup(function () {

    var pin_code = $("#p_code").val();

    if (!isNaN(pin_code))
    {

        if (pin_code.length < 7) {
            $('#pCodeError').text("");
            return true;
        } else {
            $('#pCodeError').text("Pin Code Should not  greater than 6 digits");
            $("#p_code").val("");
        }
    } else {
        $('#pCodeError').text("Required numeric value");
        $("#p_code").val("");
    }
});



$("#l_code").keyup(function () {

    var pin_code = $("#l_code").val();

    if (!isNaN(pin_code))
    {

        if (pin_code.length < 7) {
            $('#lCodeError').text("");
            return true;
        } else {
            $('#lCodeError').text("Pin Code Should not  greater than 6 digits");
            $("#l_code").val("");
        }
    } else {
        $('#lCodeError').text("Required numeric value");
        $("#l_code").val("");
    }
});
$('input').focus(function(){

var aadhar_no = $("#aadhar").val();

if (!isNaN(aadhar_no))
{

/*if (aadhar_no.length == 12) {
$('#aadharError').text("");
return true;
} else {
$('#aadharError').text("Enter a valid aadhar number.");
$("#aadhar").val("");
}*/
} else {
$('#aadharError').text("Required numeric value");
$("#aadhar").val("");
}
});
$("#total_marks").keyup(function () {

    var total_marks = $("#total_marks").val();
    var obt_marks= $("#obt_marks").val();
    var percentage= Number(Number(obt_marks)/Number(total_marks)*100).toFixed(2);
    //alert(percent);
    if(!isNaN(percentage)){
        $('#percent').val(percentage);
    }else{
        $('#percent').val('0');
    }
    

});
$("#i_pass_year").keyup(function () {

    var pass_year = $("#i_pass_year").val();
    var date = new Date();
    var current_year = date.getFullYear();
    //alert(current_year);
    if(pass_year > current_year){
        $("#i_pass_year").val('');
        alert('Year of passing should not be greater than current year');
    }
});
$("#l_p_year").keyup(function () {

    var pass_year = $("#l_p_year").val();
    var date = new Date();
    var current_year = date.getFullYear();
    //alert(current_year);
    if(pass_year > current_year){
        $("#l_p_year").val('');
        alert('Year of passing should not be greater than current year');
    }
});
$("#mat_pass_year").keyup(function () {

    var pass_year = $("#mat_pass_year").val();
    var date = new Date();
    var current_year = date.getFullYear();
    //alert(current_year);
    if(pass_year > current_year){
        $("#mat_pass_year").val('');
        alert('Year of passing should not be greater than current year');
    }
});
$("#bca_pass_year").keyup(function () {

    var pass_year = $("#bca_pass_year").val();
    var date = new Date();
    var current_year = date.getFullYear();
    //alert(current_year);
    if(pass_year > current_year){
        $("#bca_pass_year").val('');
        alert('Year of passing should not be greater than current year');
    }
});
$("#grad_math_pass_year").keyup(function () {

    var pass_year = $("#grad_math_pass_year").val();
    var date = new Date();
    var current_year = date.getFullYear();
    //alert(current_year);
    if(pass_year > current_year){
        $("#grad_math_pass_year").val('');
        alert('Year of passing should not be greater than current year');
    }
});
$("#grad_pass_year").keyup(function () {

    var pass_year = $("#grad_pass_year").val();
    var date = new Date();
    var current_year = date.getFullYear();
    //alert(current_year);
    if(pass_year > current_year){
        $("#grad_pass_year").val('');
        alert('Year of passing should not be greater than current year');
    }
});
$("#other_pass_year").keyup(function () {

    var pass_year = $("#other_pass_year").val();
    var date = new Date();
    var current_year = date.getFullYear();
    //alert(current_year);
    if(pass_year > current_year){
        $("#other_pass_year").val('');
        alert('Year of passing should not be greater than current year');
    }
});

//Ajax function for Final submit Application Form :Date:21 Jan 2020 Kedar

$('body').on('click','#finalSubmit', function(){
    var application_no = '<?php echo $this->a_id;?>';
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/ajax-generate-form-id'; ?>',
        data: {application_no: application_no}
    }).done(function (data) {
        if(data){
             location.href = '<?php echo $this->baseUrl("multi-step-form/index/type/step5/a_id/{$this->a_id}"); ?>';
        }else{
            //alert('no');
        }
    });
    
});

$('body').on('click','#offlinePayment', function(){
 
    var application_no = '<?php echo isset($this->a_id)? $this->a_id:'';?>';
    var applicant_name= '<?php echo isset($this->paginator['applicant_name'])? $this->paginator['applicant_name']: ''; ?>';
    var form_id= '<?php echo isset($this->paginator['form_id'])?$this->paginator['form_id']:'';  ?>';
    var email_id= '<?php echo isset($this->paginator['email_id'])?$this->paginator['email_id']:'';  ?>';
    var phone= '<?php echo isset($this->paginator['phone'])?$this->paginator['phone']:'' ;  ?>';
    var course = '<?php echo isset($this->paginator['course'])?$this->paginator['course']:'';  ?>';
    var challan= '<?php echo isset($this->challan['challan_no'])?$this->challan['challan_no']:'';  ?>';
    //alert(application_no);
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/ajax-insert-offline-mode'; ?>',
        data: {application_no: application_no,applicant_name:applicant_name,form_id:form_id,email_id:email_id,phone:phone,course:course,challan:challan}
    }).done(function (data) {
        
        if(data){
             $('#challan').empty(data);
             $('#challan').html(data);
             $('.paymentMode').hide();
        }else{
            //alert('no');
        }
    });
});

//End

//Jquery for caste selection field
    var selectedCaste = $("#caste_category").children("option:selected").val();
    if(selectedCaste == 'General'){
        $("#certificate_issued,#certificate_no").val(''); 
        $("#certificate_issued,#certificate_no").attr('disabled','disabled').trigger("chosen:updated");   
        $("#certificate_issued,#certificate_no").removeAttr('required').trigger("chosen:updated"); 
    }else{
        $("#certificate_issued option:first").attr('selected','selected');
        $("#certificate_issued,#certificate_no").removeAttr('disabled').trigger("chosen:updated"); 
        $("#certificate_issued,#certificate_no").attr('required','required').trigger("chosen:updated"); 
    }
    $("select#caste_category").change(function(){
        var selectedCaste = $(this).children("option:selected").val();
        if(selectedCaste == 'General'){
            $("#certificate_issued,#certificate_no").attr('disabled','disabled').trigger("chosen:updated");   
            $("#certificate_issued,#certificate_no").val('');   
            $("#certificate_issued,#certificate_no").removeAttr('required').trigger("chosen:updated"); 
        }else{
            $("#certificate_issued option:first").attr('selected','selected');
            $("#certificate_issued,#certificate_no").removeAttr('disabled').trigger("chosen:updated"); 
            $("#certificate_issued,#certificate_no").attr('required','required').trigger("chosen:updated"); 
        }
    });
    //Other Religion Column
        var selectedReligion = $('#religion').children("option:selected").val();
        if(selectedReligion == 'others'){
            $("#others_rel").show();
            $("#others_religion").attr('required','required'); 
          
        }else{
            $("#others_rel").hide();
            $("#others_religion").removeAttr('required'); 
        }
    
     //$("#others_rel").hide();
     
    $("select#religion").change(function(){
        var selectedReligion = $(this).children("option:selected").val();
        if(selectedReligion == 'others'){
            $("#others_rel").show();
            $("#others_religion").attr('required','required'); 
          
        }else{
            $("#others_rel").hide();
            $("#others_religion").removeAttr('required'); 
        }
    });
    
    $('body').on('click','#firstStep', function(){
        var degree_id= $("#degree_id").val();
        var course= $("#course").val();
        if(!course){
            alert('Please select the required field');
        }
        if(!degree_id){
            alert('Please select the required field');
        }
    });
    //For appearing Status
        var status= '<?= $this->paginator['appearingStatus'] ?>';
        var degree_id= '<?= $this->followup['degree_id'] ?>';
       
           if(degree_id !=1 && status ==1){
                //$("#i_division,#i_pass_year").val('');  
               $("#grad_math_division,#grad_division,#grad_pass_year,#grad_math_pass_year,#bca_division,#bca_pass_year").attr('disabled','disabled');
           }else{
               $("#grad_math_division,#grad_division,#grad_pass_year,#grad_math_pass_year,#bca_division,#bca_pass_year").removeAttr('disabled');
               $("#grad_math_division,#grad_division,#grad_pass_year,#bca_division").attr('required','required');
           }
           
        if(status == 1){
            var paragraph = document.getElementById("p");
            var text = document.createTextNode("Upload Admit Card");
            $('#p').empty();
            paragraph.appendChild(text);
            if(degree_id == 1){
                $("#i_division,#obt_marks,#total_marks,#percent,#i_pass_year").val(''); 
                $("#i_division,#obt_marks,#total_marks,#percent,#i_pass_year").attr('disabled','disabled');   
            }
              
        }else{
            var paragraph = document.getElementById("p");
            var text = document.createTextNode("Upload  Marksheet");
            $('#p').empty();
            paragraph.appendChild(text);
            if(degree_id == 1){
                $("#i_division,#obt_marks,#total_marks,#percent,#i_pass_year").removeAttr('disabled');
            }
        }
    $(function(){
        
        $('[name="appearingStatus"]').change(function(){
           var status= $(this).val();
           let degree_id= '<?= $this->followup['degree_id'] ?>';
           if(degree_id !=1 && status ==1){
                $("#i_division,#i_pass_year").val('');  
                $("#grad_math_division,#grad_division,#grad_pass_year,#grad_math_pass_year,#bca_division,#bca_pass_year").attr('disabled','disabled');
           }else{
                $("#grad_math_division,#grad_division,#grad_pass_year,#grad_math_pass_year,#bca_division,#bca_pass_year").removeAttr('disabled');
                $("#grad_math_division,#grad_division,#grad_pass_year,#bca_division").attr('required','required');
           }
           
           if(status == 1){
                var paragraph = document.getElementById("p");
                var text = document.createTextNode("Upload Admit Card");
                $('#p').empty();
                paragraph.appendChild(text);
                if(degree_id == 1){
                    $("#i_division,#i_pass_year,#obt_marks,#total_marks,#percent").val('');  
                    $("#i_division,#i_pass_year,#obt_marks,#total_marks,#percent").attr('disabled','disabled');
                }
           
           }else{
                var paragraph = document.getElementById("p");
                var text = document.createTextNode("Upload  Marksheet");
                $('#p').empty();
                paragraph.appendChild(text);
                if(degree_id == 1){
                    $("#i_division,#i_pass_year,#obt_marks,#total_marks,#percent").removeAttr('disabled');
                    $("#i_division,#i_pass_year,#obt_marks,#total_marks,#percent").attr('required','required');
                }
           }
        });          
    });
    
     
    
//Runtime Image view on change of image file  Author: Kedar Date: 03 MArch 2020
    function readImgURL(input) {
        if (input.files && input.files[0]) {
        var reader = new FileReader();
            reader.onload = function(e) {
                 var type =  e.target.result.split("/")[1];
                type = type.split(";")[0]
                if(type!="pdf"){
                    if( $(input).parent().next().find('img').length !=0){
                $(input).parent().next().find('img').attr('src', e.target.result);
            }
            else{
                $(input).parent().next().append('<img id="eduFile" src="" style="width:5em;" >');
                
              $(input).parent().next().find('img').attr('src', e.target.result);  
            }
            $(input).parent().next().find('a').remove();
            }
              else{
                //$(input).parent().next().html('<a href="javascript:0;">pdf file</a>');
                $(input).parent().next().find('img').remove();
            }
            }
            
            
            reader.readAsDataURL(input.files[0]);
            
        }
    }
    $('input[type="file"]').change(function() {
        readImgURL(this);
    });
    
    $('#baptism').change(function() {
        var type=$(this).val();
       
        var url = type
        var arguments = url.split('.');
        arguments.shift();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/file-upload-validation'; ?>',
            data: {file_type: arguments}
        }).done(function (data) {
            if(data != 1){
                alert('Only .jpg or .png or .pdf files can be uploaded');
                $('#baptism').val('');
            }
        });
        
    });
    $('#photo').change(function() {
        var type=$(this).val();
       
        var url = type
        var arguments = url.split('.');
        arguments.shift();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/photo-upload-validation'; ?>',
            data: {file_type: arguments}
        }).done(function (data) {
            if(data != 1){
                alert('Only .jpg or .png files can be uploaded');
                $('#photo').val('');
            }
        });
        
    });
    $('#casteCertificate').change(function() {
        var type=$(this).val();
       
        var url = type
        var arguments = url.split('.');
        arguments.shift();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/file-upload-validation'; ?>',
            data: {file_type: arguments}
        }).done(function (data) {
            if(data != 1){
                alert('Only .jpg or .png or .pdf files can be uploaded');
                $('#casteCertificate').val('');
            }
        });
    });
    $('#educertificate').change(function() {
        var type=$(this).val();
       
        var url = type
        var arguments = url.split('.');
        arguments.shift();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'multi-step-form/file-upload-validation'; ?>',
            data: {file_type: arguments}
        }).done(function (data) {
            if(data != 1){
                alert('Only .jpg or .png or .pdf files can be uploaded');
                $('#educertificate').val('');
            }
        });
        
    });
//Step click check ajax :date:20 March 2020

</script>                 